### ISSUE TITLE
Add Semi-automatic image support?

### ISSUE THREAD

**Issue by Funtime60** [JimmXinu/FanFicFare#1007]
Would it be possible to have FFF output the image URL from sites using FlareSolverr for the user to manually download and then have FFF match them by file name to the correct EPUB? The first 2 steps are easy enough to do entirely manually, but the final step is the hard part unless I'm doing it wrong. Manually editing each metadata is a pain.

**Comment by JimmXinu** [comment]
Might be able to do something.  Calibre's Edit Book feature has an option for 'Download external resources'...

What site are you using FlareSolverr with that has images? And can you provide an example story URL (preferably SFW) with images?

**Comment by Funtime60** [comment]
Scribble hub. Since it REQUIRES FS and FS doesn't support images I have to download them manually. I used curl with FS to get the images cdn link and then use jdownloader2 to download them in bulk. I'll try to get a link ASAP since I'm on mobile.

**Comment by Funtime60** [comment]
Story url: https://www.scribblehub.com/series/852237/azure-orphans/
Image url: https://cdn.scribblehub.com/images/42/azure-orphans_852237_1693354371.jpg

My hope is that FFF could check for an image and then output the image url and then monitor a folder for image files with a matching filename.

**Comment by Funtime60** [comment]
This is mainly because I operate in batches. I spend several hours looking for decent stories with a specific search/tag(s) and then import them all at the end once I'm sure I've exhausted the matching stories.

**Comment by JimmXinu** [comment]
I've had a few different ideas:

### Keep Remote Image Links
My first idea was to add a setting to FFF to keep `<img>` tags with their original `src` attribute intact.

Calibre's Edit Book has an option to 'Download external resources' and I've tested that it was able to download and embed images both from the `cdn.scribblehub` link you provided and the `i.ibb.co` image links in that story's text.  

- A CLI tool to do the same would seem possible and may be available, but I didn't immediately find one.
- FFF's cover image processing is kinda complex.  I'm not sure how remote links would fit in exactly.
- FFF's image processing (resizing, convert, etc) isn't done.

### Convert Image Links
Closer to your original request, I could add a feature to configurably change image links, somewhat like `replace_metadata`.  Remote image links could be transformed to `file://` URLs.

Recent issue #1004 could also have been addressed this way instead of hard-code. 

- Getting the list of images to download in the first place is another step, either manually or by running another pass of FFF.  
- Plus actually downloading images, of course.

### Force Normal Fetch (instead of Proxy) for Images
'Download external resources' working lead me to test whether we could just skip the proxy for images.  This seems to work for the given story's first few chapters containing one `cdn.scribblehub` and 5 `i.ibb.co` images.  This would appear to be the least work for everybody.

- There's no guarantee it would work for any other stories.


Would you be willing to test a version with 'Force Normal Fetch' for various stories?  I don't read that site.

**Comment by Funtime60** [comment]
Absolutely! I'm more than happy to help. I probably won't actually "read" all the books but I'll look through and check on images. I assume there are also logs on whether FFF thinks it succeeded or failed and I'll take a look or send those too.

**Comment by JimmXinu** [comment]
I've uploaded a test CLI version that uses direct download of images when `use_flaresolverr_proxy:directimages`.  

I also had to add a `user_agent` setting for cdn.scribblehub images to work.
```
[www.scribblehub.com]
user_agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
slow_down_sleep_time:1
use_flaresolverr_proxy:directimages
```

**Comment by Funtime60** [comment]
I apologize. I was too enthusiastic and forgot that I only know how to install it from the calibre plugin page. Do I clone the github or something else? thank you. And the line you added, I assume that would go in the personal.ini? Thank you.

**Comment by JimmXinu** [comment]
Sorry, I assumed from your comments about using `curl` that you use CLI, so I only posted the CLI test version.  

I've now put up a plugin test version also.  I post [test versions](https://github.com/JimmXinu/FanFicFare/#test-versions) in the same places all the time.

To see if images were successfully included, view the Calibre background job log after it's finished or edit the epub and search for `<img` tags.  Failures will be marked 'failed'.

**Comment by Funtime60** [comment]
That will be extremely useful since I also just realized that I have no idea of how to use the CLI version I just downloaded with pip. I will try that ASAP. Thank you so much.

**Comment by Funtime60** [comment]
First test run worked perfectly on the cover. Though the personal.ini editor in calibre complained that directimages is not a valid parameter. I will continue to test other stories, sites, and in book images.

**Comment by Funtime60** [comment]
It seems to be working perfectly on ScribbleHub and FanFiction.net as far I can tell. I'm going to install the test version on my main calibre server now. I'm going to assume that using Overwrite will "add" the images to existing stories that I downloaded before.

**Comment by JimmXinu** [comment]
> Though the personal.ini editor in calibre complained that directimages is not a valid parameter. I will continue to test other stories, sites, and in book images.

Yeah, I skipped the part that tells the color highlighter and editor about that value since it's plugin only and I thought I was making a CLI test version.  Just ignore the warning for now.

If this works for a wide array of stories, I'll look into making it more full featured, like using FFF's `BasicCache`.

Make sure, if you can, that you're trying different authors who may use different image hosts.

**Comment by JimmXinu** [comment]
I assume this works well enough to keep.
