### ISSUE TITLE
Colored text is not being retrieved

### ISSUE THREAD

**Issue by Arkbird1000** [JimmXinu/FanFicFare#101]
Specifically here: http://www.fimfiction.net/story/19198/background-pony.
I don't know of any other books that make use of colored text, so I am unsure if it is specific to FIMFiction, if it is just something that has never come up, or if I am simply missing something obvious. If there is any other information I can provide, please let me know.

**Comment by JimmXinu** [comment]
Not a bug, this is how it's intended to work.

In an effort to make the ebook output look more or less the same for all authors and sites, FanFicFare strips out styling by default.  Otherwise it can become unreadable on gray-scale ebook readers.

In your case I think putting this in your personal.ini will help:
```
[www.fimfiction.net]
keep_style_attr:true
```
I've added a [new FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-doesnt-the-color--font--special-formatting-from-the-story-appear-in-the-ebook-fanficfare-produces) to example why.

**Comment by Arkbird1000** [comment]
Yep, that would do it. Thank you! I am still familiarizing myself with Calibre and FanFicFare. Obviously, I have a little more learning to do.
