### ISSUE TITLE
Colored text (and hidden text)

### ISSUE THREAD

**Issue by arromdee** [JimmXinu/FanFicFare#1012]
Add support for colored text, at least on questionable questing/spacebattles/sufficientvelocity.

With This Ring (https://forum.questionablequesting.com/threads/with-this-ring-young-justice-si-thread-fourteen.8938/ ) heavily depends on colored text (and sometimes on hidden text too, which has to be handled somehow.  Maybe a weird font and color?).

Also, the title page is cut off and doesn't have its image.

**Comment by JimmXinu** [comment]
See FAQ: [Why doesn't the color / font / special formatting from the story appear in the eBook FanFicFare produces?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-doesnt-the-color--font--special-formatting-from-the-story-appear-in-the-ebook-fanficfare-produces)

FFF's titlepage includes the _description_ metadata entry.  Older Xenforo forum stories that don't have a specific thread description take their description from the first post, but it's limited by default to 500 characters.  With lots of HTML, that can end up being pretty short.  So that's functioning as designed.

As for the cover image, that story 'cover' image uses a `proxy.php` URL that is returning 404 not found to FFF but works in browser as long as it has a Referer.  I'm not currently able to get it to work despite already having a Referer and adding a User Agent string.  So I don't have a solution for the cover other than adding it manually.
