### ISSUE TITLE
Erotica Tags to Extra Tags

### ISSUE THREAD

**Issue by Alphadesk10** [JimmXinu/FanFicFare#1023]
I know it maybe a dumb request,

What I'm trying to do is to combine the Erotica tags in the LITEROTICA webpage ePubs to the Extra Tags and that too in the website own order rather then the alphabetic order.

All my stories tags only show 2 tags = (Erotic, category)

If i open the book, in the title age I can see the Erotica tags completely.

I have tried to create an custome collum with coma seperated text like, tags........ and on the FanFicFare configaration I have set the extra tags to this custom column. But it doesnt copulate the Erotica tags rather It just gives out Erotica.

When I tried t edit the default.ini file I fount that the extra tags was defaulted to Erotica for literotica, and the erotic tags are not synced with the extra tags.

If it's not a bother please help me with an cod ethat I can plly on the personal to just sombile the erotica tags to the tags or to the Extra tag so that I can update it to my custom column.

And if you need any detailed information please ask.

**Comment by JimmXinu** [comment]
I'll give you some guidance, but I'm closing this issue because it isn't a problem with the software.

I recommend the Mobile Read [FanFicFare plugin thread](https://www.mobileread.com/forums/showthread.php?t=259221) for questions like this about using the plugin.

As you found, Literotica's 'Story Tags' are collected in FanFicFare(FFF) in the `eroticatags` metadata entry.  This is a _site specific metadata entry_, meaning most sites don't have it and that's why it doesn't appear in the drop down lists in FFF plugin's Custom Columns config tab.  `extratags` is a _standard metadata entry_: all stories on all sites have it, even if some don't put anything in it.

There's more than one way to get what I think you want: Unsorted `eroticatags` in a custom column.

### Extra Tags
The first is to use `extratags` to populate the column, but include `eroticatags` in it, too.  You can do that, and keep the original order by setting 'Extra Tags' to your custom column in FFF plugin's Custom Columns config tab and these settings under `[literotica.com]` in `personal.ini`:
```
[literotica.com]
keep_in_order_extratags:true
keep_in_order_eroticatags:true
include_in_extratags:extratags,eroticatags
```

Or to not include the default extratags setting of 'Erotica':
```
[literotica.com]
keep_in_order_extratags:true
keep_in_order_eroticatags:true
include_in_extratags:eroticatags
```
**NOTE:** By default, both of the above will __also__ put `eroticatags` in Calibre's Tags column (which is always sorted).  The `include_subject_tags` setting controls what is set in Calibre's Tags column and can also be customized.  You could skip the custom column entirely if you are happy with that.

### Erotica Tags Directly
The second way is to set `eroticatags` directly into a custom column.  Because it's a site specific metadata entry, this is done in `personal.ini` with more settings under `[literotica.com]`.
```
[literotica.com]
keep_in_order_eroticatags:true
add_to_custom_columns_settings:
 eroticatags=>#yourcustomcolumn
```
Note the space before eroticatags--it's necessary.

The `add_to_` prefix is in case you already have `custom_columns_settings` under `[defaults]`.

### Important Note: Calibre Columns Types
It's important to be aware that Calibre Custom Columns have more than one type, in this case the important difference is:
- `Comma separated text, like tags, shown in the Tag browser` will always be sorted by Calibre
- `Text, column shown in the Tag browser` will not be sorted.
- `Long text, like comments, not shown in the Tag browser` will also not be sorted, but is presented and edited a little differently.
