### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by jherazob** [JimmXinu/FanFicFare#104]
Ubuntu 12.04 LTS, Python 2.7.3.
"pip install FanFicFare" returns this exception:
     IOError: [Errno 2] No such file or directory: '/home/username/build/FanFicFare/DESCRIPTION.rst'

The file exists on the repository and manually copying it makes it work, so clearly it's something directly related to the pip configuration.

**Comment by JimmXinu** [comment]
This works fine for me on my CentOS release 6.6, but I do see the issue occur on my Raspbian GNU/Linux 7.

Okay, it turns out that the DESCRIPTION.rst file is automatically included in the whl (pre-compiled) version, but not the source zip.  I've explicitly included it in MANIFEST.in and that fixed it for me.

Try again, although be aware that pip may have left a 'build' directory.  I had to delete that before pip would download the newer package to work correctly.

**Comment by jherazob** [comment]
Did "pip uninstall FanFicFare", deleted the "build" directory, did "pip install FanFicFare" again, worked. That should do it then, closing the ticket :)

**Comment by JimmXinu** [comment]
:thumbsup:

For the record, fix is in these commits:
e97f03a680e1d564437e644e622811acfd5feed4
668fca6f6ee6661604c71b6d34262d597ef03adb
