### ISSUE TITLE
Is it possible to make FFF ignore the 403 errors.

### ISSUE THREAD

**Issue by tchua0927** [JimmXinu/FanFicFare#1044]
Hi. Please close if not relevant or possible to address.

I saw a closed thread about the 403 error and understand that for some sites there is nothing to be done. This is related to the issue.

Before the last update, I could select all stories in my Calibre library and execute an update all. Even for sites like FFNET which would functionally ignore any errors / stories that would not update. 
Now, each time there is an error, FFF stops updating anything in the queue until user input is provided.
My current library is 500+ stories and quite a few are old stories that are no longer available on their sites and would thus produce an error. It is cumbersome to provide 100+ user inputs just to find the few stories that have updated today, especially since the library can take over an hour to update without user input.

Is it possible to restore the previous update behavior?

**Comment by JimmXinu** [comment]
Already fixed in f21f039b3a099d3356e3729bee2a0848092b7282.  You can get the [latest test version](https://github.com/JimmXinu/FanFicFare#test-versions) with that change.

Also, please see the FAQ: [Why shouldn't I just select my entire library and use FanFicFare plugin to check for updates?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates)

**Comment by tchua0927** [comment]
Thank you. I will attempt to head your FAQ advice.
