### ISSUE TITLE
fanfiction.portkey.org download issues

### ISSUE THREAD

**Issue by dendryte** [JimmXinu/FanFicFare#105]
When downloading http://fanfiction.portkey.org/story/8493, firefox detected the encoding of the html wrongly as western, and I had to manually set it to UTF-8. Maybe something in the html is causing it?

Downloading this url only saved the first chapter: http://fanfiction.portkey.org/story/456

**Comment by JimmXinu** [comment]
What Firefox detects encoding as is outside my area of concern.

If you mean FanFicFare, for portkey.org, it defaults to Windows-1252 then UTF8.  (There is an 'auto' setting that you could manually set in personal.ini, but it's not used by default because it's not terribly reliable.)  portkey.org doesn't appear to declare it's delivered encoding either way.

As for http://fanfiction.portkey.org/story/456, that's an unrelated issue.  portkey.org is an old site with a lot of questionable HTML.  I've made a change (dafbac5c9b0938901ce60e13f804dc046b3d276c) that appears to help with that.  New test version of plugin [posted here](http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025).
