### ISSUE TITLE
[Question] For the Browser Cache method: only check first and last chapter

### ISSUE THREAD

**Issue by Felina-Lain** [JimmXinu/FanFicFare#1054]
Hi

I recently tried to update some old fic because the author returned to them (never give up hope!) But found that because of cloudflare FFfare could no longer just download from ff.net
I followed the instructions and got the browser cache magic working, but on some fanfic it can be pretty long to open all the chapters one by one
I could have sworn at some point during my exploration of all the docs and pages, that I came across something that said
"Here's an option to put in the ini to only check first and last chapter if the fic already exist"

But then I couldn't find that option at all again, in any of the pages I had open?
So, does that option exist and if yes, how is it called exactly? So I know where to look.

Thanks in advance, have a nice day! (night, whenever you read this)

**Comment by JimmXinu** [comment]
That sounds like downloading all the chapters again rather than updating and just downloading new chapters.

That can happen because you didn't specify to update, but depending on how old you're talking about, it may be that the old chapters don't have the chapter URLs embedded in them.  Current FFF looks for those embedded chapter URLs and discards chapter files that don't have them, and has done for many years now.

There are ffnet only options for taking metadata from the last chapter(`meta_from_last_chapter`) and looking for a 'next' chapter after the reported chapters on the site(`check_next_chapter`).  But there aren't any options I remember for "only check first and last chapter if the fic already exist".

You can use a chapter range (`-b` and `-e`) to limit the download to the new chapter(s), but it would be on you to combine that with your existing ebook.  (And not overwrite your existing ebook.)

Regardless, this is a user question, not a code issue; so I'm closing it.
