### ISSUE TITLE
Update AO3 anthology not working when a series URL is used

### ISSUE THREAD

**Issue by jenniferlynparsons** [JimmXinu/FanFicFare#1056]
I've noticed that I can't update any of the anthologies I've added to Calibre via the "Make anthology epub from webpage" option. When I try to run the update option, I get a "story is not a valid URL" error. 

Is that intentional or a bug? 

Am I correct that if I use the update option it will only update a single story url, like if an incomplete story has new chapters, but not add new parts to a series?

**Comment by JimmXinu** [comment]
There's a separate Anthology Options > Update Anthology Epub action you need to use for anthologies rather than the basic update action.  It sounds like you're trying to use the basic book update.

Also, AO3 added pagination for series a few days ago.  I already have a code change for that in testing (704ea89d726501560976e51cfdd33d9a7a1e1b13) and a test version posted in the [usual place](https://github.com/JimmXinu/FanFicFare/#test-versions) for plugins.  (I confess I didn't remember to push the code change here until I saw this.)

**Comment by jenniferlynparsons** [comment]
@JimmXinu Just confirming that I tripled-checked and I have indeed been using the "Anthology Options > Update Anthology Epub" option you mentioned when trying to update and getting that error. I'll keep an eye up for whatever gets pushed up. 

Thanks for all the work you put into this!

**Comment by albyofdoom** [comment]
@jenniferlynparsons As a counterpoint, I also use this same feature on AO3 extensively, and I've been having no issues. I download with the series url (examples below) using the "Get Story URLs from Web Page" menu option, then do updates via the "Update Anthology Epub" menu option. It's been picking up new chapters and new stories in the series without issue.

Sounds like you're doing all the exact same things I am, so I'm wondering if it's either an AO3 work or site skin issue or if there is some other site setting that could be causing this. 

Below are a few of the series that I regularly update this way, if you want to test or compare to see if there is something different about them.
- https://archiveofourown.org/series/3583306 (did update 4/17/24 successfully with new chapters)
- https://archiveofourown.org/series/1891810 (did update 4/10/24 successfully with new stories)
- https://archiveofourown.org/series/3251574 (did update 4/1/24 successfully with new chapters)
- https://archiveofourown.org/series/1362046 (did update 3/23/24 successfully with new story)
- https://archiveofourown.org/series/3031950 (did update 3/7/24 successfully with new chapters)

Do you have an example series URLs I could test with to see if I experience the same issues with them?

**Comment by JimmXinu** [comment]
Possibly.  All of those series above (with more than 20 stories) appear paginated for me using AO3's Default site skin and the handful of others I tried randomly.

What site skin do you use?  

All I've ever done with AO3 site skin is change CSS and pagination goes beyond CSS.  I don't think work skins apply to series.

Paginated examples previously reported:
- https://archiveofourown.org/series/1683661
- https://archiveofourown.org/series/1034549
- https://archiveofourown.org/series/1533116

**Comment by albyofdoom** [comment]
I'm just using the default skin by AO3, and like I said, I've had no issues with series anthologies, with or without pagination, using the test versions of FFF as they come out. I'll see if Jennifer posts any examples, and test those, to see if I can help them narrow down where the issue might be. 

Just figured I'd jump in and try to assist in troubleshooting, since it seems like I'm using the feature nearly identically to the way they do and not seeing the same issues. :)

**Comment by JimmXinu** [comment]
You haven't downloaded the latest test version of FFF and are using that, are you?  Because it's fixed in the text version, I just haven't released a version since then.

**Comment by albyofdoom** [comment]
I am currently using version 4.33.4. 

I just want to clarify that I am **not** experiencing any issues. I installed the AO3 pagination test version a few days after you posted it. I generally update to the newest test version within a few days of them being posted. 

I was only attempting to assist the original poster in troubleshooting, but it seems my using the test version may be invalidating my results. My apologies :)

**Comment by JimmXinu** [comment]
Fixed last verion
