### ISSUE TITLE
Any way to improve tables on Kindle?

### ISSUE THREAD

**Issue by emrys90** [JimmXinu/FanFicFare#1057]
LitRPG on Royal Road often uses tables to show "System" notifications. Unfortunately, on Kindle that means those tables get cut off and are impossible to read without reducing font size to try and fit it all on screen. In the case the text is still cut off, the only option is going to the Royal Road website to read that chapter.

Is there anything that can be done to improve this? Often times this happens is for a table with only one column and one row, as its just used for formatting. Maybe in those cases the table could be stripped out and add different formatting that Kindle supports?

As an example, here's a chapter that has this issue:
https://www.royalroad.com/fiction/35398/monroe/chapter/1305495/chapter-three-hundred-and-ninety-eight-for-the

**Comment by JimmXinu** [comment]
I'm reluctant to try and solve such issues in FanFicFare.  In part because people will disagree about what the correct solution is.  

As you noticed, in that particular example the author is basically misusing tables.  They're being used to apply a background color to a single cell instead of for tabular data presentation.  

Those tables also have tag specific `style` attributes for width.  I assume you have `style` attributes being kept in your `personal.ini` settings, what happens if you don't?

Have you tried turning on Calibre Convert's > Look & feel > Layout > Linearize tables option?

**Comment by emrys90** [comment]
Hmm I tried turning on the linearize tables setting, I converted that book, and then sent to device. It still looks the same though with getting cut off screen. Did I do something wrong?
