### ISSUE TITLE
Literotica changes after site UI revamp

### ISSUE THREAD

**Issue by dakswiggin** [JimmXinu/FanFicFare#1058]
Presumable due to move of list of works from https://www.literotica.com/stories/memberpage.php?uid=author id&page=submissions to https://www.literotica.com/authors/author name/works/stories updating/creating anthologies is broken now
submissions link now points to author details after redirect rather then to stories page

**Comment by JimmXinu** [comment]
I'm not seeing that site change.  However, I also don't have an account on literotica; is it a member only change?

I'm going to need some real URL examples before I can do anything about it.

**Comment by dakswiggin** [comment]
link to author page from story was moved from https://www.literotica.com/stories/memberpage.php?uid=1400023&page=submissions to https://www.literotica.com/authors/bhuff/works/stories for example
seems this change was reverted as author page link now points back to https://www.literotica.com/stories/memberpage.php?uid=1400023&page=submissions

**Comment by JimmXinu** [comment]
That looks like site change testing.  I'm not going to make changes chasing a moving target, but I'll leave this issue open in case it stabilizes soon.

**Comment by dakswiggin** [comment]
Seems changes were deployed again couple of days ago and not rolled back since. New UI in place in anonymous mode as well

**Comment by dakswiggin** [comment]
Got it, thanks for tip. Changes indeed are deployed only for some regions or ip ranges as under vpn i've got old UI. Sorry inconvenience caused.

**Comment by JimmXinu** [comment]
np.  I don't read that site myself, so unless prompted I won't remember to look at this very often.  Thanks for confirming the region idea.

**Comment by Jemeni11** [comment]
> Got it, thanks for tip. Changes indeed are deployed only for some regions or ip ranges as under vpn i've got old UI. Sorry inconvenience caused.

Thanks for this. FF worked when I used a VPN.

**Comment by JimmXinu** [comment]
FYI, I'm told there's an option in the user settings to opt-out of the beta.  There's also one I see for non-users on story chapter pages.  That might help.

**Comment by natsuj** [comment]
> FYI, I'm told there's an option in the user settings to opt-out of the beta. There's also one I see for non-users on story chapter pages. That might help.

The option in the story chapter only change the chapter UI not the author's page UI nor the forced author's page redirection. The main problem that cause FFF to malfunction is the forced URL redirection from https://www.literotica.com/stories/memberpage.php?uid=author id&page=submissions to https://www.literotica.com/authors/author.

So VPN is the only option for now.

**Comment by JimmXinu** [comment]
Test versions in the usual places.

Changes for literotica aren't hugely tested.  Also, I fully expect further site changes.

**Comment by wtrees9** [comment]
Thanks for the update.

Another big change is that it shows only up to 25 parts of a series.  For example, here is a story called "Mary and Alvin" at https://www.literotica.com/authors/MelissaBaby/works/stories.  It has 37 parts but the page shows only 25 parts, and a `button` to "View Full 37 Parts Series".  

So to get the full list of the parts in those series, the button has to be clicked.

**Comment by JimmXinu** [comment]
Ugh.  That's a javascript interaction that creates the HTML for the +25 chapters from some embedded data.  

It's not obfuscated, so it should be possible to extract.  But I may not get to it today.

**Comment by JimmXinu** [comment]
Parsing that embedded info is a pain.  I think it may work better to get the chapters from the new "Story Series" page like:
https://www.literotica.com/series/se/80075773

Which does raise the question of whether that "Story Series" should be the canonical story URL for this site in FFF now.

**Comment by wtrees9** [comment]
I did search for another long series and here is one:
  https://www.literotica.com/authors/BlaQQuill/works/stories

Also found another author's page with `Show More` button at the bottom to load more stories (not just from the same series):
  https://www.literotica.com/authors/Naughtybecca/works/stories

As you mentioned before, it's not clear that the UI revamp is completed or not.  So until revamp is done, I think it would be helpful to have an option to download single story directly from the story link without looking up the author's page.  Then, those individual stories can be merged to first 25 stories if wanted.

**Comment by JimmXinu** [comment]
Thanks, that helps.  Especially knowing about 'Show More' for the author's list.  

That definitely puts me in favor of using the 'Story Series' page (`/series/se/99999`) both to collect story data and to be the canonical story URL.  Especially since I now see a link on each 'chapter'('story') page back to the 'Story Series' page.  

(I suspect we're going to lose the `averrating` metadata entry, however.  It's not included per 'chapter'('story') or in aggregate on the 'Story Series' page.)

That should also deal with the weird cases where the author somehow associated the same 'chapter'('story') with more than one 'Story Series'. [Example](https://www.literotica.com/authors/Zeff999/works/stories)

But it's also good you reminded me about single 'chapter' stories--they don't have a 'Story Series' page.  So they'll have to keep the `/s/story-title` style URLs.  We have prior precedent for allowing more than one style of canonical story URL.

### Structural Words
Unfortunately, literotica and FFF disagree about the definitions of 'chapter', 'story' and 'series'.   I'm not sure that this is documented anywhere else, so I'm going to ramble about it for a bit to help collect my thoughts.

#### FanFicFare
FFF generally downloads a 'story' of multiple 'chapters', each chapter being an individually downloaded webpage.  In FFF a 'series' is a name and URL associated with a story and making an anthology of multiple stories in a series is a separate (Plugin only) feature.

#### literotica 
literotica instead defines a 'story' which can (optionally) have multiple 'pages' that are different webpages.  Then a 'series' (or 'story series') is a collection of 'stories'.

When `adapter_literotica.py` was implemented in FFF, it was decided to map literotica 'series' and 'stories' to FFF 'stories' and 'chapters'.  literotica 'pages' aren't represented at all and are all fetched together.

The alternative would have been to map literotica 'series', 'stories', and 'pages' to FFF 'series', 'stories' and 'chapters' respectively--to match terminology, if nothing else.

It was ~10 years ago and I didn't write `adapter_literotica.py` myself, so I don't remember all the details, but here are some factors that probably contributed to the way it is:
1. While each 'lit-page' is a separate webpage, they don't have individual names like 'fff-chapters'.
1. Each literotica `story series` didn't have page of its own, pre-beta version, which made it significantly more difficult to use FFF's (Plugin only) anthology feature to collect the 'lit-stories' together.
1. I'm dead sure the large number of 'stories' titled _Whatever Ch. 7_ contributed to treating 'lit-stories' as 'fff-chapters'.

**Comment by JimmXinu** [comment]
Also related 6462c5c3663045900b592330a7dcc6513a0ba82e  Forgot to tag the issue.

**Comment by wtrees9** [comment]
WOW!  Thank you so much for your effort and the detailed comments.

Personally I like the `averrating`, and most of the series are less than 25 parts.  So will it be too complicated to use the new story series page only for the stories with more than 25 parts?

It seems that not all series follow a new `siteURLPattern`. For example, 
  https://www.literotica.com/series/se/a-hawke-and-his-princess
which raises
> /.../fanficfare/adapters/adapter_literotica.py", line 91, in _setURL
>    lang = m.group('lang')
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by JimmXinu** [comment]
I'm really not interested in trying to parse author page again.  It's a bit of a nightmare looking past the 'show more' buttons without a javascript engine.  

Ideally, the site will start showing ratings or average ratings on the /series/se page.  I'm pretty sure I've noticed at least one further site change today while I was working on it: `memberpage.php?...page=submissions` links now redirect to `/authors/.../works/stories`

Your second point about /series/se URLs should already be addressed in 6462c5c3663045900b592330a7dcc6513a0ba82e and in the posted test versions.

**Comment by wtrees9** [comment]
Understandable; it looks messy.

Thanks again for your effort.

**Comment by version365** [comment]
Hi.. I understand why you don't want to work the `averrating` because the ratings for all the stories in a series in difficult to parse; but what about single stories? The rating for single stories are on the story page to the right side. It should be easy to parse though.. is it not?
So, my request is to bring the rating back for the single stories at least.
Or is there already a metadata for that which I don't know the name of?

**Comment by JimmXinu** [comment]
### averrating
Since apparently `averrating` is worth nagging for, I looked into it again and found that there's a JSON data dump hidden inside a `<script>` tag on `/series/se` and `/s/chapter` URL pages.  And it happens to contain the average rating for that page (one-shot) or all 'chapters' (series).

So I've added code to parse it and calculate the overall average rating to put in `averrating` again.  

This is 'best effort' code and likely rather fragile.  If it fails, there's only a debug level notification.
### description
I've also changed the `description` collection to use the 'Series Introduction' if available, then the short desc in 'Series Info' if available.  

I've removed entirely the old code that filled `description` with the chapter list.

Test versions in the usual places.

**Comment by wtrees9** [comment]
Thanks for adding `averrating` again.

Now the `Summary` is empty for series; it seems that `div.bn_B` is empty.

**Comment by JimmXinu** [comment]
Examples?  It worked for the ones I looked at.

> Now the `Summary` is empty for series; it seems that `div.bn_B` is empty.

**Comment by MrKonan** [comment]
I just downloaded the new test version..  I've updated qhml1's "A Box of Rocks" story series in my library and I got an empty comments/summary. 

https://www.literotica.com/authors/qhml1/works/stories
https://www.literotica.com/series/se/493921623

**Comment by JimmXinu** [comment]
The author hasn't given that story a description or introduction.

In past, FFF filled literotica story descriptions with a numbered list of the chapter titles because there wasn't a story(series) summary/description.  

But now there are two available, which the site presents to the author as 'Short Description'(required) and 'Series Introduction'.

**Comment by wtrees9** [comment]
With the code  before `4436001`, which uses `chapterdesctag` to parse for multipart story, the above link from @MrKonan gives the following `Summary`;
```
<b>Summary:</b> <p>1. Rock and Roll is a tough business.</p>
<p>2. It's only rock and roll but I like it.</p>
<p>3. A novel, rock and roll fantasy.</p>
<p>4. Things develop beyond anything she could imagine.</p><br />
```

Thanks a lot :pray:

**Comment by JimmXinu** [comment]
Correct.  

And as I [said over on MR](https://www.mobileread.com/forums/showpost.php?p=4418914&postcount=9528):
> That was an ugly kludge implemented because the site didn't have a 'story' description before.
>
> No other supported site gets a ToC when there isn't a description, and the site now requires at least the 'Short Description' on all new 'Story Series'.

**Comment by version365** [comment]
Thanks a lot for bringing back averrating! Your continuous work is really commendable! 🫡

**Comment by JimmXinu** [comment]
I've reimplemented description from chapters' descs for 'story series' that don't have an intro or short desc only.

On reflection, I decided I let my dislike for this site get away from me a bit there.

**Comment by MrKonan** [comment]
Thanks for adding that feature back and fixing the plugin :)   I have a problem updating or adding chapter 12 of this series.  

https://www.literotica.com/series/se/208847

FFF skips the update and says in log/comment  "Already contains 11 chapters."

**Comment by MrKonan** [comment]
I've updated to the new test version. It didn't add chapter 12 to the 11 chapter series. I even deleted the whole series and re-add to library. Only picked up 11 chapters. Here's the debug log file.

thanks!

[logfile.txt](https://github.com/JimmXinu/FanFicFare/files/15151270/logfile.txt)

**Comment by JimmXinu** [comment]
As of writing, same issue with:
https://www.literotica.com/series/se/493907811

The site is apparently not showing all chapters when not logged in on some stories now.  Both hidden chapters are new(ish).  Presumably they unlock after a few days.  

I'm not dealing with login for this site right now.

**Comment by wtrees9** [comment]
Thanks a lot for putting back the `averrating` and the `descriptions`.

Just fyi, the `averrating` needs to be formatted, `%4.2f`, but that's just a very minor stuff and doesn't need to be addressed right away.  

Best
