### ISSUE TITLE
BeautifulSoup UserWarning

### ISSUE THREAD

**Issue by fitzmorrispr** [JimmXinu/FanFicFare#109]
CLI version outputs the following:
bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))

Since one of the packages required by fanficfare is html5lib, I figure this is some kind of oversight

**Comment by fitzmorrispr** [comment]
I know this is minor, more of a user experience thing than aything else, but it bugs me, so here it is.

**Comment by cryzed** [comment]
@JimmXinu this could probably be fixed by manually checking all instances where a BeautifulSoup instance is created and modifying it accordingly, right? There's [quite a few places](http://i.imgur.com/X0d3dBz.png) where it's not explicitly specified, but I'm not sure if simply adding the html5lib argument to each of those would break anything. In theory it shouldn't, as long as each of those places usually has the html5lib library on its import path, since then it would be automatically used and the behavior would stay unchanged.

**Comment by JimmXinu** [comment]
@fitzmorrispr -- What were you doing when you got that warning?  Because I'm not seeing it.

**Comment by fitzmorrispr** [comment]
@JimmXinu
Suppose i should have led with that. I get the warning when updating an epub generated from a story on FimFiction.net, but before any network traffic happens. It appears to be happening when the program extracts the original URL from within the epub. When updating epubs generated from Fanfiction.net it does not exhibit this behavior.

**Comment by JimmXinu** [comment]
Story URL?

**Comment by fitzmorrispr** [comment]
So far, any one i have tried. Pulled this one off the Top Ranked page for the first time just now: http://www.fimfiction.net/story/67362/
No warnings on initial download, same warning as above on update. I'm using 2.2.14, which pip says is latest.

**Comment by JimmXinu** [comment]
Addressed in b2238e10e7c966115161fa759fc445d2b2b4b67a 
Included in next release.

**Comment by fitzmorrispr** [comment]
Thanks!
