### ISSUE TITLE
[FimFiction] 403 Client Error for all FimFiction Scraps

### ISSUE THREAD

**Issue by boomcpg** [JimmXinu/FanFicFare#1100]
FimFiction has been having problems with spam bot accounts for some time now and I suspect that a site change to combat this has broken the FimFiction Scraper. As of today any attempt to scrap a book gives the following error.

`HTTP Error in FFF '403 Client Error: Forbidden for url: https://www.fimfiction.net/story/(Insert Story Number)/'(403)`

System Info
OS = Linux Mint 21.1
Calibre Version = Calibre 7.17
FanFicFare Version = 4.37.0

**Comment by JimmXinu** [comment]
Also reported [here](https://www.mobileread.com/forums/showthread.php?p=4450268&postcount=9881).

FimFiction, like ffnet and so many other sites on the web, is now using cloudflare.  Whether by accident or design, cloudflare's protection against bots also prevents FanFicFare from working.

Using [flaresolverr](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures#flaresolverr) seems to work in my limited testing, with the limitation of not getting images.

(I haven't tested with BrowserCache because I don't expect it to work. Response header says cache: max-age=0.)

Unless/until FimF relaxes their cloudflare settings, I don't know of anything else FFF could do.

**Comment by boomcpg** [comment]
Dang. That's sad to hear but at least flaresolverr has had promising success. I will test on my end as soon as I can to see how it fairs on my end. I unfortunately have no experience with Docker containers and will have to learn how to run one before I can report back.

**Comment by jcotton42** [comment]
> Unless/until FimF relaxes their cloudflare settings, I don't know of anything else FFF could do.

They have an API https://www.fimfiction.net/developers/api/v2/docs/resources#chapter.

**Comment by JimmXinu** [comment]
Last considered in #229.  

I see that the [BBCode issue](https://www.fimfiction.net/developers/api/v2/docs/resources#html-vs-bbcode) appears to have been likely been addressed, but OAuth2 is still a significant barrier.  Keep in mind that FFF is still maintaining compatibility back to Calibre v2.85.1 and python 2.

In past, other sites (notably AO3) have relaxed their cloudflare level after a time at a higher level due to specific attacks.  IMO, it's better to wait and see for the time being.

**Comment by boomcpg** [comment]
OK. Didn't take long to setup the docker container and scraps seem to be working up to a point for a large library. Scraping times are 3-4 times what they were previously and was fine until about 2+ hours into the scrape. After that point every scrape gives the following error. 

`Expecting value: line 1 column 1 (char 0)`

Rerunning the scrape on stories that ran successfully works like normal and trying to rerun on a failed scrap gives the same error. Here is a list of a few of the failed scrapes.

https://www.fimfiction.net/story/530334/
https://www.fimfiction.net/story/548592/
https://www.fimfiction.net/story/561961/

**Comment by boomcpg** [comment]
Can confirm that this error is persistant in FanFicFare Version 4.38.0

**Comment by kolbdog323** [comment]
Its still not working I hope you get it fixed soon.

**Comment by JimmXinu** [comment]
Problem decoding first character while there's blocking happening is pretty obvious.  But in the interests of thoroughness, I went back and tried the 3 stories you reported with that error.

I was able to download the first 2 using cloudscraper before being blocked on the third.  So they may have relaxed cloudflare a notch, but are still blocking 'excessive' traffic?  Maybe go with `slow_down_sleep_time:5` or even larger?

I used:
```
[www.fimfiction.net]
use_cloudscraper:true
slow_down_sleep_time:3
```

**Comment by JimmXinu** [comment]
FYI, I've looked at FimF's API docs and I don't see anyway FanFicFare could use it.  

Their [auth](https://www.fimfiction.net/developers/api/v2/docs/oauth) requires either a `redirect_uri` to return the necessary `token` ([Authorisation Code](https://www.fimfiction.net/developers/api/v2/docs/oauth#authorisation-code) or [Implicit](https://www.fimfiction.net/developers/api/v2/docs/oauth#implicit) methods) or a static `client_secret` ([Client Credentials](https://www.fimfiction.net/developers/api/v2/docs/oauth#client-credentials) method).  

FFF doesn't have a web server to host a `redirect_uri` on, and a `client_secret` is automatically out, since it would have to be in the code of an open source project.
> You must keep your client_secret safe. If you believe yours to be compromised you should regenerate it.

Since [Creating an Application](https://www.fimfiction.net/developers/api/v2/docs/applications) is apparently a manual process, I can only assume they would _not_ want each FFF user requesting their own application/client ID.

**Comment by boomcpg** [comment]
Ah. I was not aware that the sleep timer was configurable. Retrying thanks for that insight. Hopefully FimFiction drops the increased Cloudflare settings but so fat the increase in security hasn't solved their scam bot problems.

**Comment by FaceDeer** [comment]
Just chiming in with my own experience since I finally ended up here after finding a barrier I couldn't surmount. :)

I ran into the "Expecting value: line 1 column 1" error after just my second attempt to download a story from Fimfiction through FlareSolverr, and my slow_down_sleep_time was already set to 5 by default (I've always tried to tread gently, I'm in no hurry). Seems they're being quite vigorous. Though I just tried clicking around through a couple of pages more rapidly than that through my regular Firefox browser with no trouble, so maybe Cloudflare is being clever.

Here's hoping the spammers ease off and Fimfiction's able to relax a bit.

**Comment by kolbdog323** [comment]
> Just chiming in with my own experience since I finally ended up here after finding a barrier I couldn't surmount. :)
> 
> I ran into the "Expecting value: line 1 column 1" error after just my second attempt to download a story from Fimfiction through FlareSolverr, and my slow_down_sleep_time was already set to 5 by default (I've always tried to tread gently, I'm in no hurry). Seems they're being quite vigorous. Though I just tried clicking around through a couple of pages more rapidly than that through my regular Firefox browser with no trouble, so maybe Cloudflare is being clever.
> 
> Here's hoping the spammers ease off and Fimfiction's able to relax a bit.

Try setting `slow_down_sleep_time:7` That worked for me to fix error

**Comment by FaceDeer** [comment]
I cranked it all the way up to 11 and I'm still getting some working and some not working. I suspect that sleep time alone is not the only thing that's triggering problems here but I have no idea what else it might be.

I notice that on previous efforts on this FlareSolverr was reporting "no challenge detected" but now I'm getting "challenge solved". This doesn't seem to be related to the actual problem, though, I'm still getting some successes with that and some failures. But it does suggest that something's continuing to change in the background with how Cloudflare is handling connections.

**Comment by kolbdog323** [comment]
The error is back today even with the sleeptimer

**Comment by JimmXinu** [comment]
Yet more cloudflare we can't do anything about.
