### ISSUE TITLE
update plugin with logins is not working

### ISSUE THREAD

**Issue by MrKonan** [JimmXinu/FanFicFare#113]
FanFicFare v2.2.15

While using "update existing fanfiction books" (with Storiesonline) the login pop-up keeps showing up even with the login information saved in personal.ini and manually entering the login information to the pop-up is rejecting the login/password. Resulting in books not being updated.

**Comment by JimmXinu** [comment]
On 12/17/2015 10:53 AM, MrKonan wrote:
> While using "update existing fanfiction books" (with Storiesonline) the
> login pop-up keeps showing up even with the login information saved in
> personalini and manually entering the login information to the pop-up is
> rejecting the login/password Resulting in books not being updated

storiesonline.net has changed their site.  It will be fixed in the next 
version.

There's a test version of the plugin available here:

http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

If you are a web service user, I can make an updated test version of the 
web service also on request.

Jim

**Comment by JimmXinu** [comment]
Fixed in v2.2.15
