### ISSUE TITLE
Downloading at 1%

### ISSUE THREAD

**Issue by Verfassergeist** [JimmXinu/FanFicFare#114]
Trying to download a story from https://www.fanfiction.net but I never got the menu to add it to my library. Job details only displays:

Download FanFiction Book
FFF:INFO:calibre_plugins.fanficfare_plugin.jobs(42):FanFicFare v2.2.16
FFF:INFO:calibre_plugins.fanficfare_plugin.jobs(46):Adding jobs for URLs:
FFF:INFO:calibre_plugins.fanficfare_plugin.jobs(48):https://www.fanfiction.net/s/4240771/
 
While the Job Details window sits at 1%. I've let the plugin run for up to 7 min, but nothing happens as far as I can tell. 
![capture](https://cloud.githubusercontent.com/assets/16395511/11947471/e1ba8b12-a82c-11e5-8fb4-cf4203865176.PNG)
e

**Comment by JimmXinu** [comment]
Percentage done is by stories.  Since you're only downloading one story, it's going to stay at 1% until it's done and then jump to 100%.

To avoid being flagged by traffic throttling, there are ~8 sec sleeps imposed between page requests.  That story is 103 chapters long.  With default settings, the *minimum* time that story should take is ~14 minutes.  To check and make sure, I downloaded it myself and it took 15:29.
