### ISSUE TITLE
Fimfiction.net download appears to be broken.

### ISSUE THREAD

**Issue by Mihara** [JimmXinu/FanFicFare#118]
http://www.fimfiction.net/story/18832/so-long-and-thanks-for-all-the-ponies is a particular example. The only symptom is a "HTTP Error 404: Not Found" in the log.

This appears to only affect some stories, as there are others that update and download successfully.

**Comment by JimmXinu** [comment]
Already fixed in ca5077b9efcf28cfbd621ee5bae9d409634dea9a.  

New versions of FanFicFare are released ~ monthly.

There's a [test version of the plugin posted](http://www.mobileread.com/forums/showpost.php?p=3084025&postcount=2) already.  If you use CLI or web service, let me know and I'll make a test version there, too.
