### ISSUE TITLE
Issue with ascii strings

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#129]
FFF: ERROR: 2016-08-19 22:11:01,877: geturls.py(232): Failed to read email content: 'ascii' codec can't decode byte 0xe2 in position 256: ordinal not in range(128)

This is when calling geturls.get_urls_from_imap

I get it whenever the email has non-standard characters, such as in " Padmé"

Any other info that you want me to give relating to this I can.

**Comment by JimmXinu** [comment]
I assume you're using the Calibre plugin.  What OS are you using?  

What does the rest of the email look like?  What site is it from?

I'm able to use emails that I copy-paste "Padmé" into, so I suspect that the issue may be that the email you received doesn't have its encoding correctly flagged.

**Comment by MrTyton** [comment]
Using calibre pip-package, calling it from python interpreter (from fanficfare import geturls; urls = geturls.get_urls_from_imap("imap.gmail.com", "user", "pass", "INBOX"))

Email is from fanfiction.net. Here are example emails that the function all failed on with the same error, with only the byte name and the position differing.

http://imgur.com/a/GDT0M

I should have specified before, these emails do work within the calibre-plugin, it's only when I call it from python interpreter that they don't work. Every other email works from the interpreter.

Do you want more info? I can regenerate each of the error messages or forward the emails to you if you want.

**Comment by JimmXinu** [comment]
> Using calibre pip-package ...

Do you mean using fanficfare pip-package?  

I've only ever tested calling geturls.get_urls_from_imap() from inside the Calibre plugin before.  I assume calling it directly means you get your system default encoding instead of the environment Calibre sets up.

Trying it out on my Win10, I do get that error.  Changing the beginning of get_urls_from_text() (geturls.py:126) this like works for me:
```
def get_urls_from_text(data,configuration=None,normalize=False):
    urls = collections.OrderedDict()
    try:
        data = unicode(data)
    except UnicodeDecodeError:
        data=data.decode('utf8') ## for when called outside calibre.
...
```

If that works for you, I'll commit the change.

**Comment by MrTyton** [comment]
Yeah, that works. I figured it was something like that, but it is your code.

Reason that this was all relevant was because I wrote a script for cron to auto-update my calibre-library from email notifications. It works for most cases (doesn't handle chapter replacements well, I'm working on that), but it saves a lot of manual headache/time/clicks. I can share it if people want :|

Thanks again!

**Comment by JimmXinu** [comment]
Commit 664684b04f056f4bf2002419c3e8d5db6e4a741b
It'll be a few days before the next official release.

As far as I know, proper (safe) integration with Calibre requires updates to the library DB be done from the GUI thread to prevent the in-memory cache getting screwed up and causing data corruption.  But if you have a solution for that problem, I'd be interested to see it.

**Comment by MrTyton** [comment]
There's a [calibre cli](https://manual.calibre-ebook.com/generated/en/calibredb.html). By default it notifies the calibre GUI thread unless you specifically call it with "--dont-notify-gui", so it doesn't cause data corruption (or at least, it hasn't in my test cases; in fact while writing this comment I double checked, ran my script on something I had just removed from library while leaving calibre-gui open. Worked like a charm, updated it in the GUI, no corruption). Works whether or not you have calibre running itself. 

My script is a bit hacky: it's basically just using a python wrapper to call your plugin and calibredb, exporting the epub from the calibre db, updating, then replacing (and by replacing I mean delete and re-add, which tends to ever higher id numbers but... that's ok). So my thing isn't really a solution, it's just hacking together automation. There's likely a better way to do it from completely within python using your code (I sorta just like... call it and read the output to determine what to do) but I was lazy.

I'll modify it for general use and upload it tomorrow if you want to see it, I've had a long day. Sound good?

**Comment by JimmXinu** [comment]
You're right about calibre cli.  I was conflating the two related issues: 

- GUI plugins can't run cron/background threads in calibre (as opposed to BG jobs) because the main GUI thread is used as the DB mutex lock (thus the 'Proceed to update' dialog).  (WoG from Kovid.)

- Calibre CLI can run plugin code, but when the plugin is run that way it can't use its usual GUI code.  Both because it can't pop dialogs/interact with the user, and because it only knows how to update DB the GUI way.

I gave FFF a CLI interface similar to the FFF CLI when Calibre introduced plugin CLI with the idea of pursuing a more full-fledged implementation if it was popular.  As far as I can recall, you're the first person interested in using both Calibre and CLI since, so it never went anywhere.

**Comment by MrTyton** [comment]
This is the script that I wrote to handle it: https://github.com/MrTyton/AutomatedFanfic

It's got an additional bash wrapper that I use for cron safety, but that's not that important. Like I said, it's kinda hacky ^_^;

And oh, I see. It should be possible to have the FFF CLI use the calirbedb command from inside then no? That would take care of the DB GUI issue. I'd be up for helping if you want.
