### ISSUE TITLE
post_process_cmd

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#137]
I don't know if this a new thing but there used to be an output when downloading stories (that way you can see the progress as it was happening). But not in the newest version. 
Said output was the filepath created. In some cases it also printed other messages (like if the story was adult, etc)
Some warning messages in case of errors are still printed at least.

Is this a bug or a new feature?

in any case I figured out that a similar output can be created with a command like this:
`post_process_cmd: echo ${output_filename}`
in personal.ini

But I would rather have one like this
`post_process_cmd: echo Downloaded Story: "${title}" by "${author}"`
but ${author} is printed as [u'Author_Name'] instead of just Author_Name.
Am I doing something wrong or is this a bug because the line in my personal.ini above this is:
`output_filename: File_Path\${author} - ${title}-${siteabbrev}_${storyId}${formatext}`
And in that case ${author} is Author_Name

Note: Author_Name is the name of the author of the story.
Also File_Path is the path were my epubs are saved (and I don't want to post that online)

**Comment by JimmXinu** [comment]
I reduced the level of the normal output because it was inconsistent between sites.  You can use -d/--debug to get more output.

As for `post_process_cmd`, that's a problem with which way cli.py was getting the metadata.  It's fixed in 7221742  

If you don't want to wait for the next version, you can download [cli.py](https://raw.githubusercontent.com/JimmXinu/FanFicFare/fanficfare/cli.py).
