### ISSUE TITLE
sufficientvelocity.com has introduced a new "reader mode"

### ISSUE THREAD

**Issue by ATotalGit** [JimmXinu/FanFicFare#150]
Reader mode causes a thread to only display threadmarked entries, rather than the entire thread. It could massively reduce the amount of bandwidth required to pull a story from the site. Instead of getting 1 or 2 story posts plus 8 - 9 comments per page load, FanFicFare could get 10 story posts per page load.
If a story's normal url is something like:
https://forums.sufficientvelocity.com/threads/split-worm-fic.24539/

The reader mode url is:
https://forums.sufficientvelocity.com/threads/split-worm-fic.24539/reader

**Comment by JimmXinu** [comment]
That's an interesting feature, I'll definitely look into it.

However, it's not a trivial change to FFF due to various implementation reasons.  For one, the code for downloading from SB, SV and QQ is shared and only SV has this feature so far.  It may be a while before I get to it.

Thanks for pointing this out.

**Comment by JimmXinu** [comment]
I found some time.  I've added support for SV reader mode in 9abfaa793881cae908089a8d7a9e79618399617e.  It seems to work for me.
