### ISSUE TITLE
Storiesonline does not load following pages in a chapter

### ISSUE THREAD

**Issue by kapaka** [JimmXinu/FanFicFare#152]
storiesonline.com doesn't download the following pages in a chapter, just the first page of each chapter.
p.e.  http://storiesonline.net/s/14757/unending
Thank you for FFF :)

**Comment by JimmXinu** [comment]
Already fixed in 3ec7709c62d842455cd2bb561c24a7b1864baece.  

FanFicFare is released ~once a month.  Test versions with that and other fixes are frequently available early and are announced in the [plugin forum](http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025) and [mail list group](https://groups.google.com/group/fanfic-downloader).

**Comment by kapaka** [comment]
Sorry, I meant the webapp is having this issue, the plugin works fine now.

**Comment by JimmXinu** [comment]
Looks like I forgot to announce the test version URL for that one.

https://2-6-5-dot-fanficfare.appspot.com/
