### ISSUE TITLE
Bug with check_next_chapter

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#164]
Related to issue [159](https://github.com/JimmXinu/FanFicFare/issues/159)

In [adapter_fanfictionnet.py](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fanfictionnet.py), line [97](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fanfictionnet.py#L97) can return the url formatted as 

> http://www.fanfiction.net/s/number

and in line [130](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fanfictionnet.py#L130) it tries to split this by the 5th instance. This can't happen, so it throws an exception, which is caught in line [143](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fanfictionnet.py#L143)

The variable set in line 130 is also never used, so it's sort of doing this for no reason at all. I think that it should just be deleted.

(Also unrelated, for some reason it's been randomly hanging since I updated my linux kernels yesterday. Trying to figure out why this is happening.)

**Comment by JimmXinu** [comment]
That line is predicated on the user entering the story URL the way ffnet presents them (and the say FFF stores them): 

> https://www.fanfiction.net/s/number/chapter/ 

That explains why I didn't see it.  But you are correct that line doesn't do anything and can cause problems when the user enters an abbreviated story URL, which FFF does permit.  

Thanks for figuring that out.  Fixed in: 7a175ba
