### ISSUE TITLE
Author changes name -> metadata.opf is not created

### ISSUE THREAD

**Issue by AndyScull** [JimmXinu/FanFicFare#167]
It happens when author (specifically, on fantiction.net) changes his alias/name.
When I load url links from email notifications into FFF, it creates a new entry for the book and new file/folder in calibre library. The thing I noticed it that there's no metadata.opf in this folder, only epub.
New entry seems to be added correctly to metadata.db and I can manually copy my third-party bookmarks file from previous book folder to current so no bid deal as long as old folder isn't deleted along with this bookmarks file.
Honestly, I don't know how I'd deal with this situation - scanning whole library on each URL import looks kind of bad (I personally have ~3200 entries). Therefore, more like a question - would absense of metadata.opf break anything in calibre? Or maybe there's something missing in plugin since adding new books does correctly create metadata.opf file

**Comment by JimmXinu** [comment]
The existence or absence of a `metadata.opf` file is outside the scope of FanFicFare.

That said, I also see that there isn't a `metadata.opf` file in the directory for a new download.  My understanding is that the `metadata.opf` file is just a backup for what's in the library DB now.  Unless you see some specific problem, I wouldn't worry about it.

As for why you get a new book on author change instead of an update, I'm not sure.  The _If Story Already Exists_ setting will cause that if set to _Add New Book_, but if you're using one of the Update or Overwrite options, it should be matching by story URL.  (Of course, that assumes that you haven't changed or removed the story URL from the Calibre Identifiers column.)

You can change the default value for _If Story Already Exists_ in the Basic tab of the FFF Config:

![capture](https://cloud.githubusercontent.com/assets/11446969/24323301/940a3708-1141-11e7-9b2b-64fef8956b54.png)

Does any of that help?

**Comment by AndyScull** [comment]
Yeah I have that option enabled.
I think this was some kind of glitch, I found all my old email notifications from fanfiction.net and tried to reproduce the situation - deleted newly created duplicate book in calibre and tried adding it in various ways ( copy/paste link, import from email, import from email as attachment). Well, I couldn't. On all tries FFF correctly saw that I already have the book in library and updated exsting one )
