### ISSUE TITLE
Out of spec epub output (minor)

### ISSUE THREAD

**Issue by fitzmorrispr** [JimmXinu/FanFicFare#182]
I ran across a site-specific ePub generator someone wrote in Javascript, of all things, which the author was quite proud of. The author claimed that what set it apart from FFF was, among other things, spec compliant output.

So I ran [epubcheck](/idpf/epubcheck) against my FFF generated epubs, and found that it was indeed out of spec, in several ways. 

First, and probably easiest to fix, is that when including images, FFF does not necessarily (never in my testing) include an alt attribute in the img element. I presume that it would pass through any alt attribute that was present in the original html, but, [according to the spec](http://www.idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section2.3.4) the attribute is required. I did some testing, and epubcheck is satisfied with `alt=""`

Second, FFF is messing up file extensions and mime types for images, or at least for PNG images. It saves them as .jpg and (in the OPF file) image/jpeg. This is with image processing turned off, and regardless of what the default image file type is set to (which I believe wouldn't matter, as that option is for when the processing is turned on, right?)

Thirdly, FFF is passing through a few disallowed element types, including but not necessarily limited to `<center>` and `<u>`. I know that fimfiction, at least, still uses these tags, despite them being deprecated since html 4.01. My only fanfiction.net sourced story validates perfectly, so either fanfiction.net uses different elements to achieve the same styling (one would hope), or that story contains no examples of said styling.

**Comment by fitzmorrispr** [comment]
The "other things" were:
* pretty XML (who cares, really? It's not meant to be viewed. Useful for bug reports, maybe)
* epub 3 support (this actually would be nice, since 2.0.1 was superseded by 3.x nearly six years ago now)

**Comment by JimmXinu** [comment]
You are correct (I think) that if the site <img> tags has an alt attribute it will be preserved.  I don't see a lot of point to it, but I could add an empty alt when none exists.

(A more significant standard violation, I would think, is FFF's blatant abuse of the img longdesc attribute to store the original image URL.  Which I don't intend to change.)

Can you provide example story URLs for the other issues (PNG type & center/u tags) you mention?  Because as far as I know, there's code to deal with both of those already in place.  

Pretty XML--I have vague recollections that something bad happened when I tried that.  The extra whitespace being included in TOC entries on certain ebook devices; something like that.

Epub 3 support--So far as I remember, it's a lot of extra complexity for no gain plus issues with backward compatibility to older devices.

**Comment by fitzmorrispr** [comment]
https://www.fimfiction.net/story/318771/earth-without-us
This one doesn't have the u tag, but does have center, and does have the png/jpg issue.

https://www.fimfiction.net/story/290208/utaan exhibits u tag, is also really long.

As to epub3, couldn't it be implemented as a separate output adapter? I suppose it is a lot of work, and presumably we won't start seeing software that lacks epub2 support for awhile yet.

**Comment by JimmXinu** [comment]
- First, the png issue: [that story](https://www.fimfiction.net/story/318771/earth-without-us) uses image URLs like this one: `https://camo.derpicdn.net/80c22fde0844c25f71d8bedc288e9628f2004585?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F155575820457345024%2F274810660481925120%2Flpoe.png`

  The thing to notice is that the 'path' part of the URL is `/80c22fde0844c25f71d8bedc288e9628f2004585`.  Which _doesn't_ end in a known image file extension.  (The FFF code specifically looks for the path part because some sites include other params.) 

  However, it is a reasonable thing to check the overall end of the URL for an extension if there isn't one on the path.  So I'll add code for that: 622f4d7dd14e2d0e52bf4bdd0ee569db155fd643

  (FYI, the cover will still be a PNG named .jpg because there's no extension at all on FimF cover URLs.  In theory, I could get the content-type from the HTTP response headers; but in practice I'm not going to unless it's demonstrated to cause real problems.  Also, processing the images will convert them to jpg.)

- Regarding `<center>` and `<u>` tags, it appears that the code used to replace those become at least partially ineffective somewhere along the way.  I have a fix for it: e6ca5da2c9939c09c0e5465cf5f79728f185b116

- Regarding epub3; yes, it could be a new output writer.  And if someone writes one, I'll likely accept it.  But I don't see enough (or any) benefit to it right now to do it myself.  Quite the opposite--I'd have to maintain epub2 _and_ 3 for the foreseeable future.

New test versions posted.

**Comment by fitzmorrispr** [comment]
Thanks!
(damn, that was fast)
