### ISSUE TITLE
Requesting support for https://fiction.live/

### ISSUE THREAD

**Issue by darnessfalls** [JimmXinu/FanFicFare#201]

**Comment by JimmXinu** [comment]
fiction.live is a site for 'quest' type stories with lots of reader votes and tons of images.
It is specifically designed to be real-time interactive including chat between author and readers and have content added real-time.

Rather than page scraping, supporting this site would require figuring out their web apis and using those.  

I don't say it can't be done, but I'm not personally interested in doing it.

**Comment by HazelSh** [comment]
I'm writing a fanficfare adapter for it, and did some digging around with my browser's devtools to try and figure the site out and see if there's a sane way to get story body text out of it. 
There is, kinda:
You can get the story id from the end of the story url, then request:
https://fiction.live/api/node/STORY_ID
which returns as JSON a bunch of the needed story metadata like author name, title, content description tags, etc, as well as a chapter list with chapter names and IDs. 
after that, per-chapter requesting:
https://fiction.live/api/anonkun/chapters/STORY_ID/0/CHAPTER_ID
returns the chapter's content-blobs, some of which are 'chapter' text updates, others are 'choice' with the votes, and I suspect there'll be others for audio, achievements, etc. 
then you can pull the content from the content-blobs, concatenate, and return fairly sane HTML story body.

that's the plan, at least.

this is *totally* ignoring the chat, the boards, and all the live stuff. not sure how ok with that the site author would be, turning the stories into ePUBs for offline reading is kinda counter to the whole purpose of the site.

if it goes well, I'll have something that works for me offline in a few weeks and a pull request not too long after. (if it goes poorly, I'll disappear and never be heard from again)

**Comment by DragoLord19D** [comment]
> I'm writing a fanficfare adapter for it, and did some digging around with my browser's devtools to try and figure the site out and see if there's a sane way to get story body text out of it.
> There is, kinda:
> You can get the story id from the end of the story url, then request:
> https://fiction.live/api/node/STORY_ID
> which returns as JSON a bunch of the needed story metadata like author name, title, content description tags, etc, as well as a chapter list with chapter names and IDs.
> after that, per-chapter requesting:
> https://fiction.live/api/anonkun/chapters/STORY_ID/0/CHAPTER_ID
> returns the chapter's content-blobs, some of which are 'chapter' text updates, others are 'choice' with the votes, and I suspect there'll be others for audio, achievements, etc.
> then you can pull the content from the content-blobs, concatenate, and return fairly sane HTML story body.
> 
> that's the plan, at least.
> 
> this is _totally_ ignoring the chat, the boards, and all the live stuff. not sure how ok with that the site author would be, turning the stories into ePUBs for offline reading is kinda counter to the whole purpose of the site.
> 
> if it goes well, I'll have something that works for me offline in a few weeks and a pull request not too long after. (if it goes poorly, I'll disappear and never be heard from again)

Hey, if it works let me know because there’s a few of the stories there that I wouldn’t mind having!

**Comment by HazelSh** [comment]
so my timeframes were hopelessly optimistic due to uni kicking my butt. 

but it now exists and fetches metadata correctly from the command line. 
I honestly believe that fetching actual story content shouldn't be too much harder. although I may need to spend some time formatting votes, making sure that inline images are included, etc. 

merge request will turn up at some point when it's working.

**Comment by HazelSh** [comment]
yeah, so this api reversing thing is fun. there aren't any chapter IDs. or there are, but as far as I can tell they don't do much. Instead, chapters have timestamps, which control the chunk-range fetched. As a story is written live, the site will just just add chunks to the end with  timestamps, then 'bookmarks' for chapters are added after the fact.

this isn't really a good match for how fanficfare expects things. in particular, I expect stories will update their chapter urls / chapter list a *lot*.

also sometimes chapters are just one chunk, not a range. when I solve that, and also write code to format choices as html I'll have ~200 lines of python that when plugged into the rest of fanficfare can turn fiction.live story urls into epubs. 

 this has somehow been way more work than I expected, possibly because it's the first time I've used python in a project, reversed an api, or done anything with a modern webapp. ...or because I took on uni at the same time. 

ETA, I dunno, first half of 2020 some time.

**Comment by HazelSh** [comment]
It works and works good. All the metadata fanficfare expects, story body text, properly formatted votes and multivotes, crossed-out vote writeins, readerposts and readerposts with dice rolls, option for spoilertags, images and coverimages and option for *not* nsfw covers, appendices, option to show the chunk timestamps, etc. 

I really don't understand the fanficfare/calibre Configureable infrastructure and how it interacts with story metadata. What to do as an adapter with custom metadata is unclear. I have it working at the command line, but not from Calibre. I need to go through defaults.ini more. I have a feeling that there's already options for handling, for example, nsfw covers. Also should figure out what to do with plugin-defaults.ini

 Should be just tidying and metadata/config stuff from here out, plus a rebase onto the most recent version. Wish me luck.

**Comment by HazelSh** [comment]
ahaha I decided that actually achievements were doable in a book after all. But that's it for major features, I swear. 

Got three more weeks of covid-19 lockdown, minimum. Needs more testing and some code tidying, then I'm gonna try and ship it.
