### ISSUE TITLE
Allow custom icons

### ISSUE THREAD

**Issue by 8bitgentleman** [JimmXinu/FanFicFare#205]
The current icon for FanFicFare looks strange when the calibre system icons are changed. I've put together an alternate icon that matches my calibre setup but changing the plugin icon is complicated. An easier way to do this would be much appreciated :)
<img width="759" alt="screen shot 2017-07-16 at 11 54 09 am" src="https://user-images.githubusercontent.com/4028391/28249106-a6726da4-6a1d-11e7-80b6-675024393972.png">

This is my custom icon 
![artboard 1](https://user-images.githubusercontent.com/4028391/28249177-e5863af6-6a1e-11e7-8ad0-b6895c1dcb69.png)

**Comment by JimmXinu** [comment]
Do you end up with the same issue with all your plugins?  I can think of a few ways to allow custom icons that I think would work, but I wonder if there's a general solution that could be made to work with more than just one plugin...

I'll think about it, but it may be a while, I have a lot going on this summer.

**Comment by 8bitgentleman** [comment]
No worries and no rush. Yours is the only plugin I actively use so I haven't had an issue with other icons. If there was a feature built into calibre to change the icons of any plugin that'd be ideal but I don't think such a feature exists

**Comment by JimmXinu** [comment]
Okay, this is actually a bit amusing.  Turns out, there's already code in the plugin to do this.  

What you do is:
1. Go into Calibre's config directory (Preferences -> Misc -> Open calibre's config dir, typically something like `C:\Users\user_name\AppData\Roaming\calibre` on windows).  
1. From there, go down into `resources\images`.
1. Create a directory `FanFicFare`
1. Copy your icon image into the `FanFicFare` dir as `icon.png`
1. Restart Calibre.

I learned to make Calibre plugins by (ahem) _borrowing_ code from kiwidude's existing plugins.  I believe many if not most of the other plugins available did something similar.  Which means that the same approach will work for all of my plugins and, I suspect, most of the others as well.

Further, it looks like Calibre's theme creation process will include plugin dirs and images, so themes could even include icons for plugins directly.
