### ISSUE TITLE
ArchiveOfOurOwn Bug?

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#208]
In Archive of our own I was trying to download the following:
https://archiveofourown.org/works/10093553

But due to (probably) the author's FuckUp there is no chapter 23.
On the index in goes chapter 22 => chapter 24.

As a result FanficFare does not download it.

In this case the story is problematic so it's fine (since the story is also on FFnet it might be for the best actually)
But it might be an issue that happens in other stories

**Comment by JimmXinu** [comment]
You can use chapter ranges to get partial downloads before and after the missing chapter, or you can use `use_view_full_work:false` to download the individual chapters that do exist.  It's the mismatch between chapter number in the full_work page and chapter list that's causing the issue.

Put it in your personal.ini as:
```
[https://archiveofourown.org/works/10093553]
use_view_full_work:false
```

I'm going to leave this issue open for the moment.  I want to look at see if that's a rarity or if that's just what happens if an author deletes a middle chapter.

**Comment by JimmXinu** [comment]
I do not believe this is likely to be a common problem.  I believe AO3 will renumber later chapters when a middle chapter is deleted by the author--it did for me.

The previous comment explains how to work around the issue for this particular story.
