### ISSUE TITLE
please add support for novelplanet.com

### ISSUE THREAD

**Issue by blacksheep19** [JimmXinu/FanFicFare#221]
novelplanet.com hosts most of the popular asian webnovels, so it would be a great help if we could download it from this site and read it later...
                                                              thanks for your hard work!!

**Comment by JimmXinu** [comment]
Closing this one due to site apparently include copyrighted material.

(These are some notes I made a while ago for this issue but didn't publish at the time.)  

Wuxia works, Translator is an included metadata.

Notes: 
- Other Name, Author, etc are often lists
- Chapter names always prepend story title?
- Adult stories don't require login?
- Stories can exist and be shown with no chapters posted
- Hundreds and thousands of chapters are common.
- Date Released is only year?
- Date Released/Translator at least can be 'Unknown'
- Chapters can be PDF files.  Some are named .pdf in chapter list, but others have no indicator in the chapter list.

Are PDF chapters a deal-breaker?  Otherwise, pretty straight-forward.  

**Also looks like it may include copyrighted material:  I see _All You Need Is Kill_ (the source for Live, Die, Repeat).  That _is_ a problem for us.**

Don't see any fanfiction...
