### ISSUE TITLE
Please consider adding support for http://volarenovels.com

### ISSUE THREAD

**Issue by ElminsterAU** [JimmXinu/FanFicFare#223]

**Comment by cryzed** [comment]
Well, I managed to create an adapter that seemingly works using [Faretricks](https://github.com/cryzed/Faretricks), [here](https://github.com/cryzed/Faretricks/blob/master/examples/adapter_volarenovelscom.py). Of course almost all of the important metadata is missing (scraping these from a blogging-platform with inconsistent formatting is senseless anyways).

I'll be honest: this works, but I don't particularly feel like finishing up the details -- maybe someone else will find some time?

**Comment by JimmXinu** [comment]
FYI, these 'add support for X novel site' issues are all sitting here because I don't want to deal with adding and supporting them.  So don't look at me.  ;-)

**Comment by cryzed** [comment]
Right, the same goes for me -- that's why I had hoped to come up with something like Faretricks that automates the process of creating these "throw-away" adapters, however I hadn't considered the cost of maintenance.

A more ideal solution regarding this might be to simply allow people to create their own (unsupported) adapters using whatever method, and then move them to a special folder where FanFicFare picks those up and loads them at runtime: that way their code wouldn't create a maintenance burden and people who desperately want FFF to work with a site that isn't supported for various reasons could help themselves without having to package a different version of the plugin.

**Comment by JimmXinu** [comment]
That's been suggested before, but past experience shows there are more people who desperately want FFF to work with a site than are willing or able to write the code for it.  I worry very much about the security implications of non-technical users dropping buggy or even malicious code into that directory from nefarious sources.

**Comment by cryzed** [comment]
Well regarding your first point, _ideally_ Faretricks wouldn't require users to write any code, just use the command-line "wizard" to create them semi-automatically.

Regarding the other point: if someone is (strangely) motivated enough to write malicious adapters for FFF and actively distribute them, they are also probably motivated enough to write a Python script or instruct a user to modify the plugin zip-files in the Calibre configuration directory. I mean, I get your worries, I'm just unsure if they represent a realistic threat model.

**Comment by dteviot** [comment]
@JimmXinu, @cryzed 
Apologies for the diversion and humble brag.
I'm the author of the Chrome and Firefox plug-in https://github.com/dteviot/WebToEpub that has similar function as FanFicFare.
After about 2 years, I've received almost no assistance or contributions and am seriously considering abandoning it and contributing to FanFicFare.
Anyway, getting to the point.  I ran into similar problem:  How to avoid having to do the "can you support site X". My solution was to provide a a very simple to customize parser.  It was very crude, but the idea was user can specify a host name and then specify how to find the content element for pages under that hostname, .  i.e Node of type "body", "div", with classname or id of XXXX.
I've learned a bit more since then, and would suggest that instead of using drop down lists for that, user could specify the element using a CCS selector.  Enhancement would be to allow user to provide additional selectors for other components.  e.g. Title element of page, next page URL, etc.

**Comment by cryzed** [comment]
@dteviot I have to admit that I had never heard about WebToEpub before, but this looks really cool! One huge advantage you have over FFF currently is that you have access to a real, underlying browser with full JavaScript support, which makes finding selectors and creating these custom parsers easy; FFF however often has to do quite a bit more reversing and mangling with the page's source, because it might be heavily modified at runtime by its JavaScript parts.

I'm of course sorry to hear that you couldn't find many participants for your project, however it _is_ quite a niche if you think about it for a moment :\^).

I can only speak absolutely for myself, but I would definitely be happy to have you on-board with FFF if you are comfortable with Python and working on someone else's code; and I suspect that Jimm's thoughts would be similar to mine.

The way you describe WebToEpub currently works is actually more or less exactly the approach I have taken with [Faretricks](https://github.com/cryzed/Faretricks/blob/master/faretricks/cli.py#L30), I first attempt to semi-automatically determine the correct (and best) selectors for the central elements (TOC, content, links) and fall back to allowing the tool's user to specifying custom bs4-compatible CSS selectors. After having done all that, the gathered data is used to render a rough adapter template which can be inserted into FFF's adapters package and quickly finished up manually.

However, when you compare this approach to your WebToEpub, it's clear which seems more user-friendly and robust. I'm unsure how to best integrate this kind of functionality into FFF in a way that it makes sense.

**Comment by JimmXinu** [comment]
I'm not opposed to having a generic configurable adapter.  I'm definitely not opposed to having more developer contribution. :-) But there are a couple hurdles to get over first.

The first is proving that it's real-world useful with FFF.  For that, I'd like to see working configurations for either some of the requested sites, some existing supported sites, or both.  If it can't be configured to support say 3-4 known sites, I have to question how many other sites it would be useful for.  Also keep in mind that because FFF runs as a Google web service, python pip CLI _and_ a Calibre plugin, including non-standard libraries can be problematic--we already have to bundle several libraries in with FFF.

The second is that the existing FFF architecture is pretty firmly site==adapter==adapter source file.  We have more than one site using the same code in places, but we generally do it by class inheritance.  For proof-of-concept and initial testing, that's fine: add a new `base_whatever_adapter.py` file, add `adapter_sitename.py` files for each configured site, add the parser control configurations to `defaults.ini`.  If a generic/configable adapter proves to be workable, and sufficiently easy for users to do, I'll need to then extend the architecture to allow sites to be added without `adapter_sitename.py` files.

If all that sounds reasonable, I suggest that we open a new issue for futher discussion.

**Comment by dteviot** [comment]
@eFrysTon

While waiting for FFF to implement support for volarenovels.com you could use this Chrome/Firefox plugin.
https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm?hl=en
Full Disclosure, I'm the author of it, and I haven't tested that it fully works for the Volarenovels.

**Comment by Rikkitp** [comment]
As an option you may use lightnovelgate.com, which contain many novels from other sites

**Comment by JimmXinu** [comment]
Closing this one due to site apparently containing copyrighted material.

(These are some notes I made a while ago for this issue but didn't publish at the time.)

"Chinese Romance and Fantasy"

https://volarenovels.com/abt/recruitment/

Claims to 
> ...have official licensing agreements with Zongheng, 17K, iReader, Xiang5, independent authors, and are in talks with traditional publishers. What this means is, not only do you have the freedom to select from their libraries, your translations are also 100% legitimate with no copyright concerns!"

> "Residual income is strong as we pay based on views, which means that a chapter you translated a year ago would continue to earn you money a year later. Add in two or three finished novels, and that's a considerable sum every month!"

> "The company oversees the process of turning completed translations into ebooks. Which, when released, will also provide you with remuneration for your work, this includes any other adaptions of your translations."

Not fanfiction, claims to be legit, paid translation service.
Which raises the question, are some of the already-supported sites the same?
