### ISSUE TITLE
Story Metadata differences between story URL and --download-list option

### ISSUE THREAD

**Issue by theit8514** [JimmXinu/FanFicFare#240]
I have a process that calls FFF with the --download-list option (mostly so I can send series links and download entire series). I've recently been noticing that most of the stories downloaded via the CLI appear to not contain all the information available on the story page. Using the single story URL option (without passing --download-list) has all the metadata from AO3 but if the same URL is passed via --download-list, the metadata from AO3 is missing.

Log output from both processes including metadata:
https://gist.github.com/theit8514/760d5c859b2550cacfdee6d0be8f3693

**Comment by JimmXinu** [comment]
I'm glad you posted the gist with the full command used, because this is a problem that _only_ appears when running FFF from the _calibre_ command-line with list download.  It doesn't happen using regular CLI, and it doesn't appear with individual download.

It turned out to be something I didn't think about enough: because I passed the calibre `defaults.ini` and `personal.ini` text in as StringIO objects (fake file objects), they were 'empty' after being read once.

Rather than rewind the passed StringIO objects, I thought it more intuitive to pass the INIs as strings and create StringIOs when needed.  a19331e3114aa2d36dc58a547b5ae3412a8f43f6

**Comment by cryzed** [comment]
Nice catch!
