### ISSUE TITLE
Metadata Update / Adult Status

### ISSUE THREAD

**Issue by LifeShouldBeAMusical** [JimmXinu/FanFicFare#252]
When selecting just the "update metadata" download option, FanFicFare will not ask you to confirm adult status, but if a story requires confirmation of adult status, it will not download the metadata.  The log just outputs

Bad
[title]
[author]
Story requires confirmation of adult status: (story url)
story url

Would it be possible for FanFicFare to ask for confirmation of adult status, as it does when actually downloading books/chapters?

**Comment by JimmXinu** [comment]
Are you seeing this with the calibre plugin, python CLI or web service version?

**Comment by JimmXinu** [comment]
So this only happens if it's a story that requires adult (or user/pass) _and_ already exists in your library _and_ you're doing 'Update Calibre Metadata from Web Site' _and_ you don't have `is_adult` and/or user/pass set in your personal.ini for that site.  I can see why I never noticed it. :-)

Fixed in c492b73.
