### ISSUE TITLE
Download Speed

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#262]
So I don't know if this qualifies as an issue or if it is just a question that has been answered already, but I figured I should mention it.

So I am downloading stories and I am noticing that Fanfiction.net stories take much longer
As an experiment I downloaded these:

> https://www.fanfiction.net/s/12731081/1/Skittering-thief
> https://archiveofourown.org/works/12772611

These are basically the same story,same word count and chapter count.
The author just post it on both FFnet and AO3.

I downloaded both on the calibre plugin and FFnet took 8 minutes and 47 seconds (that is 527 seconds) while the AO3 version took just 37 seconds.
So the AO3 version took 14.24 times longer.
That is a massive difference.

Is there an issue with accessing FFnet?
Is it just a slower site?
Does it have a force you to wait between page requests?

**Comment by JimmXinu** [comment]
From defaults.ini:
```
## AO3 offers a page to download the entire work at once.  This can
## save a lot of network traffic if there are many chapters.
## True by built-in default.
#use_view_full_work:true
```
AO3 downloads by default download the entire story in one network request.  ffnet does not offer a full work page and must be fetched one chapter at a time.

If you are updating to add a single chapter to an existing epub, ffnet download might be quicker because the `use_view_full_work` setting requires the AO3 server to collect all the chapters even if they all come in one request.  But it might not--as I recall, ffnet downloads need more requests to collect all the metadata.
