### ISSUE TITLE
Bad Request?

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#267]
Attempts to download https://forums.spacebattles.com/threads/it’s-been-a-long-road-getting-from-there-to-here-a-star-trek-x-com-crossover.379862/ gives me a 400 error code but other spacebattle stories download fine except this one...
![05fe821b-d75d-4757-9fd9-d0d36f096e45](https://user-images.githubusercontent.com/36297332/36024073-3014e440-0d54-11e8-9154-4680d57e2d56.jpeg)

**Comment by JimmXinu** [comment]
I've just successfully downloaded that story using both CLI and the web service.  So I don't think there's anything wrong with the FFF software.

Unfortunately, the web service isn't 100% reliable due to a number of factors, see [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-has-the-web-service-version-of-fanficfare-stopped-working).
