### ISSUE TITLE
Improve stdout with --download-list and --json-meta

### ISSUE THREAD

**Issue by theit8514** [JimmXinu/FanFicFare#272]
If I pass the arguments `--meta-only --json-meta --download-list URL` to FFF and the URL contains multiple books, the stdout from the command returns multiple JSON objects with no delimiter. Can this be updated to return a JSON array?

**Comment by JimmXinu** [comment]
Due to the way the it's coded, this would require non-trivial changes to the CLI code.  

Since the JSON output is only particularly useful as a script input, putting the logic to combine the JSON objects into an array in the receiving script doesn't seem like an outrageous requirement to me.

However, I see that Python's JSON methods don't easily provide a way do read multiple JSON objects from the same stream.  There are ways, but they seem to all require jumping through additional hoops or using additional libraries.

As a compromise, how about if I remove the `indent=2` option from the JSON option so each object is on a line by itself?  That eases parsing significantly plus you can more easily handle it when there are errors--they will be one non-JSON line instead of breaking the entire JSON output.

**Comment by theit8514** [comment]
Thanks for looking into it. Right now I'm working around the issue in my code by changing `}{` to `},{` and wrapping in brackets.

Just a thought, but could the do_download function return the metadata object and have the main function create the array of metadata objects and then convert to json?

**Comment by JimmXinu** [comment]
I looked at that.  The problem is dealing with the error/other cases where it currently doesn't return anything or gives error output.

Removing `indent` and getting line-per-record instead seems like the best compromise to me.  But I'm not going to bother if you don't think it will help you.

**Comment by theit8514** [comment]
Changing the indent would not help or break my current workaround, so I wouldn't bother right now. Thanks.
