### ISSUE TITLE
webnovel.com is not pulling in any tags.

### ISSUE THREAD

**Issue by vidalvanbergen** [JimmXinu/FanFicFare#299]
It seems that story tags from www.webnovel.com are not getting downloaded or added to the ebook.

**Comment by JimmXinu** [comment]
That's a bit vague, but I can see that we're not collecting `category`, `translator` or `editor` anymore.  Fixed in 771246c9de6eeee28f914072e23ddf0210451c0c

If you're talking about the secondary tags after the first category (such as Action under Science Fiction), those aren't any place I can find in the page or metadata about the story itself, only in the lists pages.

New test versions shortly.

**Comment by vidalvanbergen** [comment]
I'll try to be more specific since i'm not sure category and tags are the same thing either.

Using "The King's Avatar' for example (https://www.webnovel.com/book/7176992105000305/The-King's-Avatar)
I can see that the category for the novel would be 'Video games', and the tags, which can be found just below the synopsis are:

Action, Comedy, Brotherhood, Animation, MMORPG, Game, Smart protagonist, Great Translation, Great Novel, Brilliant, Game Elements, Funny, Skilled Protagonist, Internet Cafe, Nice MC, Gaming, Modern Setting, eSports, Professional Gaming, Teamwork

In the page's html code I can see an information source in json format under 'g_data.book', I'm not sure if you're using that to collect the information, but the tags can be found under "tagInfo" > "popularItems" > "tagName".

**Comment by JimmXinu** [comment]
Hmmm.  I searched the source on the page I was looking at for the tags and didn't find them.  Must have been on the wrong page.  157b0555e4c1294686ab12639cffdb0c06265baa adds `sitetags` as site specific metadata and starts collecting `rating`.
