### ISSUE TITLE
Issue with Web Service

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#300]
I have noticed that some ffnet stories that have a lot of chapters don't get downloaded and get stuck in the downloading phase

Here are a couple of examples of fics that end up like that:

> https://www.fanfiction.net/s/5939286/
> https://www.fanfiction.net/s/12289423/

**Comment by JimmXinu** [comment]
It looks like one of the requests took longer than the Google service allows:
`DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.`

Downloading from ffnet is generally slower than from other sites due to the sleeps added to keep from getting blocked by the site.  But this suggests that either ffnet started slowing or blocking requests, or just ended up taking too long for the web service.

In any case, it's not something that's under my control.  This is similar to the [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-has-the-web-service-version-of-fanficfare-stopped-working) about the web service running out of over all quota.

If you cannot use CLI or plugin instead, you might try downloading stories in chunks using the chapter range feature:
`https://www.fanfiction.net/s/5939286/[1-10]`
