### ISSUE TITLE
feature request: add a 'no confirm' mode to the calibre plugin

### ISSUE THREAD

**Issue by BrainDamage** [JimmXinu/FanFicFare#305]
Currently, every time one executes an operation ( or a batch of ) the plugin makes calibre to emit a popup dialog with the summary of changes ( amount of failures, successes, etc ), then prompt to continue or not

I would like to have an option to bypass such dialog and implicitly accept as yes no matter the amount of failures.

It's essentially a pointless dialogue since failed updates/actions don't impact existing books so I end up having to always press yes at the end to apply things for the items that succeeded, and for those which didn't, it doesn't hurt either.

**Comment by JimmXinu** [comment]
The 'Proceed with updating your library?' dialog is the official Calibre way for plugins to insure that the GUI's in memory data cache is not corrupted by different things updating  simultaneously.

Early FanFicFare (when it was still called FanFictionDownLoader) allowed that, but was changed shortly after.  You can still see [the original discussion](https://www.mobileread.com/forums/showthread.php?p=2155484) if you like, and where I [asked about it again](https://www.mobileread.com/forums/showthread.php?p=3530867) last year during the lead up to Calibre 3.0.

If you have reason to believe that Calibre's requirements have changed since then, I'd be happy to hear about it.
