### ISSUE TITLE
Spacebattles not supported?

### ISSUE THREAD

**Issue by Anonark** [JimmXinu/FanFicFare#317]
According to both the appspot and Calibre plugin versions, Spacebattles is no longer a supported site. Is this a bug or an intentional removal of functionality?

**Comment by JimmXinu** [comment]
Can you explain why you think that?  I’ve downloaded several from SB just today.

I suspect you have a story url that isn’t recognized.

**Comment by Anonark** [comment]
I've tried three different URLs so far, one a thread URL and two post URLs, all of which FFF couldn't recognize, both the web version and the calibre plugin:
https://forum.spacebattles.com/threads/delusional-dancing-dragon-touhou-worm-quest.375944/
https://forums.spacebattles.com/posts/14747765/
https://forum.spacebattles.com/posts/16320021/

I'm also currently using Calibre 3.20 with FFF 2.27.0

**Comment by JimmXinu** [comment]
Use https://forums.spacebattles.com/

Note the ‘s’ on forums.  That’s the link from spacebattles.com, so that’s what we use as canonical. 

I vaguely recall accepting ‘forum.’ for one of the xenforo sites at one time and then having to change it.  I’ll look at accepting both, but there may be a reason it doesn’t.

**Comment by JimmXinu** [comment]
I see you edited your comment to change forum.sb to forum**s**.sb.  Which kind of negates the entire issue report.

Are you trying to say that the URLs with forums.spacebattles.com also don't work for you?

**Comment by JimmXinu** [comment]
Assumed fixed.
