### ISSUE TITLE
Feature Request: Xenforo Forums Metadata

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#319]
Since Threadmarks give a lot of metadata in XenForo Forums (SB,SV,QQ) is it possible to add those in the final result?
Specifically:
1. Add date started & updated by the dates in the threadmarks
2. Add overall word count 
3. Add word count and date updated in the generated inline TOC

**Comment by JimmXinu** [comment]
1. `datePublished` and `dateUpdated` are already taken from the threadmark dates when threadmarks are used for chapter list.  If you have reason to believe that's not working correctly, please give an example.
1. Most sites provide a wordcount.  Rather than re-invent that particular wheel, FFF Calibre plugin has an option to call Calibre's wordcount routine for any story that doesn't get one from the site.  That has served me well.

   However, I see that there is an actual value (not just human-friendly k count) for each chapter in an invisible HTML attribute.  I will look into summing that for the benefit of CLI & webservice users.

3. Configurably including threadmark wordcount and/or post date in the chapter title is technologically possible, but something I'm a bit reluctant to do.  

   If added to the chapter title, they will appear both in the TOC and in the title at the start of each chapter; adding them to TOC only would require significant refactoring.  

   Plus there's a difference between the EPUB TOC (and the AZW3 TOC generated from it by Calibre conversion) and the (I assume rarely used) FFF generated TOC turned on by `include_tocpage`.

**Comment by Twilight666** [comment]
First of allit looks like 1 was my mistake, it's fine now. As for 3, yeah I was talking about the TOC from include_tocpage, but if it is that rarely used and if to create it you have to mess with the chapter titles then it's fine to ignore that,

**Comment by JimmXinu** [comment]
Threadmark wordcounts summed into numWords: f29f86d4

If "Add word count and date updated in the generated inline TOC" happens it will be rolled into #318 as chapter URL handling gets refactored.
