### ISSUE TITLE
tocpage links not working

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#320]
I downloaded a few stories with the 27.4 test version on CLI and the inline TOC is not working on AO3, XenForo and FFnet (the TOC created by include_tocpage)
I also tried this on calibre and had the same error
From editing the epub I can see that the url links point to file1.xhtml,file2.xhtml... while the filenames are file0001.xhtml,file0002.xhtml...

**Comment by JimmXinu** [comment]
Due to poor planning on my part, `chapter_title_*_pattern` settings expected index==1 while writer settings (such as `tocpage_entry`) expected index=0001.  

I've switched to using index04 to disambiguate (previously I'd tried 0index, but that doesn't work with python ${} subst), but index is kept in both places with the previous value for users' pre-existing settings.

I'll also need to update the custom output wiki page when this gets released.

I've put out test version v2.27.5 CLI and plugin.

**Comment by Twilight666** [comment]
Actually the CLI version isn't up yet:
https://test.pypi.org/project/FanFicFare/#history

**Comment by Twilight666** [comment]
... this is the bug that keeps on giving. Although it is not a bug in the code, but in my implementation
Technically this is my fault since this is a custom created url for the tocpage.
But since I copy-pasted the example from personal.ini (and edited it to add date and kwords), at the very least the example in personal.ini should be changed from 
```
#tocpage_entry:
# <a href="#section${index04}">${chapter}</a> ${date} ${kwords}<br />
```
to
```
#tocpage_entry:
# <a href="file${index04}.xhtml">${chapter}</a> ${date} ${kwords}<br />
```
In other words, change section to file and add .xhtml at the end to match the filenames created by FanficFare.
Also remove the # at the start

**Comment by JimmXinu** [comment]
I assume you mean you found the example in `defaults.ini`.  That example is for `[html]`, because that's the `tocpage_entry` example I had handy.

But you are correct that it is a problem when I'm recommending epub to everyone.

"Add [epub] tocpage_entry example to INIs for base_xenforoforum." d3b9315e
