### ISSUE TITLE
Problem downloading from RoyalRoad

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#324]
I am downloading a new story that has one chapter:
`https://royalroadl.com/fiction/19739`
And the end result is broken.

The chapter itself is downloaded but in the calibre version the `style="..."` is saved as `style=&quot;...&quot;` causing the epub to not work,
The CLI works fine.

Also I am using test version 2.27.5

(edit to make style vs style visible--JM)

**Comment by JimmXinu** [comment]
By default, FFF doesn't save `style` attributes, so clearly you have enabled that.

I do see this happening with the Calibre plugin, but _only_ with that one story.  

I don't see it with:
- CLI (as reported);
- Stories with style attrs from other sites;
- Another story on the same site (https://royalroadl.com/fiction/8894 which has a style attr near the end of the first chapter);
- The same story, but HTML output instead of epub.

I eventually narrowed it down to being an issue with using Calibre's word count.  `jobs.py` writes the story to epub, word counts that epub, then overwrites with a new epub containing the word count.  

_And_ it only effected single chapter works.

So thanks for finding this corner case, I'll have a test version out shortly.
