### ISSUE TITLE
Could we get LICENSE and README.md included into distributed tarball

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#329]
Trying to package FanFicFare for openSUSE and it would be lovely to have the text of license (I know, it is a standard GPLv3) and README.

**Comment by mcepl** [comment]
Preliminary package at https://build.opensuse.org/package/show/home:mcepl/python-fanficfare . I will make proper package when next release happens.

**Comment by JimmXinu** [comment]
I've added [LICENSE](https://github.com/JimmXinu/FanFicFare/blob/master/LICENSE), [README.md](https://github.com/JimmXinu/FanFicFare/blob/master/README.md) and [DESCRIPTION.rst](https://github.com/JimmXinu/FanFicFare/blob/master/DESCRIPTION.rst) to `MANIFEST.in` and they are now included in the `.tar.gz` generated by `setup.py`.

However, they are not installed anywhere that I see when the package is installed with `pip`.  I tried a few different approaches and the closest I found dropped them in `/usr/local` directly.

If you need more than it just being in the `.tar.gz`, I'm open to suggestions on how.

**Comment by JimmXinu** [comment]
`data_files` is what I tried first (398f9657264ed92edddc4e7e15bfdd74ee71205f) -- it's what dropped them in as `/usr/local/LICENSE` etc when installed with `pip`.  I can add a dir and make it a level lower, eg `/usr/local/fanficfare/LICENSE`, but that also seems a bit high up the tree for software installed in `/usr/local/lib/python3.6/dist-packages/fanficfare`.  

If you don't need them installed, I'm not going to worry about it any further.

I generally release roughly once a month, with the last at the beginning of August.  But I'm likely to wait longer this time so test users have more time to notice issues since pretty much every file has been touched.

**Comment by mcepl** [comment]
OK, don't worry, I have set up builds from the tip of the master branch on https://build.opensuse.org/package/show/home:mcepl/python-fanficfare and it seems to work just fine. I specifically wanted Py3k compatibility, so plain 2.28.0 won't cut it for me. But there is no rush, truly.

**Comment by eli-schwartz** [comment]
From an Arch Linux perspective, the reason I'd want those files distributed on PyPI is not so setup.py could install them -- it's so that they would be available in the tarball in order for me to cp them to a distribution-specific location.

That being said, a) I use the github tarball :p b) we don't package GPL licenses because they're "common" and as such get packaged in https://www.archlinux.org/packages/core/any/licenses/
