### ISSUE TITLE
500 error 

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#331]
Hi, attempted to download a story off AH and got a 500 message multiple times.
![47988a6f-0213-42f4-9299-69dbe7f0fa74](https://user-images.githubusercontent.com/36297332/44963680-bdd4ee80-aef1-11e8-90f4-316d9b63a2ad.png)

Help?

**Comment by Twilight666** [comment]
Ok I am not a part of the dev-team but I had a similar issue in #266  (although in my case it was in fanfiction.net).

But before that:

1. you should mention the site you have the problem in (AH probably means https://www.alternatehistory.com/forum/ but it's not mentioned in the issue)
2. you should mention the story that causes the problem.
3. you should also mention were it happens (CLI, calibre or the webservice).

Otherwise the devs won't be able to help you unless the problem is wide enough that a general check might make them stumble into it.
It look to me like it happens in the webservice version in which case it might be something similar to my case where the author page was problematic, so it might not be fixable.

**Comment by JimmXinu** [comment]
What I see in the logs for this is pretty much exactly the same as #266 (thanks to @Twilight666 for pointing that out) and has the same answer.

Without the story URL, I can't really say anything else.  Please include story URL in any future issues.

**Comment by DragoLord19D** [comment]
Apologies here you go.
https://www.alternatehistory.com/forum/threads/gonna-to-know-we-were-here.433309/

**Comment by JimmXinu** [comment]
I don't see any problems with the software itself downloading that story.

But I also see an eventual failure in web service.  Log says: `Exceeded soft memory limit of 128 MB with 153 MB after servicing 43 requests total.`

With 200+ chapters, it's not hugely surprising that the web service might have problems with that story.  Stories from alternatehistory.com have to download each chapter separately, which is a lot of hits.

Generally, it is recommended to use the Calibre plugin or command line (CLI) versions if you want to do more than occasional downloads.  We use Google's freebie level service for this, so limitations are to be expected.

However, if you are limited to the web service, you can download ranges of chapters at a time like so:

https://www.alternatehistory.com/forum/threads/gonna-to-know-we-were-here.433309/[1-40]

Again, prior issue #266 is the same and has the same answer.
