### ISSUE TITLE
Not Well-Informed (Invalid Token): line 10, column 25

### ISSUE THREAD

**Issue by Waterspark63** [JimmXinu/FanFicFare#338]
So I was trying to update a book from Fimfiction, and it gave me that error, Is it my side, or FFF's side?

[Good Griff! (193).zip](https://github.com/JimmXinu/FanFicFare/files/2412188/Good.Griff.193.zip)

**Comment by JimmXinu** [comment]
I assume that you mean for https://www.fimfiction.net/story/103811/good-griff  
Please include story URL in any issue report.

The epub attached was not created by FFF.  When FFF tries to parse it, the XML parser blows up.

I'm able to download the story from that URL in FFF without any problem, and update the downloaded epub.

So this isn't FFF's problem.  

If you do a Calibre Convert epub->epub on it, the XML will be fixed enough that FFF doesn't blow up parsing it, but there isn't really point since FFF doesn't recognize the existing chapters in that epub and will download them all again anyway.
