### ISSUE TITLE
sugarquill.net produced epub is not correct

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#348]
epubReader (addon for Firefox) fails on this epub [Lessons for Life-sq_106.zip](https://github.com/JimmXinu/FanFicFare/files/2483320/Lessons.for.Life-sq_106.zip) which is download from http://www.sugarquill.net/read.php?storyid=106&chapno=2

**Comment by JimmXinu** [comment]
Do you have any more detailed description of the problem?  Or evidence that it's a systematic problem rather than an issue with that particular story?

Issues with a 16 year old story on a site that's been frozen for a decade are really not a priority for me unless you can show it's happening across a wide range of stories or something that's been broken by changes in FFF.

Here's a copy of the epub(renamed zip) that I've used Calibre's Edit Book to fix the problems in the story HTML reported by it's Check Book feature:
[Lessons for Life-sq_106.zip](https://github.com/JimmXinu/FanFicFare/files/2483371/Lessons.for.Life-sq_106.zip)

**Comment by mcepl** [comment]
Sure, I am not saying that it should be your priority. Concerning the age of the story, I though that pages on the site are generic and the same, so the age of the particular story should be irrelevant, shouldn't it?

**Comment by JimmXinu** [comment]
A lot of sites, especially older ones, let authors upload their own html.
So each author and even each story can use different html.
-- 
Jim Miller
RetiefJimm@gmail.com

**Comment by mcepl** [comment]
OK, whatever.
