### ISSUE TITLE
Royal Road Update Emails not Parsing

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#349]
Royal Road Update Emails aren't parsing properly. This is because the royalroad update emails don't have a proper recognizable URL, since they send the emails of the form 

`http://clicktracker.royalroadl.com/wf/click?upn=8li4huaLF4rdTD-2Bp8XTPlZuj53fXjDpt9-2FJ53IyczbwDPy3SmXdJBgsEZwA7K-2F5Ix9SDDjS0CalGgtmkAvUBCA-3D-3D_d19oppgaxE6wOerZqxZl-2BgvymUYM5ZqWJIAoEI-2BRRpAwmJzW-2F2lrQumjq91Tcg5A5tgQUMkxuQbJNLbV2FDj0lAeoKgSY7QmePrDrK3lKiEKzi-2BMPhf06iryvsmI9ZMjBJkbtFB2-2FS7Y8BLJM-2FVlS6xzWizbwO8fKWejwR6ze99dhuJSUVgQDhsqvmABd1ECLJEWPsjUDN-2FW3Nx0w7zaZtbySTdYD5jPPjpxR3LOVxE-3D`

which performs a redirect and gives the actual response requested, which is 

`'https://www.royalroad.com/fiction/8894/everybody-loves-large-chests/chapter/299470/legacy-1'`

This can be solved [here](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/geturls.py#L181), I'm pretty sure, by doing something like the following

`
import requests
def cleanup_url(href,email=False):
    ## used to perform some common URL clean up.

    # this (should) catch normal story links, some javascript 'are you
    # old enough' links, and 'Report This' links.
    if 'story.php' in href: ## various eFiction and similar.
        m = re.search(r"(?P<sid>(view)?story\.php\?(sid|psid|no|story|stid)=\d+)",href)
        if m != None:
            href = form_url(href,m.group('sid'))
    elif 'clicktracker' in href:
       response = requests.get(href)
       href = response.url
    elif email and '/threads/' in href:
        ## xenforo emails, toss unread and page/post urls.  Emails are
        ## only sent for thread updates, I believe.  Email only so
        ## get_urls_from_page can still get post URLs.
        href = re.sub(r"/(unread|page-\d+)?(#post-\d+)?",r"/",href)
    href = href.replace('&index=1','')
    return href`

There might be an argument for running this on all of the urls to get their final result, but I'm not sure how that would interact with some of the sites that have additional javascript shenanigans going on.

**Comment by JimmXinu** [comment]
First, a few notes:

`requests` package is not available in Calibre.  FFF uses lower level `urllib`, now as presented by `six`.

Email notifications use clicktracker.royalroad _l_ .com not royalroad.com (no l), apparently? 
clicktracker.royalroad.com doesn't exist.  I wonder how long until that changes...

I'm not interested in calling every URL in every email just to see which might redirect to a story URL.  Nor is it something that could be done configurably, since the site hasn't been identified yet at that point.

But I am willing to try it for individual sites that need it.  I've added some code to watch for clicktracker.royalroad (for when they change to royalroad.com) and it has to set User-Agent to something or else it gets a `HTTP Error 403: Forbidden`.

As I recall, you are a CLI user?  I'll push a test version of CLI.

**Comment by MrTyton** [comment]
Sounds good. I tried putting in specifically the clock tracker part so that
not everything needs to be tested.

Using urllib works, requests just didn't need a header so I didn't bother
with it. That's reasonable.

I think that the click tracker is probably just something for internal
metrics. All of their email uses that, even the privacy policy link.

I am a cli user, I'll update my side with the pushed code and test it
later. ( Thanks for reminder me to update my repo BTW)

**Comment by JimmXinu** [comment]
FYI
`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by MrTyton** [comment]
The fix seems to have worked on my test cases. I'll mark this closed for now unless something else similar comes up in the future.
