### ISSUE TITLE
Request Support for https://www.readlightnovel.org/

### ISSUE THREAD

**Issue by AvatarWan** [JimmXinu/FanFicFare#359]

**Comment by JimmXinu** [comment]
Closing this one due to site apparently include copyrighted material.

(These are some notes I made a while ago for this issue but didn't publish at the time.)

> "READ DAILY UPDATED LIGHT NOVEL, WEB NOVEL, CHINESE NOVEL AND KOREAN NOVEL ONLINE."

- Contains copyrighted material: 
  - I see _All You Need Is Kill_, the source for Live, Die, Repeat & _Banner of the Stars_
  - Don't see any fanfiction...
- Stories without chapters
- At least one (Martial God Asura) even says it comes from another site, http://www.wuxiaworld.com/
- Ad JS in the chapter texts
- Hidden display:none version of text.  JS injects ads?
