### ISSUE TITLE
Support for deviantArt (reformatted)

### ISSUE THREAD

**Issue by DonaldTsang** [JimmXinu/FanFicFare#374]
### Regarding DeviantArt
- `<div class="text">` has everything in the text
- `<img class="smshadow">` has the thumbnail
- `<div class="metadata">` and `<div class="text block">` needs some wrangling for tagging
### Example story URLs with image thumbnails
- https://www.deviantart.com/natsneko/art/Jouer-Tenue-Tridentes-427857746
- https://www.deviantart.com/natsneko/art/Jouer-Tenue-Adamas-428302598
- https://www.deviantart.com/natsneko/art/Jouer-Tenue-Ramus-428056889
- https://www.deviantart.com/natsneko/art/Jouer-Tenue-Animus-428742642
### Example story URLs without image thumbnails
- https://www.deviantart.com/samurai-papers/art/MafiaStuck-339027996
- https://www.deviantart.com/esper30/art/Mobstuck-A-Homestuck-Fanfiction-316504186
- https://www.deviantart.com/eccentricpapillon/art/Azure-and-Tyrian-258374809

**Comment by JimmXinu** [comment]
FanFicFare is built around the assumption (for most sites) that stories have chapters and a chapter list.

deviantart.com is a site built around a one page == one work paradigm.  I see numerous works with names such as "Whatever Chptr 6", "Something else Chapter 2-5", "012. Another thing".  But I see no mechanism that FFF could reliably use to tie them together.  While there are 'Gallery Folders' that authors can create, I didn't find any that function as a chapter list when looking at a few obvious multi-chapter works.

This site could be implemented in FFF with one page == one story, leaving it up to the FFF user to deal with multi-chapter stories, either as individual ebooks or by manually making anthologies.  

And theoretically, multiple chapters could be detected from the author's Gallery.  But because no naming convention is enforced it would be heuristic at best.

I'm not personally interested in adding support for this site, but I will review and (probably) accept contributed code for it.  I'll leave this issue open in case someone else is interested in implementing it.

**Comment by DonaldTsang** [comment]
@JimmXinu perhaps FFF can have a mode that accept lists of chapters (manually chosen) and combining them into one story.
