### ISSUE TITLE
[Feature] Optimize chapters downloads by spawning new process/thread for each of them.

### ISSUE THREAD

**Issue by DanGSun** [JimmXinu/FanFicFare#376]
Hello.
I am writing a deep-learning algorithm for fanfiction related processes. I've noticed that FanFicFare downloader is very slow. I have 100mbit/s broadband connection and can't use it maximally. For 10 hours I've only downloaded 1,3 GiB.

Thx for your attention.

**Comment by JimmXinu** [comment]
FanFicFare doesn't download as fast as possible to avoid putting excessive load on the sites that host the stories.  If you and a hundred other people all try to download from a site at your maximum bandwidth rate, that's going to raise costs or even crash servers on the story hosting site.

Slower downloads are a deliberate design decision.  For many sites, FanFicFare includes sleeps to slow down even more because some story sites, [notably fanfiction.net](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet), watch for 'excessive traffic' and will start blocking you if detected.

**Comment by DanGSun** [comment]
I understand, that maybe this is not question to ask here, but can you give me the advice to increase my import speed?

**Comment by cryzed** [comment]
Write your own scraper for the targeted site.
