### ISSUE TITLE
Combine meta and file write

### ISSUE THREAD

**Issue by theit8514** [JimmXinu/FanFicFare#383]
When I run the FanFicFare cli with the `--meta-only --json-meta` options, the epub file gets written with just the TOC page and no chapters. After this, running the command without `--meta-only` results in the process not updating the empty epub file:

    File(story.epub) Updated(2019-03-01) more recently than Story(2019-02-25) - Skipping

Would it be possible to add the ability to output the meta json and write the full story file in one pass? Possibly a `--force-full-story` option? I'll be glad to PR it, if needed.

Edit:
I am also now getting this message when trying to use `--update-epub --meta-only --json-meta`

    story.epub doesn't contain any recognizable chapters, probably from a different source.  Not updating.

**Comment by JimmXinu** [comment]
The `-m`/`--meta-only` option was added as a debugging tool, not a scripting tool; `--json-meta` was added later.  I think the only reason `--meta-only` even writes an output file is because it didn't occur to me not to.  So I've never thought very hard about what that output file looks like.

First, the mostly empty `--meta-only --json-meta` epub contains titlepage, but I don't get a TOC page.

The personal.ini option `always_overwrite: true` exists to force overwrite when the epub is newer.

It doesn't surprise me that combining `--update-epub` and `--meta-only` has unexpected results; it's not a case I ever considered.  FFF doesn't update an epub when it doesn't find *any* chapters on the assumption (as stated) that it's probably from a different source.

> Would it be possible to add the ability to output the meta json and write the full story file in one pass? > Possibly a --force-full-story option? I'll be glad to PR it, if needed.

I think I'd be more inclined to allow `--json-meta` when downloading/updating as well as with `--meta-only` rather than adding a new option to contradict the 'only' part of `--meta-only`.

**Comment by JimmXinu** [comment]
See what you think of #384.

**Comment by JimmXinu** [comment]
Please let me know if this change helps.  

I'm going to do a release this week, but I won't include this change if I don't know that it addresses your issue.

**Comment by theit8514** [comment]
Looks like this will help. I will be able to test tomorrow. Thanks!

**Comment by theit8514** [comment]
Just finished testing the new branch and it both `-j` and `--update-epub` are working together. Thanks.

**Comment by JimmXinu** [comment]
Okay.  I've merged that branch and uploaded a test CLI.  

In case you need it:
`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`
