### ISSUE TITLE
Book downloaded from www.mugglenetfanfiction.com has incorrect encoding

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#385]
When I download http://www.mugglenetfanfiction.com/viewstory.php?sid=93638 with FFF 3.5.0, I get 
[Aunt Marge's Even Bigger Mistake-mgln_93638.epub.gz](https://github.com/JimmXinu/FanFicFare/files/2940066/Aunt.Marge.s.Even.Bigger.Mistake-mgln_93638.epub.gz). Whereas the original story is encoded with ISO-8859-1 encoding (yes, that's a very stupid idea), included HTML is marked as UTF-8, so all doublequotes are displayed as â character.

**Comment by mcepl** [comment]
Hmm, and another one http://www.mugglenetfanfiction.com/viewstory.php?sid=93428 is correct. There is probably no way how to make it work in the unified fashion, right?

**Comment by JimmXinu** [comment]
FFF has a `website_encodings` setting that can be used to correct for when an author uploads the wrong encoding.

However, changing encoding to iso-8859-1 for [that story](http://www.mugglenetfanfiction.com/viewstory.php?sid=93638) doesn't work.

A bit more investigating shows that sid=93638 is mostly utf8, but there's one or more characters that aren't utf8 and error, so FFF goes to the next encoding on its list, which 'works' in that it doesn't error, but isn't correct either.

In this case, you can use FFF's encoding 'ignore' feature to force utf8 encoding while ignoring any errors the decode encounters:

```
[http://www.mugglenetfanfiction.com/viewstory.php?sid=93638]
website_encodings:utf8:ignore
```

It's not recommended to use that for the whole site, because then FFF can't ever fail to the next encoding.  But you could.
