### ISSUE TITLE
The series title is not include correctly at SOL.

### ISSUE THREAD

**Issue by T-Man2000** [JimmXinu/FanFicFare#386]
With storiesonline.net (SOL), the series titles are not include correctly. Some examples:

https://storiesonline.net/s/19249/rich-kid-1-freshman-year
Series @ Sol: "Rich Kid"
Series @ Calibre: "Rich Kid —		A Universe from the Mind ofDark1 [0]"

https://storiesonline.net/s/16863/warlord-and-traitor-redux
Series @ Sol: "Warlord and the Multiverse"
Series @ Calibre: "The Warlord and the Multiverse —		A Universe from the Mind ofHunter Johnson [0]"

**Comment by JimmXinu** [comment]
storiesonline.net has separate series and universe metadata.  Those stories are part of a universe rather than a series.  But FFF has a `universe_as_series` setting which defaults to true.

I don't read SOL, and most of the code for its adapter was written by others, so I don't know off hand if the current behavior is a best-effort compromise, or if the site has changed since, or what.  But it looks like the universe page now lists an order for stories, which I think it lacked before.

I'll look into it, see what I can figure out.  I also have to watch out for the fact that FFF's adapter for finestories.com shares code with the adapter for storiesonline.net

**Comment by JimmXinu** [comment]
The code seems to indicate that storiesonline.net/finestories.com stories can have both series and universe.  I think--I haven't actually found any.

I've made changes(29ada606c5ba63b94c5e6312fcca7fe879c2d58d) to remove 'A Universe from the Mind of...' from universe (and series when using `universe_as_series`) and to use the position in the universe list as series number when using `universe_as_series`.

Test versions in the usual places: [plugin](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2), [web service](https://3-5-6-dot-fanficfare.appspot.com/), [CLI](https://test.pypi.org/project/FanFicFare/).
