### ISSUE TITLE
AFF(asianfanfics.com) Error: Blank Chapters

### ISSUE THREAD

**Issue by TeaMee321** [JimmXinu/FanFicFare#394]
Hi! I recently tried downloading a fic from AFF using Fanficfare and it did download into an ePub format. When I opened it though, only the title page and the chapter titles were present. I tried it with other stories and it's the same thing. The text per chapter were blank. I tried restarting and I tested it out on A03 if it had the same issue, but I was still able to download fics from AO3 and Wattpad with complete chapters.

**Comment by JimmXinu** [comment]
AFF meaning adult-fanfiction.org?  I don't read that site, but the test story I use downloaded correctly, as did another recent story chosen at random.

I need some story URLs that exhibit the problem before I can really investigate it.

**Comment by TeaMee321** [comment]
AFF is Asianfanfics.

**Comment by JimmXinu** [comment]
asianfanfics.com has changed and the chapter text is now fetched from a JSON URL instead of included in the page html.

I've changed FFF to do that too (7590dd8003645ba6021aef91b914f03f0ff20818), which appears to work correctly to me.

But I don't read asianfanfics.com either, so let me know if it works correctly for you.

I've posted a [test version of the Calibre plugin](https://www.mobileread.com/forums/showthread.php?p=3084025#post3084025).

**Comment by TeaMee321** [comment]
Oh. that's why the text chapters won't appear. I've updated FFF but how can you update the asianfanfics adapter?

**Comment by JimmXinu** [comment]
It's in the test version plugin linked in my previous message.  Download the zip, install it in Calibre as a plugin.  

If you need help with that, see [Intro to Plugins](https://www.mobileread.com/forums/showthread.php?t=118680) and look for 'How do I install a plugin manually?'

**Comment by TeaMee321** [comment]
I was able to update it and it worked for AFF already. Thank you so much!

**Comment by JimmXinu** [comment]
Okay.  Re-open this issue if you find more problems with asianfanfics.com chapters before the next release.
