### ISSUE TITLE
harrypotterfanfiction.com psid v chapterid

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#398]
```sh
~$ fanficfare --debug 'https://harrypotterfanfiction.com/viewstory.php?chapterid=449522'
FFF: DEBUG: 2019-04-28 23:20:38,628: cli.py(184):     OS Version:Linux-5.0.8-1-default-x86_64
-with-glibc2.2.5
FFF: DEBUG: 2019-04-28 23:20:38,628: cli.py(185): Python Version:3.7.2 (default, Dec 30 2018,
 16:18:15) [GCC]
FFF: DEBUG: 2019-04-28 23:20:38,628: cli.py(186):    FFF Version:3.6.0
Bad Story URL: (https://harrypotterfanfiction.com/viewstory.php?chapterid=449522) for site: (
harrypotterfanfiction.com) Example: (https://harrypotterfanfiction.com/viewstory.php?psid=123
4)
```

**Comment by mcepl** [comment]
Actually, it is possible to get URL with psid from ``.section__content > h2:nth-child(1) > a:nth-child(1)`` (CSS Selector) or ``/html/body/main/section[1]/article/div/h2/a`` (XPath), so perhaps it should be possible to add just a simple conversion of URLs.

**Comment by JimmXinu** [comment]
When the chapter URL contains enough info to deduce the story URL, FFF accepts chapter URLs.

As a general rule, we don't accept chapter URLs (as story URLs) when it requires another fetch to get the real story URL.

Since you're using CLI anyway, you can also use `-l` to get the story URL from the chapter URL.

**Comment by mcepl** [comment]
Right, I forgot about ``-l``, you are right.
