### ISSUE TITLE
FFN adapter: Avoid redownloading old chapters

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#415]
When updating a fic from FFN, debug output suggests all pages are downloaded afresh.
To reproduce:
```
fanficfare -d "$url[1-5]"
mv "$title" "${title/ (Ch*)/}"
touch -t$(date --date=@0 +%Y%d%m%H%M)
fanficfare -ud "$url"
```
As can be seen, the second call to fanficfare downloads all the chapters, which can lead to a large number of connections for long fics.

However, the naive solution -- noting the chapter count difference between the on-disk version and the online version and updating just the new chapters -- would be wrong in case of chapter edits (e.g. sometimes authors leave a note re the following chapter, then overwrite it by the new chapter when publishing). Perhaps a choice of update heuristic, with ```append-new``` being the default, with the caveat that it might miss chapters?

**Comment by JimmXinu** [comment]
1) FFF looks inside the EPUB of the *same name* for the existing chapters.  When you move it away, of course FFF downloads everything again--it can't find the EPUB.  Functioning as designed.
2) Yes, FFF assumes that old chapters are unchanged.  The only way to know if an existing chapter has changed is to download it again, which defeats the point.  ("Last-Modified" headers do not report last author update.)

Many consider this a feature because it also means you can 'fix' poor author formatting etc without it being overwritten later.

**Comment by hseg** [comment]
On 23 July 2019 0:05:39 GMT+03:00, Jim Miller <notifications@github.com> wrote:
>1) FFF looks inside the EPUB of the *same name* for the existing
>chapters.  When you move it away, of course FFF downloads everything
>again--it can't find the EPUB.  Functioning as designed.
The ```mv``` line is there to remove the ``` (Ch 1-5)``` part of the filename, leaving just he expected ```$title_$extractor-$id.$ext```
>2) Yes, FFF assumes that old chapters are unchanged.  The only way to
>know if an existing chapter has changed is to download it again, which
>defeats the point.  ("Last-Modified" headers do not report last author
>update.)
This contradicts my experience with the xenforo adapters. As I mentioned, some authors post ANs as the last chapter, then replace them by the actual chapter. FFF picks up on this correctly. However, I'd need to test whether a) these adapters display the same "download everything" behaviour and b) if they only succeed here because both threadmarks and URLs differ.
>
>Many consider this a feature because it also means you can 'fix' poor
>author formatting etc without it being overwritten later.
Right, which means I'm still confused why downloading chapters 1-5 then downloading+updating generates more requests for chapters 1-5. Surely after requesting chapter 1 FFF has enough metadata to know to request chapters 6-latest only?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JimmXinu** [comment]
I see exactly what I expect to see when I download 5 chapters, then update the same EPUB.  FFF hits the chapter 1 URL again because that is also the story URL of record for ffnet stories, then continues on from chapter 6.

I don't know why you are seeing chapters 1-5 reloading.  You can be sure that any file name weirdness is avoided by giving the existing EPUB path name as the parameter:
```
fanficfare -d "https://www.fanfiction.net/s/12512455/1/[1-5]"
fanficfare -u "Lex Marks The Spot (Ch 1-5)-ffnet_12512455.epub"
```

You can also disable chapter range naming by setting `title_chapter_range_pattern` to an empty value:

```
[defaults]
title_chapter_range_pattern:
```

On Xenforo sites, you are seeing different posts with different 'chapter' URLs.  Some sites use unique chapter URLs and some, like ffnet, simply number them.  If the chapter URL is different, to FFF, it is a different chapter.  If an author edits and existing post instead of making a new post, FFF will not pick that up.  And FFF is still going to use simple chapter count to determine if update is needed or not.

**Comment by hseg** [comment]
On Mon, Jul 22, 2019 at 06:30:34PM -0700, Jim Miller wrote:
> I see exactly what I expect to see when I download 5 chapters, then update the same EPUB.  FFF hits the chapter 1 URL again because that is also the story URL of record for ffnet stories, then continues on from chapter 6.
> 
> I don't know why you are seeing chapters 1-5 reloading.  You can be sure that any file name weirdness is avoided by giving the existing EPUB path name as the parameter:
> ```
> fanficfare -d "https://www.fanfiction.net/s/12512455/1/[1-5]"
> fanficfare -u "Lex Marks The Spot (Ch 1-5)-ffnet_12512455.epub"
> ```
> 
> You can also disable chapter range naming by setting `title_chapter_range_pattern` to an empty value:
> 
> ```
> [defaults]
> title_chapter_range_pattern:
> ```
> 
> On Xenforo sites, you are seeing different posts with different 'chapter' URLs.  Some sites use unique chapter URLs and some, like ffnet, simply number them.  If the chapter URL is different, to FFF, it is a different chapter.  If an author edits and existing post instead of making a new post, FFF will not pick that up.  And FFF is still going to use simple chapter count to determine if update is needed or not.
Hm. For some reason the problem seems to have gone away. Welp.
Have updated to 3.9.9 since, so it might have only been a problem in the old
version.
