### ISSUE TITLE
Request for www.the-sietch.com/

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#430]
Spacebattles has splintered... again. is there a chance for https://www.the-sietch.com/ to be added?

**Comment by JimmXinu** [comment]
While using xenforo2, the-sietch.com uses a different URL scheme than the existing supported xenforo sites.  It apparently processes all URLs through index.php:

- https:/ /www.the-sietch.com/ _**index.php?**_ threads/undiscovered-frontier-origins-season-1-big-steve-lcs-dilgar-war-tie-in.749/
- https:/ /www.the-sietch.com/ _**index.php?**_ threads/undiscovered-frontier-origins-season-1-big-steve-lcs-dilgar-war-tie-in.749/reader/
- https:/ /www.the-sietch.com/ _**index.php?**_ threads/undiscovered-frontier-origins-season-1-big-steve-lcs-dilgar-war-tie-in.749/page-3#post-13421
- https:/ /www.the-sietch.com/ _**index.php?**_ goto/post&id=11193
(spaces added to urls to allow text marks)

Instead of just plugging in, the different URL scheme requires a number of changes, which would also effect the existing base_xenforo adapters.  I will consider it, but I'm not promising to do it. 

Plus, it looks to me like a case of the-sietch.com not finishing the server configuration or running somewhere they can't change the server configuration.  Both of which suggest to me that they might change the URL scheme when more settled or migrating to larger hosting.

**Comment by JimmXinu** [comment]
Test versions in the usual places.
