### ISSUE TITLE
Thank You and AO3 question

### ISSUE THREAD

**Issue by DementedShoe** [JimmXinu/FanFicFare#431]
This is a very awesome program, and I thank you for the time and effort you put in. My question isn't necessarily a bug, but clarification. On the existing epubs I have in Calibre from Archive of Our Own, the plugin doesn't recognize any URL. I am assuming I need to add it manually for WIP stories that I have already downloaded.... or am I using the tool incorrectly?  Thank you again, and keep up the good work!

**Comment by JimmXinu** [comment]
One of the FFF config options on the first tab is "Search Inside ebooks for story URLs".  If you check that on, FFF will find story URLs inside epubs downloaded from AO3.  

Be aware, however, that because AO3 names the chapter files inside the epub differently, if you update an AO3 epub, FFF will download all chapters again.  This is not a big performance hit on AO3 as long as you haven't turned off the `use_view_full_work` setting in personal.ini.
