### ISSUE TITLE
Calibre Plugin: Maximum recursion limit at 1000 chapters?

### ISSUE THREAD

**Issue by bilinear** [JimmXinu/FanFicFare#432]
Tried https://www.royalroad.com/fiction/27273 and all chapters after 999 have this maximum recursion limit error, resulting in the job not completing.  I realize there is likely not a lot of fictions with over 1000 chapters, but the fact that I can't even choose to do a limited number of chapters is a little frustrating. This occurred on the same fanfiction on webnovel and also now that has appeared on RoyalRoad.com

maximum recursion depth exceeded in cmp
[recursionlimit.txt](https://github.com/JimmXinu/FanFicFare/files/3649737/recursionlimit.txt)

Attached is the log provided.

**Comment by JimmXinu** [comment]
That recursion is occurring the mobi output code which is known to be rather poor.  (Thanks for including the log--I assume everybody uses EPUB and I wouldn't have considered the mobi code.)

I recommend all Calibre plugin users download to EPUB and use Calibre's excellent conversion code to make AZW3 for Kindles.  You avoid the flaws of FFF's mobi output and you can also do updates instead of downloading all chapters every time.  I use a Kindle everyday and that's how I do it.

I'll see if the mobi recursion can be avoided, but I can't promise anything--the mobi output pre-dates my involvement in the project and is rather brittle.

BTW, you _can_ a download to a chapter range by putting it at the end of the URL when using Download from URL:
https://www.royalroad.com/fiction/27273[1-500]

**Comment by bilinear** [comment]
Ah, could have sworn I had tried epub when mobi did not work and it did not
work either but I just tried epub and was able to succeed. In that case I
will do as you suggest and just do epub then convert to AZW3.

**Comment by JimmXinu** [comment]
I've looked at this and it's actually something inside one of the dependencies, bs4, that's going into too many recursion levels.  It's not obvious what in the mobi code is causing it, but I suspect that it's some unclosed tag.  Epub, txt and html outputs all work fine.

It's also possible to increase the stack limit like so: `sys.setrecursionlimit(10**6)`.

Since this is a relatively obscure corner case, I'm going to leave it as-is.
