### ISSUE TITLE
Invalid credentials error on fetch from IMAP

### ISSUE THREAD

**Issue by binyaminyblatt** [JimmXinu/FanFicFare#437]
im trying to download from my email i know i have all the settings right but i keep on getting this error 
calibre, version 4.1.0
ERROR: Unhandled exception: <b>error</b>:[AUTHENTICATIONFAILED] Invalid credentials (Failure)

calibre 4.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Quality Check (1, 9, 11) && Generate Cover (1, 5, 21) && Count Pages (1, 8, 2) && Obok DeDRM (6, 5, 4) && FanFicFare (3, 11, 0)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 478, in get_urls_from_imap_menu
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 218, in get_urls_from_imap
  File "imaplib.py", line 523, in login
error: [AUTHENTICATIONFAILED] Invalid credentials (Failure)

**Comment by JimmXinu** [comment]
That is exactly the error given for a bad user/pass, so that's what I'm inclined to blame.

What mail service are you using?

**Comment by binyaminyblatt** [comment]
gmail

**Comment by binyaminyblatt** [comment]
i can login on the web

**Comment by JimmXinu** [comment]
I use Gmail with this feature all the time, so I know it works with Gmail.

- Are you setting this up for the first time, or was it working before and then stopped?
- Did you enable IMAP in your Gmail account?
- Do you have two-factor authentication enabled?  Do you use individual app passwords?
- Have you cut & paste your user/pass in and made sure you didn't add any stray spaces?

I haven't seen it with Gmail, but have seen at least one Internet app that accepted *different* sets of punctuation marks in passwords in different interfaces.  If nothing else works, you might try changing your pass to use more common marks.

**Comment by binyaminyblatt** [comment]
Are you setting this up for the first time, or was it working before and then stopped? 
its the first time on this pc  but i used it on other computers 
Did you enable IMAP in your Gmail account?
yes
Do you have two-factor authentication enabled? 
no 
Have you cut & paste your user/pass in and made sure you didn't add any stray spaces?
yes

**Comment by binyaminyblatt** [comment]
my pass has no symbols

**Comment by JimmXinu** [comment]
More esoteric ideas, because I'm out of good ones:

- Do you use a proxy service/server to reach the Internet?  Is it configured in Calibre?
- Do you have anti-virus / personal firewall software running?  We've seen problems with AV blocking outgoing connections before, but I would expect the error to be different.
- Have you done the restart calibre - reboot windows dance?
- You might try clearing your DNS cache in windows.
- You might try a standalone IMAP client like Thunderbird and see if that computer can use Gmail IMAP at all or if it's just Calibre.
- If you have Python CLI installed, you might try installing the FFF CLI with `pip` and try IMAP access from `fanficfare` CLI.  It's configured in `personal.ini` with the CLI.

**Comment by binyaminyblatt** [comment]
Do you use a proxy service/server to reach the Internet? Is it configured in Calibre?
no
Do you have anti-virus / personal firewall software running? We've seen problems with AV blocking outgoing connections before, but I would expect the error to be different.
ive tryd disabling it
Have you done the restart calibre - reboot windows dance?
yes
You might try clearing your DNS cache in windows.
yes
You might try a standalone IMAP client like Thunderbird and see if that computer can use Gmail IMAP at all or if it's just Calibre.
it works on outlook 
If you have Python CLI installed, you might try installing the FFF CLI with pip and try IMAP access from fanficfare CLI. It's configured in personal.ini with the CLI.
how do i do this??

**Comment by binyaminyblatt** [comment]
maybe you want to remote in to see it yourself

**Comment by JimmXinu** [comment]
Sure, if you want to send me the user/pass on email I'll give it a try.
retiefjimm@gmail.com

**Comment by JimmXinu** [comment]
Trying it in Thunderbird, I get a different error:

> You've reached this page because we have detected that cookies are disabled in your browser. The page you attempted to load cannot display properly if cookies are disabled.
> Please enable cookies and retry the operation or go back in your browser.

Searching for that leads to mentions of Google trying to force everything to use OAuth2.  FFF doesn't do that because it's a PITA.

You can enable 'less secure apps' by going Gmail > Settings > Accounts > Google Account settings > Security and turning on Less secure app access.  

It may also work to use an 'App password' with 2 factor auth.  [Google Answer page](https://support.google.com/mail/answer/7126229?visit_id=637066874290229946-604626614&hl=en&rd=1)
