### ISSUE TITLE
Feature Request: Chapter Count Added to Calibre Summary

### ISSUE THREAD

**Issue by Ultrabenosaurus** [JimmXinu/FanFicFare#444]
It'd be great if there was a tickbox in the Calibre plugin settings that would cause the chapter count to be prepended to the summary as shown in the Calibre sidebar, so we don't have to open the books to see it and can just flick through at a glance.

**Comment by Ultrabenosaurus** [comment]
I just figured out how to show this as a custom column in Calibre which accidentally, and redundantly, also adds chapter count to the sidebar. I still think this would be a nice feature for a lot of users, especially people who don't want to add it as a custom column.

**Comment by JimmXinu** [comment]
You can experiment with using personal.ini setting to add the chapter count to description like so:
`include_in_description:numChapters,description`

A specific dedicated feature for including the one metadata item to description instead of using the extensive existing features for populating custom columns from metadata is not something I'm interested in adding, sorry.
