### ISSUE TITLE
Strikethrough on QQ

### ISSUE THREAD

**Issue by EmpressFiona** [JimmXinu/FanFicFare#448]
Strikethrough tags do not get properly converted by FanFicFare. FFF _recognizes_ that a tag is applied to strikethrough text, via placing <span> tags around it, but it doesn't actually _style_ the strikethrough text.

I only tested with QQ, converting to EPUB. If there's something I should be doing in the config for this, I don't know it. (I believe it also processes down-sized text improperly while functioning with subscript normally, but I assume that's because of behaviour on the Xenforo end of things.)

**Comment by JimmXinu** [comment]
Please provide at least one story URL, chapter and specific phrase that exhibit each issue.

**Comment by EmpressFiona** [comment]
A URL of the chapter in question: https://questionablequesting.com/threads/clearest-blue-the-reconquest-of-bella-porte-original.8981/page-2#post-2417402

The passage:

> ~~The Fourth Art, that whispers in the ears of all those who truly master the others by unlocking the doors, and lets them use their very hearts to corrupt others...and at the same time, themselves. Forbidden to all, only its name remains, but it survives. From this Art, one learns to grasp their true desires, like the Old Masters that founded the noble houses, eyes turned colors like violet or gold.~~

**Comment by JimmXinu** [comment]
By default, FFF normalizes text by removing styling, but you can configurably keep it. 

Add `add_to_keep_html_attrs:,style` under the section for QQ `[forum.questionablequesting.com]` or just that one specific story `[https://questionablequesting.com/threads/clearest-blue-the-reconquest-of-bella-porte-original.8981/]` in your `personal.ini`:

```
[forum.questionablequesting.com]
add_to_keep_html_attrs:,style

## OR:

[https://forum.questionablequesting.com/threads/clearest-blue-the-reconquest-of-bella-porte-original.8981/]
add_to_keep_html_attrs:,style
```

Note that you'll need to re-download the story--FFF can't magically restore discarded attributes.

(I needed to see the specific issue because if it was CSS applied to an HTML class instead the solution would be different.)
