### ISSUE TITLE
[bug] can't download a specific story on mediaminer others work fine

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#449]
With Fanficfare's Calibre plugin (version : 3.13.1).
When attempting to download this particular story: 
>https://www.mediaminer.org/fanfic/s/ranma-1-2-fan-fiction-love-hina-fan-fiction-mahou-sensei-negima-fan-fiction/coming-home-to-roost/145320

The download fails with the following commentary:
> normalize() argument 2 must be unicode, not str

The error persists after multiple attempts.
Here is a debug log from Calibre:   
[tmpvdgpy1.txt](https://github.com/JimmXinu/FanFicFare/files/3882624/tmpvdgpy1.txt)

**Comment by JimmXinu** [comment]
[One chapter](https://www.mediaminer.org/fanfic/c/ranma-1-2-fan-fiction-love-hina-fan-fiction-mahou-sensei-negima-fan-fiction/coming-home-to-roost/145320/545612) of that story has some bad encoding in it--I can see `Ranma�fs cursed form` in browser, for example.

The error occurs in the `max_zalgo` processing.  If you turn that off, it works fine.

However, it should fail more safely.  I'll add some code to ignore `max_zalgo` processing failures.

(Thanks for including the story URL and debug log--I wouldn't have seen the problem otherwise.)

**Comment by JimmXinu** [comment]
[New Test Version posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2)
