### ISSUE TITLE
Literotica Duplicates Stories

### ISSUE THREAD

**Issue by daggerin** [JimmXinu/FanFicFare#461]
When using FFF to download from Literotica I have been getting duplicates, and I finally decided to figure out why. It's not too complicated. Stories resolve the first chapter URL, but don't use that resolved URL to check against already downloaded stories, they use the one that was put in the download window. 

Essentially this story:
https://www.literotica.com/s/a-world-for-the-taking-ch-01
will download chapters all the way to chapter 09 (current end of the 'book'), which is prefered behaviour. However if you input https://www.literotica.com/s/a-world-for-the-taking-ch-09 it downloads as a new book with 'https://www.literotica.com/s/a-world-for-the-taking-ch-01' as the URL. You can even start them at the same time and they don't see each other as duplicates, even though the end result is the exact same story, chapter and URL ID.

Thank you for the wonderful product.

**Comment by JimmXinu** [comment]
Since you don't say, I assume you're using the Calibre plugin.

Literotica doesn't normalize their story URLs.  Arguably, they don't have such a thing as a 'story' URL, only chapter URLs and author URLs.  

It's not as simple as "Change ch-09 to ch-01".  For example look at the chapter URLs for stories following this one: https://www.literotica.com/s/an-eternity-in-bonds-00-prelude

What FFF is using as the 'canonical' story URL is the first chapter URL after it's looked up the chapter list from the author page.  So there's at least two network requests just to get the canonical story URL for sure.  And FFF is designed to not do network requests early on due to efficiency reasons.

I agree that when given the ch-01 and ch-09 URLs at the same time, FFF can't figure out that they are the same and will download it twice.

However, if you already have the story in your library, when you tell it to update/download with the ch-09 URL, FFF *does* figure it out for me (because it had to get the chapter list to compare to for update).

I'm not sure I can make it any better than that with the limitations of Literotica I've seen.

**Comment by daggerin** [comment]
First, yes I'm using the Calibre plugin. 
Next, I'm not a programmer, and I understand some, but not how it all works.
Is this not a option, or is it just to complicated to modify/program? 
It may be too complicated to fix, but I just assumed since FFF checks the Calibre database for matches that it could check once it had (sort of) 'normalized' (IE retrieved the URL of the first chapter of the story) the URL. I don't know how the progression of commands\instructions(?) are written, but could they be modified so that in specific instances (IE literotica) it delays the database check until it's retrieved the first chapter URL or maybe checks twice (once it's retrieved then it checks a second time)?

**Comment by JimmXinu** [comment]
When exactly is this happening for you?  

Because FFF does check the DB after fetching metadata (IE, the chapter list etc).

The only case I've seen is when giving more than one chapter URL in the same story (as new story URL) at the same time.  Which hasn't come up before because most sites' URLs can be normalized without network reqs.

I might be able to add a de-dup'ing step for that, but I need to see any other cases before I can address them.

**Comment by daggerin** [comment]
Anytime I add a link that's NOT the first chapter. Not just if I add 2 at the same time. So if I've downloaded https://www.literotica.com/s/a-world-for-the-taking-ch-01 and then a few minutes/weeks/months later I try adding  https://www.literotica.com/s/a-world-for-the-taking-ch-09  then I get a duplicate story... although when it downloads the story it adds it with https://www.literotica.com/s/a-world-for-the-taking-ch-01 as the identifying url. When I pointed out that it could be done at the same time it was just something I noticed when I was trying to figure out what the problem was.

**Comment by JimmXinu** [comment]
Okay, I think I see what's happening.  When I run it, it's matching by title/author, not URL.  You must have the "Search by Title/Author(s) for If Story Already Exists?" option off, or the title changed.

It *is* checking for URL match just before that, but using the originally entered URL, not the retrieved one.  Which I can fix.  

Test version in [the usual place](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).

**Comment by daggerin** [comment]
I do have it unchecked, I recall it overwriting a story or two I was keeping 2 versions of, and it drove me nuts, so I had turned it off. There was something else too, but I don't remember off the top of my head what it was. Anyway, checked the test version and it seems to have fixed the major issue I was having. I don't think I ever put the story in the downloads twice, but if I do I know how to find/delete them. Thanks for the time and effort.
