### ISSUE TITLE
Adding support for portkey-archive.org

### ISSUE THREAD

**Issue by arisboch** [JimmXinu/FanFicFare#462]
Now that PortKey is dead, it'd be nice if I could download stories from the archive using this program; Here are a few examples:

https://www.portkey-archive.org/story/5952
https://www.portkey-archive.org/story/5717
https://www.portkey-archive.org/story/4753

**Comment by JimmXinu** [comment]
On the one hand, that is a self-declared read-only archive that already offers ebook download in several flavors.  So FFF's primary functions(IMO)--generate ebooks and allow for updates to ebooks without complete re-download--are both negated. 

OTOH, the fact that the site provides--and announces--a pretty complete looking JSON API raises my interest.

**Comment by JimmXinu** [comment]
I've looked at this again and found that the [API page](https://www.portkey-archive.org/api) also says:

> Please don't use this for big bulk downloads - the whole database is available to [download](https://www.portkey-archive.org/download).

And the whole download (as epubs) is only 245 MB.

Plus the JSON API causes at least one issue with FFF's paradigm--there isn't a chapter list without including all the chapter texts.  I could work around that by faking a chapter list--chapter count is available.  But only because this site is supposed to be permanently static.

I won't close this issue just yet, but I'm leaning more towards not adding support for it right now.

**Comment by JimmXinu** [comment]
Closing issue as not interesting for FFF for reasons given above.

**Comment by arisboch** [comment]
;-(
