### ISSUE TITLE
Request for hpfanfictalk.com archive stories

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#465]
The URLs are

* http://archive.hpfanfictalk.com/viewstory.php?sid=721&ageconsent=ok&warning=3
* http://archive.hpfanfictalk.com/viewstory.php?sid=3134

I hoped they offer some download, but it doesn't seem so (at least I haven't found anything).

**Comment by JimmXinu** [comment]
On the one hand, this is theoretically easy--it's an eFiction site and we have common code for scraping the print page from eFiction sites.

OTOH, this site has some problems:
- They choose to set `margins:0` on `<p>` tags (indeed, on _all_ tags), which means authors need to include style or extra newline/spacing tags to compensate.  Not insurmountable, but a nuisance because it means site-specific CSS and including style attrs from source which reduces FFF's normalization of output.  Can be addressed in ini settings.

- The print page version doesn't contain all the metadata and is formatted differently, preventing proper parsing of even the data that is there.  So metadata is minimal, practically non-existent.

- Not a direct problem, but possibly indicative, the obvious *Most Recent* and *Featured Stories* on the right of each page aren't actually links...

I could give you a marginally working adapter for this quickly, but not a good adapter; that would take longer.  I will look into further if this something you'd use.

**Comment by mcepl** [comment]
>     * They choose to set `margins:0` on `<p>` tags (indeed, on _all_ tags), which means authors need to include style or extra newline/spacing tags to compensate.  Not insurmountable, but a nuisance because it means site-specific CSS and including style attrs from source which reduces FFF's normalization of output.  Can be addressed in ini settings.

I know you probably don’t like additional dependencies (nobody likes them), but if the file was first processed by something like ``tidy -clean -ashtml``? [The resulting HTML](https://github.com/JimmXinu/FanFicFare/files/4154752/Irrational.html.zip) looks rather reasonably.

>     * Not a direct problem, but possibly indicative, the obvious _Most Recent_ and _Featured Stories_ on the right of each page aren't actually links...

Yes, I noticed.

> I could give you a marginally working adapter for this quickly, but not a good adapter; that would take longer. I will look into further if this something you'd use.

I think at least the basic adapter would be helpful, so I would have something to play with.

**Comment by JimmXinu** [comment]
I believe you are a CLI user?  I've uploaded v3.15.7 with eFiction Base for this site to testpypi.

**Comment by mcepl** [comment]
Works for me. Thank you. And yes, metadata are really poor. Where is the code? I cannot find v3.15.7 tag here on Github.

**Comment by JimmXinu** [comment]
I hadn't pushed it into git, but here's [the branch now](https://github.com/JimmXinu/FanFicFare/tree/adapter_archivehpfanfictalkcom).  The [adapter](https://github.com/JimmXinu/FanFicFare/blob/adapter_archivehpfanfictalkcom/fanficfare/adapters/adapter_archivehpfanfictalkcom.py) just calls [base_efiction](https://github.com/JimmXinu/FanFicFare/blob/adapter_archivehpfanfictalkcom/fanficfare/adapters/base_efiction_adapter.py).

I would probably switch to site specific code. copying from an [adapter like this one](https://github.com/JimmXinu/FanFicFare/blob/adapter_archivehpfanfictalkcom/fanficfare/adapters/adapter_efictionestelielde.py) (choosen pretty much at random--we have several eFiction that don't use base_efiction for different reasons).

**Comment by mcepl** [comment]
Hmm, so I suppose the key is to subclass method ``BaseEfictionAdapter.extractChapterUrlsAndMetadata``, right? (which is truly ugly piece of code, if I may say so).

So, if I want to add let’s say characters, how can I do it, given I have this nice piece of HTML:
```html
<span class="" label="Characters">
    <b>Characters:</b>
    <a href="browse.php?type=characters&amp;charid=366">Andromeda Black Tonks</a>,
    <a href="browse.php?type=characters&amp;charid=339">Arthur Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=341">Bill Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=342">Charlie Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=389">Fleur Delacour</a>,
    <a href="browse.php?type=characters&amp;charid=346">George Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=347">Ginny Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=432">Granger (Mr.)</a>,
    <a href="browse.php?type=characters&amp;charid=433">Granger (Mrs.)</a>,
    <a href="browse.php?type=characters&amp;charid=299">Harry Potter</a>,
    <a href="browse.php?type=characters&amp;charid=253">Hermione Granger</a>,
    <a href="browse.php?type=characters&amp;charid=320">Kingsley Shacklebolt</a>,
    <a href="browse.php?type=characters&amp;charid=266">Kreacher</a>,
    <a href="browse.php?type=characters&amp;charid=274">Luna Lovegood</a>,
    <a href="browse.php?type=characters&amp;charid=282">Minerva McGonagall</a>,
    <a href="browse.php?type=characters&amp;charid=350">Molly Weasley I</a>,
    <a href="browse.php?type=characters&amp;charid=273">Neville Longbottom</a>,
    <a href="browse.php?type=characters&amp;charid=352">Percy Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=321">Rita Skeeter</a>,
    <a href="browse.php?type=characters&amp;charid=353">Ron Weasley</a>,
    <a href="browse.php?type=characters&amp;charid=259">Rubeus Hagrid</a>,
    <a href="browse.php?type=characters&amp;charid=277">Teddy Lupin</a>
</span>
```
I guess we are based on the [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/), right? So, I need to find somewhere a place, where I could use ``.find_all(‘span’, label="Characters").find_all('a')`` and then go in the iterator to get values of text, right? Where?

**Comment by JimmXinu** [comment]
I wouldn't try to subclass BaseEfictionAdapter.  I would copy one of the other, non-base_efiction, adapters if I wanted to implement it with more metadata.  adapter_efictionestelielde.py was the example I gave.

Yes, FFF uses Beautiful Soup extensively.

You are basically correct about your parsing question, except we also commonly match the URL to be sure.  See: https://github.com/JimmXinu/FanFicFare/blob/f519641e6e3820071c448e9b44074824b8108507/fanficfare/adapters/adapter_efictionestelielde.py#L162

Feel free to work on it yourself if you want, or I will get around to it in a while.

**Comment by mcepl** [comment]
Here I have at least collected where the metadata may be found.

**Comment by mcepl** [comment]
> I wouldn't try to subclass BaseEfictionAdapter. I would copy one of the other, non-base_efiction, adapters if I wanted to implement it with more metadata. adapter_efictionestelielde.py was the example I gave.

But isn't it just a horrible [Copy and paste programming](https://en.wikipedia.org/wiki/Copy-and-paste_programming)?

**Comment by JimmXinu** [comment]
Yes, it is.  

Each eFiction site is enough different that creating common code for them is a nightmare.  

That's why base_efiction uses the print page--it's the least customized part of an eFiction install usually.  And it still can't handle all eFiction sites.  (FYI, I didn't write base_efiction, it was contributed by another dev, doe.  But I do appreciate and use doe's contribution.)

When base_efiction isn't good enough, I believe the advantages of copy-paste-modify programming _(quicker to learn for new users, simpler code, easier debugging, little chance of changes for one site breaking others)_ out weigh the disadvantages _(more setup for a new site, more code to maintain, duplicated functionality, larger memory foot print)_.

**Comment by JimmXinu** [comment]
I've uploaded v3.15.8 with custom code for this site to testpypi.

As mentioned, due to weird CSS choices by the site, `defaults.ini` contains:

```
[archive.hpfanfictalk.com]
## Some sites also require the user to confirm they are adult for
## adult content.  In commandline version, this should go in your
## personal.ini, not defaults.ini.
#is_adult:true

add_to_extra_valid_entries:,themes,inclusivity,house
themes_label:Themse
inclusivity_label:Inclusivity
house_label:HPFT Forum House

## archive.hpfanfictalk.com takes margins away, even from p tags, by
## default.  So authors have to either include extra br/p tags or
## their own styles.  These allow for both, but leave you at the mercy
## of author CSS.
add_to_output_css:
 * {
     margin: 0;
     padding: 0;
 }
add_to_keep_html_attrs:,style
```

**Comment by mcepl** [comment]
Looks very fine, thank you.
