### ISSUE TITLE
SB Author issues

### ISSUE THREAD

**Issue by Ryune** [JimmXinu/FanFicFare#473]
There was a recent mod post made in a thread that basically replaces all of the first posts of every page. This had the knock on effect of making FFF think that they were the thread's author. Any way to fix this?

https://forums.spacebattles.com/threads/inspired-voyage-st-voyager-si.791005/

**Comment by JimmXinu** [comment]
Hmmm.  Well, that's inconvenient.  This looks fixable, though.

There does appear to be a separate OP author tag available, but I have to go check each of the different support XF sites before I can use it reliably.

**Comment by JimmXinu** [comment]
Ugh.  Turns out for the 4 supported XF sites, I'd need 3 different sets of code for parsing the OP author directly (thanks, QQ).  Plus more code changes for post index vs threadmarks.

Instead, it looks easier to skip sticky posts when looking for the first post.

I don't suppose you have any other examples of sticky posts?  Especially on SV, AH and QQ?

**Comment by Ryune** [comment]
Unfortunately not. This is the first time I even saw it was possible to do something like that in thread.

**Comment by JimmXinu** [comment]
7e81930a56df9b965338052abc4ac03e9c1f5604

```
[base_xenforo2forum]
## ...

## Sometimes there's a sticky post first (often a Staff Post?) rather
## than the true first post by the Original Poster, AKA author.  By
## default, base_xenforo2forum will skip up to two sticky first posts.
## Configurable due to the extremely small sample size available when
## this was implemented.
skip_sticky_first_posts:true
```
