### ISSUE TITLE
Add favorite/review count for sites that support it

### ISSUE THREAD

**Issue by NightMachinary** [JimmXinu/FanFicFare#481]
Currently these info are recorded:
![9B412741-8B33-427A-9C03-45DA25BDEFAC](https://user-images.githubusercontent.com/36224762/78410992-66de5080-7623-11ea-988b-973bf5b0de5f.jpeg)

Also showing the number of reviews and favorites here is helpful, as a measure of popularity of the fic.

**Comment by JimmXinu** [comment]
FanFicFare already collects `reviews`, `favs`, and `follows` for fanfiction.net, they just aren't included in the title page by default because not everybody wants them.  

You can add them to the title page by putting this in your `personal.ini`:
```
[www.fanfiction.net]
extra_titlepage_entries:reviews,favs,follows
```

If you want them to appear higher up the list, you instead need to set `titlepage_entries`.  The default setting for epub is:
```
[epub]
## items to include in the title page
## Empty metadata entries will *not* appear, even if in the list.
## You can include extra text or HTML that will be included as-is in
## the title page. Eg: titlepage_entries: ...,<br />,summary,<br />,...
## All current formats already include title and author.
titlepage_entries: seriesHTML,category,genre,language,characters,ships,status,datePublished,dateUpdated,dateCreated,rating,warnings,numChapters,numWords,publisher,description
```

Not all sites have favs/reviews/etc in FFF, because they either aren't on the site or nobody's asked for them.  Consult `defaults.ini` and search for `extra_valid_entries` and `add_to_extra_valid_entries` to see what site-specific metadata is collected for each site.

**Comment by NightMachinary** [comment]
@JimmXinu Can I make fanficfare include all extra_valid_entries for any site?

**Comment by JimmXinu** [comment]
Only by adding the entries to `titlepage_entries` or `extra_titlepage_entries`.

But if you want a brute force include-everything, you could do something like this.  It's a list of all `extra_valid_entries` defined in `defaults.ini`.  Minus a few duplicates and sorted by name (not site) because that was the quickest way to remove identical entries.

```
[epub]
add_to_extra_titlepage_entries:,altTitles,authorLastLogin,averrating,awards,bodymodification,challenge,characters,codes,comment_count,comments,content,context,copyright,coverSourceHTML,crossoverfandom,disclaimer,dislikes,editor,era,eroticatags,events,fandoms,favorites,favs,featureditems,fileName,fileSize,followers,follows,forumtags,freeformtags,groupsHTML,growth,house,inclusivity,keyWords,language,likes,locale,mainCharactersAge,motivationforchange,native_status,newName,notes,notice,oldName,originHTML,pages,parentforums,personality,places,prequelHTML,readers,readings,reads,released,releaseFrequency,reviews,score,searchtags,sequelsHTML,sexualorientation,short_description,shrink,sitetags,size,sizeroles,snapeflavours,stars,storynotes,storytheme,storytype,subscribers,tags,tagsfromtitle,tagsfromtitledetect,takesplaces,themes,threadmarks_description,threadmarks_status,threadmarks_title,times,total_views,translator,turnedinto,type,typeofchange,universeHTML,upvotes,views,vote_rating,votes,warnings
```
