### ISSUE TITLE
Fancy Quotes in Tags

### ISSUE THREAD

**Issue by TheDammedGamer** [JimmXinu/FanFicFare#484]
Hi, 

I'm trying to modify a Tag using add_to_replace_metadata in the the claibre plugin's personal ini file, the issue is that I can't replace the fancy double quotes.

The tag is: Alastor “Mad-Eye” Moody

This is line i've been trying to use:
```
 ships_CHARS,characters=>Alastor (&quot;|&ldquo;)Mad-Eye(&quot;|&rdquo;) Moody=>Alastor Moody (HP)
```
Is there any way to reference theses quotes to strip them out?

Story URL for refence: https://archiveofourown.org/works/9517871/

Thanks

**Comment by JimmXinu** [comment]
Just including those characters works for me:

> replace_metadata:
>  ships_CHARS,characters=>Alastor (&quot;|&ldquo;|“)Mad-Eye(&quot;|&rdquo;|”) Moody=>Alastor Moody (HP)
> 

Most HTML entities (&code;) are converted to unicode characters during 
internal processing.  &lt; &lt; and &amp; are generally the only ones kept.

However, you might want to consider something more general, since your 
pattern won't match Alastor 'Madeye' Moody or other variations:

 > ships_CHARS,characters=>Alastor.*Moody=>Alastor Moody (HP)

**Comment by TheDammedGamer** [comment]
Thanks that worked, I was assuming everything was converted to XHTML. I did modify it slighlty so it would work if there are some variations:

`ships_CHARS,characters=>Alastor (.)Mad-Eye(.) Moody=>Alastor Moody (HP)`

Thanks
