### ISSUE TITLE
Failure to download -- Error 104 Connection Reset By Peer

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#491]
I have been having issues downloading some stories lately. I am using the most recent version of FanFicFare, as installed by the "update plugin" option in Calibre (Calibre 3.19.0).

I have had this happen with both the completed version of Mauling Snarks (https://forums.sufficientvelocity.com/threads/mauling-snarks-worm-complete.41471/) and also Dungeon Robotics (https://www.royalroad.com/fiction/21700/dungeon-robotics).

Can you let me know if this is unique to me or how to solve it? The "downloading metadata" window pops up, vanishes, the jobs icon spins for a few seconds, and after about half a minute this error message pops up with a "Nothing to update, bad jobs: 1" message.

Here is the results of the "copy to clipboard" option in the "view log" option that appears (is there a way to get better debug info on this sort of thing?):
Status
Title
Author
Comment
URL
Error
Unknown
Unknown
[Errno 104] Connection reset by peer
https://forums.sufficientvelocity.com/threads/mauling-snarks-worm-complete.41471/

Strangely, the old URL for Mauling Snarks still works: https://forums.sufficientvelocity.com/threads/mauling-snarks-worm.41471/
This redirects to the new URL, and it's now only really accessible through the new one, but somehow the program still works with it. Perhaps this will help narrow it down.

**Comment by JimmXinu** [comment]
` [Errno 104] Connection reset by peer` is a network error.  It says basically that the server end explicitly chopped the connection.

Most of the time when we see this it's because the server has decided you're hitting them too often and have gone on some kind of a list of 'offenders' to get reduced access.  Usually because you're downloading lots of stories, especially long stories, or downloading and browsing at the same time on the site.

Once on such a list it frequently takes a few days of not doing lots of downloads to get off again.

You can often avoid that by setting a longer `slow_down_sleep_time` value in `personal.ini`.  Default for SV is 4 and 0.5 for royalroad.com

If this error _isn't_ the server throttling you, then it's a network issue outside FFF's control.

**Comment by rdragonrydr** [comment]
Ah, thanks. I was browsing at the time. Depending on chapter size, _I_ probably look a bit like a web spider...

Hadn't been doing any downloads before that, though, and I'm still not clear on why the URL thing fixed it, but that was probably it.
