### ISSUE TITLE
Spacebattles issues

### ISSUE THREAD

**Issue by Ryune** [JimmXinu/FanFicFare#500]
Getting a "HTTP Error 503: Service Temporarily Unavailable" every time I try to update anything from SB.

Test URL known bad: https://forums.spacebattles.com/threads/from-mortal-to-divinity-anime-x-over-worm-si-oc.843053/

Don't think if this is related to me getting DDoS protection pages from cloudfire every once and a while or not.

**Comment by JimmXinu** [comment]
It may well be.  I'm able to download that story fine.

I can't think of anything that I could do to help you.  That sort of problem, "HTTP Error 503: Service Temporarily Unavailable" is very much from the server, not FFF.  Whether it's because the server is truly having problems or dislikes you/your network for some reason, I can only guess.

**Comment by Ryune** [comment]
Yeah, seems something has changed with my VPN recently. Turned it off and was just fine downloading. Is there any way to manually futs with the timeout?

**Comment by JimmXinu** [comment]
From `defaults.ini`:
```
## number of seconds to sleep between calls to the story site.  May be
## useful if pulling large numbers of stories or if the site is slow.
slow_down_sleep_time:0.5

## How long to wait for each HTTP connection to finish.  Longer times
## are better for sites that are slow to respond.  Shorter times
## prevent excessive wait when your network or the site is down.
connect_timeout:60.0
```
