### ISSUE TITLE
Preventing FFF from Updating a Book (was Archiving my archives...?)

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#504]
I have in my possession (Calibre library) a number of stories marked 'complete.' They will never again see an update, as the author has made the monumental achievement (or possibly the mistake) of having finished writing it.  :D

To prevent my stories from being overwritten or deleted if the author removes the chapters to put on Amazon/B&N/Kobo, and to save bandwidth if I batch an update, is there a way of removing whatever method lets the FFF updater detect its downloaded stories to update them? I have tried clearing the "id" field (url:https://whatever.com/post?=01234) and editing the ebook itself using Calibre to remove the URLs in the title page. Unless I missed one, neither of these seem to be how FanFicFare marks downloadable stories.

I bring this up because I don't know what safety features exist in the app to preserve items in the downloaded copy that aren't in the posted version. I have once seen the name of a chapter of a SV archive change on its own when the upstream version changed, rather than download the new "chapter," but that could be merely the result of the post ID being the same (if that's a thing). Still, nothing I can see protects me from someone "editing" a chapter to say "I have decided to quit writing because of a few of you complaining, or my leaving the fandom, or etc. Now no one shall ever see my work again!"

Is there a way of manually removing the URL, wherever it is stored, or better yet, flagging the story to be automatically skipped on update unless specifically requested?

**Comment by JimmXinu** [comment]
There are several things you can do to avoid that situation, and one feature that _can_ be used to block updates.

### Things you could do differently:
(FYI, unless told otherwise, I assume all users download to EPUB and use 'Update EPUB if New Chapters'.)

- On email update, FFF can't find the story to by URL update if the id field `url` is removed--unless you have the 'Search by Title/Author(s) for If Story Already Exists?' option checked.

- On manual update, FFF can't find the story URL update to if the id field `url` is removed--unless you have the 'Search inside ebooks for Story URL?' option checked.  

- If you are using email notices for updates, you can unsubscribe/unfollow that story.

- If you are using manual update, you can search for `not tags:Completed` before updating.
   (My views on ['Why shouldn't I just select my entire library and use FanFicFare plugin to check for updates?'](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-shouldnt-i-just-select-my-entire-library-and-use-fanficfare-plugin-to-check-for-updates) are already on record.)

FFF does not update a story with the same or fewer chapters when you use 'Update EPUB if New Chapters'.  And FFF reuses the existing chapter text in epub for each chapter--unless the chapter URL changes, which can happen depending on the site.  The chapter titles in the TOC are updated if different on the site.  Not an option, just an explanation.

### Existing Feature you can use:

Reject List.  
1. Select the books you want FFF to not update again.  
2. Do 'Get Story URLs from Selected Books', copy the list of story URLs
3. Open FFF config, click 'Add Reject URLs' button, right side of 'Basic' tab.
4. Paste in those story URLs. Then, in the bottom drop down, set the reason to 'Lock out Completed' or whatever.

Now when you try to update those, the reject list will trip and either prevent it or warn you, depending on your 'Reject Without Confirmation?' setting.

You can actually _more_ easily do that by selecting the books and using FFF's 'Reject Selected Books' feature; that would also save the title/author in the reject list.  But I personally have that shortcut'ed to the `Del` key and the 'Delete on Reject by Default?' setting turned on.  I fear that I would delete the books by accident.

The only real limitation is that there isn't a good way to map back from the reject list to books in the library.  But rejecting already-rejected books again will show you their existing reject entry.

Adding a special tag or something instead, while possible, duplicates a lot of what reject list does and would be somewhat complex.

**Comment by rdragonrydr** [comment]
Okay, that sounds workable, but one of my original issues remains:

I have removed the url ID, though, and 'look inside ebook for story url' is NOT checked, but it still finds it somehow. Would you have any idea why?

**Comment by JimmXinu** [comment]
Hmmm.  My apologies, I had forgotten some of the details.

First, I assume that we are talking about manually selecting books and hitting 'Update Existing FFF Books'.

There's actually three different ways FFF can find a story URL from an epub in that case:
1. From a Calibre routine that reads the epub metadata, especially Calibre's own embedded metadata.
1. From an FFF routine that reads the `dc:source` metadata in the epub (as written by FFF).
1. From an FFF routine that searches the actual ebook text for valid story URLs.  Usually present in FFF's title page and can be used on HTML and TXT formats, too.

Only the third one is currently controlled by the 'Search inside ebooks for Story URL?' option.  The first two can be defeated by using Polish or Modify Epub to update the metadata in the epub after removing the url id from Calibre.

I've been deleting `identifier:url` myself to prevent updates (generally also changing title and frequently leaving a different book with the same story URL).  But because I use email notices to drive updates, it works fine.

As I recall, steps one and two above are in place for the benefit of users importing epubs from different computers/libraries or from previous CLI downloads.  It's relatively certain the _metadata_ source URL/id is correct.  Searching the text for story URL is optional because it's less certain and takes longer.

So while it's not a huge change to apply 'Search inside ebooks for Story URL?' to all three methods, it is a change to the current behavior that I'm a bit reluctant to make.

Since we are talking about manually selecting stories to update, I don't think it's a huge impediment to ask you, the user, to restrict your book list with a search, say `identifiers:=url:false`, before hitting update.

**Comment by rdragonrydr** [comment]
Can you give details on how to use those tools to remove the URL info, then? (and what they are, if they aren't part of Calibre)

**Comment by JimmXinu** [comment]
Polish Book is a Calibre built-in feature.  I don't think it's easily visible by default, but the hotkey `p` calls it up by default.  Third checkbox down is 'Update metadata in the book files'.

Modify Epub is a plugin available the usual way, checkbox in lower right corner, 'Update metadata'.  Modify Epub predates the builtin Polish feature; for this purpose, I don't know of any difference between the two.

If this is something you do regularly, you could use a Saved Search to remember it for you.  Or a Virtual Library.  Or heck, moving those stories to a different library entirely.
