### ISSUE TITLE
scribblehub.com covers datePublished not collected

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#509]
@mavi0, can you take a look at the cover image part of this?

https://www.mobileread.com/forums/showthread.php?p=4013114&postcount=4326

Also, I noticed that the adapter doesn't collect `datePublished`.  If nothing else, it can be approximated by using the date on the first chapter.

**Comment by mavi0** [comment]
Sure, I totally forgot about cover art, there's a div on the site with the image so it's super easy to do - I'll get that added.

**Comment by JimmXinu** [comment]
Great, thanks.

Also something about rating, maybe?

https://www.mobileread.com/forums/showpost.php?p=4013154&postcount=4330

**Comment by mavi0** [comment]
Hmm, the site doesn't have ratings but it does have content warnings which it already scrapes. If there's content warnings I could set `self.story.setMetadata('rating')` to "Mature" and if not "Teen"? There's the Mature genre tag AndersW mentiond, but it doesn't seem to be as reliable as looking for content warnings 😔

**Comment by JimmXinu** [comment]
Hmmm. I didn’t really look at what they were asking about.  Not all warnings are worth a “mature”, IMO.  Like “strong language”.

I’d say since there isn’t a rating on the site, it’s not up to us to create one.

**Comment by mavi0** [comment]
Fairs, they have a mature and adult genre tag, I'll just set the rating to whichever is present (or if both are, adult) and leave the default teen as there isn't a teen tag?

**Comment by JimmXinu** [comment]
As you like. I’d be more inclined to leave rating empty, or use “Not Rated” or something instead of defaulting to Teen.  But I’ve no idea what the content level is like on that site.

**Comment by mavi0** [comment]
Okey dokes, the only other thing is `datePublished` is something I avoided because the date when the first chapter was published is only shown in the table of contents preview... but that's by default ordered by decending order (so most recent chapter first) and it's limited to 15 chapters by default, so if the story is over 15 chapters it won't pick up chapter 1. To get it to return the html list from the begininng it need a cookie like the screenshot, but I feel like that's a bit of a pain. Is it okay to leave it out, or maybe set it to the "lastUpdated" date?
![image](https://user-images.githubusercontent.com/16945326/87821901-7f881480-c868-11ea-99a2-569f50fb0bac.png)

**Comment by JimmXinu** [comment]
`adapter_fimfictionnet.py` has an example of setting a cookie if you want to explore it.

Ultimately you're the one doing it, so it's your choice.  But I'd leave `datePublished` empty before setting it to a known incorrect value.  There are a handful of existing adapters without `datePublished`.

**Comment by mavi0** [comment]
Fab I'll give it a go :)

**Comment by JimmXinu** [comment]
Closed by #510
