### ISSUE TITLE
Reprocess metadata without fetch?

### ISSUE THREAD

**Issue by inklesspen** [JimmXinu/FanFicFare#519]
I added a custom column in Calibre and assigned "Words" to go in the column. However, all previously-fetched fics don't yet have a value for this column.

Since the wordcount is present in the fetched epub, is there any good scriptable way to update the custom column in Calibre?

**Comment by JimmXinu** [comment]
No, there isn't anything in FFF to read metadata back from inside ebooks.  Output is very configurable and there's no guarantee any particular user has any particular metadata.

If you previously set up the 'Saved Metadata Column' you can use the 'Update Calibre Metadata from Saved Metadata Column' mode.  Otherwise, you can use 'Update Calibre Metadata from Web Site'.  But I'd set up 'Saved Metadata Column' first, if you do that, then you'll have it next time.
