### ISSUE TITLE
Help with workflow

### ISSUE THREAD

**Issue by Cupbox** [JimmXinu/FanFicFare#524]
Hello.
I use the following schema to track updates in any webfiction I read
A read column (tick/cross)
Reading Status (Unread,Planned,Reading,Read,Dropped)
Chapter Progress (I mark the exact chapter I'm reading and compare it to the chapters column that fanficfare updates.)

My workflow on reading a book
Mark the read column in calibre companion.
Sync it back to calibre
Open an autopopulated reading list (#read:true not #rd_status:"=Read")
Mark the above read.
Using regex to fill chapter value into the chapter progress value.

Workflow on updating fanficfare and marking books for reading.
Update fics using Fanficfare
**B**:Filter the books on reading status (If Reading Status column is marked Read then mark it as planned and reset Read column to false)
Sync to calibre companion.

I would like to automate a few aspects of this.
1: Automatically updating Reading Status based on Read Column (when I mark a book as true the reading status is updated to read) and updating the chapter progress to the most recent chapter.
2: Adding to reading list based on conditionals (See B above.) and allowing a single reading list to perform multiple actions (Marking as planned and resetting Read column)

I'd appreciate any help in this.

**Comment by JimmXinu** [comment]
FFF has features for:
- Marking new chapters in updated epubs inside the epub (in personal.ini set, `mark_new_chapters:true`).
- Adding newly downloaded/updated books to Reading Lists to indicate 'To Read'.  (FFF plugin config, Reading Lists tab)
- Adding newly downloaded/updated books to Reading Lists for 'Send to Devices'.  
   Reading Lists can be configured to set a custom column value as well as auto-sync to devices.
- Marking a book 'Read', that is, remove it from the 'To Read' lists and re-add it to the 'Send to Devices' list(s) while (optionally) 'Unnewing' aka, removing new chapter markings inside the epub.

There's a somewhat dated, but still relevant [Wiki page on setting up the Reading Lists part](https://github.com/JimmXinu/FanFicFare/wiki/PluginWithReadingList).

You will have to decide for yourself how much of this helps with your procedure, or if you want to change your procedure to more closely match what FFF provides.

The [FFF plugin forum thread](https://www.mobileread.com/forums/showthread.php?t=259221) is a better place for this discussion so that other users can also add their suggestions.
