### ISSUE TITLE
De-duplicate downloaded images (mostly for fiction.live)

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [JimmXinu/FanFicFare#550]
`fiction.live` stories often have duplicate images in the downloaded epub, as every uploaded image will always receive a new URL, preventing simple deduping. If an author repeatedly reuses images this can significantly bloat the ebook.

Although they don't have the same URL, identical images will be byte-for-byte identical even after FanFicFare/Calibre image processing (resizing, grayscaling). Duplicates can therefore be detected by use of a fast cryptographic hash and only one copy kept in the ebook, all other sources rewritten to point to it.

This isn't by any means critical to supporting F.L, but it's nice to have smaller ebooks.

(I have an only-partly-functional F.L downloader written in Rust and I do this to keep sizes down; I use the BLAKE2 hash since it is fast and its length is configurable. Thanks for FanFicFare, it's the only way I read fanfics now.)

**Comment by JimmXinu** [comment]
Can you provide a few examples?  Are you talking about saving a few bytes?  A few K?  M?

Most of time, this would be a waste of processing--how many sites/stories have a significant number of duplicate images with different URLs?

Plus, this is a general problem, not unique to FanFicFare or even epub.  And if _zip_ doesn't detect and collapse duplicate files, why should FanFicFare?  (FFF does already recognize when the same image URL is used more than once, even across updates.)

But I'm going not to reject the idea out of hand, because it's a moderately interesting problem.  

Depending on the data set, I'd be inclined to start with a simple data length comparison and maybe just do direct comparisons since it's already all in memory.  Or only hashing on length collision.  Except for bitmaps, it seems unlikely to me that images would have the same length very often.

If implemented, this would definitely be an optional feature that defaults to 'off'.

**Comment by AlyoshaVasilieva** [comment]
Size saved depends on the story. To test I grabbed some stories from F.L using FFF and manually removed duplicate images (note I have a larger-than-default image_max_size):

|Story|Initial size|De-duplicated size|
|-|-|-|
|[Star Wars: The Chosen](https://fiction.live/stories/Star-Wars-The-Chosen/phgkJGLSq39BxMnou)|7.01MB|6.02MB|
|[Your Hero Academia](https://fiction.live/stories/Your-Hero-Academia-Unbreakable/nyk8yBc3BizKaiC3d)|7.4MB|No duplicates|
|[A Shadow Resides](https://fiction.live/stories/A-Shadow-Resides-A-Raven-s-Operator-Quest/BDsdgTADKmNqzvmqP)|27.9MB|23.4MB|
|[Fate/Grand Quest](https://fiction.live/stories/Fate-Grand-Quest/WSqYHFxdbasEpMKH5)|28.6MB|25.1MB|
|[Dictator Quest](https://fiction.live/stories/Dictator-Quest/zY9wJFwKqNDXAp98p)|10.8MB|10.6MB|
|[EUN-1CE](https://fiction.live/stories/EUN-1CE/rFZHwP4wvoudmNrpm)|4.33MB|4.11MB|

Entirely possible it's more effort than is worth it, especially since every other site I'm aware of either doesn't use images or expects users to provide their own hosting (leading to identical URLs).

**Comment by JimmXinu** [comment]
I've added the setting `dedup_img_files` (defaults to `false`).  Set it `true` in your `personal.ini` to try it out.

**Comment by AlyoshaVasilieva** [comment]
Thanks a ton! Appears to be working fine so far and now the F.L ebooks are smaller.
