### ISSUE TITLE
Fiction.live email update issue @HazelSh

### ISSUE THREAD

**Issue by Ryune** [JimmXinu/FanFicFare#559]
So I'm currently having issues with email notifications for Fiction.live. When you do your initial download you end up with a url that isn't present in the email notification.

Initial URL: https://fiction.live/stories/Card-games-Upon-Mars-A-Soul-Master-Story-/Lq24g9xLuyfThqhsT/home
Email Update URL: http://fiction.live/stories/card-games-upon-mars-a-soul-master-story/Lq24g9xLuyfThqhsT

and finally, the URL for individual chapters is:
https://fiction.live/stories/card-games-upon-mars-a-soul-master-story/Lq24g9xLuyfThqhsT/Training-Days/EG7hmZXFu3TLdKJkT

Is there any way to set it so that any Fiction.live URL just cuts off that last bit? The only part of it that is useful for the downloader is: http://fiction.live/stories/card-games-upon-mars-a-soul-master-story/Lq24g9xLuyfThqhsT

**Comment by JimmXinu** [comment]
I'm not sure if GitHub will notify users about a mention in an issue title, but it does work in the comments.
@HazelSh, could you look at this?

**Comment by Ryune** [comment]
Oops, Sorry about that. Don't use github terribly much...

**Comment by HazelSh** [comment]
Can confirm, didn't get a notification for mention in the title.

I'm not totally clear on what the issue is, or how to resolve it. I don't use fanficfare email notification downloads, nor email updates from fiction.live, so I'm not familiar with how they work. Both URLs click through to the story, and both should work in fanficfare for downloading that story. 

How/where does fanficfare fail? What were you expecting, and what happened instead?

**Comment by JimmXinu** [comment]
#### Normalizing Story URLs
I agree that I see both story URLs working.  But they are different and can lead FFF to download them as two different stories (I didn't understand that's @Ryune meant at first either).  It would be nice if we could recognize that both are the same story (despite differences in letter case, Card vs card).  

Rather than just saving the story URL given, we commonly parse out the storyID and reconstruct the story URL so they match as much as possible.  `grep` for `_setURL` in the adapters dir for examples.

I'd suggest lowercasing everything in the story title part may work, but I'm not sure about that trailing `-`. I think it's from the `)` in the title _Card-games Upon Mars (A Soul Master Story)_.  Would the same thing happen with a leading `(` in the title?  Do we even have a way to know?

The most brute force way would be removing the title part all together, like: https://fiction.live/stories//Lq24g9xLuyfThqhsT (note the `//`).  We do that with other sites (like `adapter_tthfanficorg.py`), but they have the title at the end, not in the middle.

Ultimately, it's not our fault that fiction.live doesn't use the same URLs in email notices that it does on the site.  So if it is too complicated to deal with, we won't.  But at a minimum, we should be normalizing `http` to `https` and whether or not they end in `/home` (I'd remove it).

#### User Mitigation
@Ryune, have you tried turning on the _Search by Title/Author(s) for If Story Already Exists_ plugin option?  It will prompt you about changing the story URL if you have the _Check for changed Story URL_ option on or just change it otherwise.

#### Chapter URLs.
The chapter URLs, OTOH, could be recognized fairly easily by removing the `$` at the end of the `getSiteURLPattern()` pattern.  Like `/home`, the chapter part shouldn't be included the storyURL.

**Comment by Ryune** [comment]
Easiest mitigation I've found is to just download using the URL without the "/home" at the end of it or edit the metadata after the fact. It will then pick up the email. I made the mistake of forgetting that if you don't have new chapters FFF won't actually update the email even if you go through the prompt at the identification stage. Right now the best strategy I can come up with is to just police the URLs when I download a story. No different from downloading Xenforo stuff.

And yeah, when I specifically put in either URL it correctly identifies the story I want to update and asks to update the URL. Only issue was the email notifications not being picked up.

Though, now that I have that working... even though the story got updated with some new content it didn't update the story... I take it that the plugin only functions with new chapters and not new sections of chapters?

**Comment by JimmXinu** [comment]
> Though, now that I have that working... @HazelSh even though the story got updated with some new content it didn't update the story... I take it that the plugin only functions with new chapters and not new sections of chapters?
>
> (EDIT: Actually, thought about it a bit and honestly can't see how you could fix that without telling FFF to always update though. I'm downloading for archival purposes at the moment anyways so whatever...)

Correct.  Except that Update Always won't do it--you have to either Overwrite or manually delete the old chapter to get new sections in an existing chapter.  That's one of the reasons I was reluctant to support fiction.live in the first place.

**Comment by HazelSh** [comment]
> That's one of the reasons I was reluctant to support fiction.live in the first place.

Yeah, there's a slight mismatch with fanficfare's approach. Fanficfare expects chapters as the basic organizing block of a story, but fiction.live does sub-chapter 'chunks' which can be as short/frequent as the author likes. I've been using 'overwrite if newer' as the update mode for stories I follow week to week.

I'll add URL normalization. I'll look at transforming the title -- it might be similar to what happens with achievment IDs -- but I may just end up omitting it.

**Comment by HazelSh** [comment]
This is WIP -- have had other work, sorry. Give me a week or two.

**Comment by HazelSh** [comment]
I went with just ommitting the title, and that works even if it's a bit ugly.

**Comment by HazelSh** [comment]
I've also made a change in that should help with recognising updates to stories even when they're not publishing complete chapters.

**Comment by Ryune** [comment]
awesome, I'll check it out when I get the chance.

**Comment by JimmXinu** [comment]
Test versions out in the usual places.
