### ISSUE TITLE
personal.ini takes no effect

### ISSUE THREAD

**Issue by SomeRandomDude870** [JimmXinu/FanFicFare#571]
I am using FFF with Calibre 4.
After I configure the ini, I click twice at "OK" and sometimes I directly restart Calibre.

I am currently playing around with the personal.ini, but it seems as if no matter what I do nothing changes in the output epub.

ie:
"
extratags_label:test
extratags:muuuu"

If I add this I would expect that I will get new tags in the epub and in calibre, but nothing is added.
Or if I add:
"include_tocpage: true"
, I would expect to get an TOC page if there is more than one chapter, but no matter what. I don´t get one.

Also: In Literotica it only loads the Categories into Calibre tags (Mature, Couples), but not the tags of a Story. But those are inside the epub.

Do I missunderstand something or is here something wrong?

**Comment by JimmXinu** [comment]
Changes to FFF's `personal.ini` do not require calibre restart.

Changing `extratags_label` will generally only be visible if you've added `extratags` to `titlepage_entries`.  Some sites sections in `defaults.ini` clear `extratags` to get rid of the default 'FanFiction' value.  I'd have to see your `personal.ini` to know for sure what's going on.

`include_tocpage:true` needs to be under the heading `[epub]` in `personal.ini` or else the `defaults.ini:[epub]` setting will override `personal.ini:[defaults]` because `[epub]` is more specific than `[defaults]`.  See [wiki page](https://github.com/JimmXinu/FanFicFare/wiki/INI-File).

`[literotica.com]` has a site specific metadata entry `eroticatags`.  Add `add_to_include_subject_tags:,eroticatags` to `personal.ini` under `[literotica.com]` to add them to calibre's tags as well.

Nothing I've seen here is a problem in FFF, so I'm closing the issue.  There's a regular discussion forum for FFF plugin [here](https://www.mobileread.com/forums/showthread.php?t=259221).
