### ISSUE TITLE
Broken SpaceBattles

### ISSUE THREAD

**Issue by duplaja** [JimmXinu/FanFicFare#584]
Hello! I've been having issues with a particular Space Battles link (latest version of CLI fanficfare)

The link for the story is: https://forums.spacebattles.com/threads/going-native-dbz-dc-comics.789109/ ,
and it only appears to be pulling the first chapter (with no other errors thrown).

Thanks!

**Comment by JimmXinu** [comment]
Site changed.  Already fixed in test versions and previously reported in #576.  And #578.  And #579.  Going to leave this one open, see if it helps.

I will admit that I may not have remembered to update the CLI test version.  I didn't look, but I just ran it again.

> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by nsapa** [comment]
Did you also update the Calibre plugin?
I had the same issue before replacing ~/.config/calibre/plugins/FanFicFare.zip by the zip generated by makeplugin.py.

**Comment by JimmXinu** [comment]
I do official releases once a month.  T

est versions are uploaded more frequently at testpypi shown above and in [this post](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) in the plugin discussion thread.

**Comment by Rajvir8** [comment]
I'm having the same issue right now, glad to see that you left this open.  Was able to easily find it so that way I'm not opening up another issue mentioning the exact same thing.

That right now SB is only giving me the first chapter.

Thanks as always Jim for being so on the ball.

**Comment by Rajvir8** [comment]
Manually updating it to .14 fixed the issue for me.

Since I was a bit confused on how to do it and Googling it did not actually give me any actual guide.

I'll give a quick explanation here.

Download the Updated Version right above me that Jimm provided

Open up Calibre, go to Preferences - Change Calibre Behavior

Click Plugins under Advanced and then just click Load Plugin from file.

Very easy update overall, I was just looking in the wrong place myself as I kept going to the Plugin Update menu and looking for a way to add it from there.

**Comment by JimmXinu** [comment]
I've added an FAQ: [How do I get the latest test version of FanFicFare?](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#how-do-i-get-the-latest-test-version-of-fanficfare)

**Comment by duplaja** [comment]
Thank you very much, I appreciate all of your hard work!

**Comment by JimmXinu** [comment]
v3.25.0 released with fix for this.
