### ISSUE TITLE
AO3 conversion from pdf

### ISSUE THREAD

**Issue by JasCU100** [JimmXinu/FanFicFare#585]
Hi! I would like to ask if there is a way to convert downloaded PDF AO3 fics to epub where it could support updates? Unfortunately, I started downloading fics way before I knew fanficfare and I always downloaded them in PDF format. It eventually became a hassle to update them manually. I tried converting the pdfs to epub format and use get the story URLs from the selected books but it doesn't work. Thank you!

**Comment by JimmXinu** [comment]
FFF's epubs assume a certain file naming scheme, plus they have some hidden metadata that would be missing even if pdf->epub conversion worked better.

And in the case of AO3, the time savings would be small because FFF downloads the 'full work' page with all chapters unless you specifically turn off `use_view_full_work`.

If you are using the calibre plugin version of FFF, there's a checkbox in FFF's config (Basic tab, left side, toward the middle) for 'Search inside ebooks for Story URLs'.  If you have converted PDFs to text, html or epub, that should work for getting the story URL, at least.
