### ISSUE TITLE
Strange URLs when adding a new link

### ISSUE THREAD

**Issue by T-Man2000** [JimmXinu/FanFicFare#587]
I have a problem with adding new URLs. When I select "Download from URLs" the opening window behaves a bit strange. 

- If I copy & paste a URL from the browser, everything works normally.
- If I copy & paste a URL from the Firefox library, a "%0" is automatically added to the link at the end. Some adapters cannot handle this.
- If I drag & drop a URL, it looks like an html link. 

Example. https://imgur.com/a/Of26c5B

Can anyone reproduce a similar "strange" behavior?

Edit: I have the same problem with fanfiction.net. So it is not because of the website.

**Comment by JimmXinu** [comment]
Are you using the [latest test version](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2)?  Drag-n-drop got a bit buggy with python3 and I didn't realize (and fix) it until recently.

What is 'the Firefox library'?  Do you mean bookmarks?

**Comment by T-Man2000** [comment]
Yes, I am up-to-date. 
- calibre 5.4.2 [64bit]
- FanFicFare v3.24.15 (The test version of today)
- Firefox 83.0b9 (64-bit)

I mean the bookmarks.

Does the following part from the debug file help: https://pastebin.com/n7iUVYMM

**Comment by JimmXinu** [comment]
The `%0D` (which is Carriage Return, BTW) is being added by Firefox.  No idea why--it doesn't when you drag a URL from a page or from the location bar.  Or from Edge Favorites.

Arguably, this is a bug in Firefox, but I will add a check-and-remove for trailing `%0D` on dropped URLs.

I only see the dragged content appear as a 'link' when I select text and drag that instead of just the link--the drag-n-drop semantics are different.

However, accepting `text/html` and scanning it for story URLs is both easy and useful, so I'll add that, too.

**Comment by T-Man2000** [comment]
Thanks for looking at it and making an adjustment. 
I hope that Firefox still corrects the problem.

**Comment by JimmXinu** [comment]
[Test version posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).  Please advise if it that resolves your issues or not.

**Comment by T-Man2000** [comment]
The `%0D` is no longer included. The 'link' is still shown. But is not recognized by FFF anymore.

**Comment by JimmXinu** [comment]
Okay, you're going to have to describe in exact detail what you mean by "If I drag & drop a URL, it looks like an html link."  Because I don't see it.

From where?  What page, what link?  Using what browser (Firefox, I assume)? Do you have text selected at the time?

**Comment by T-Man2000** [comment]
I use Firefox 83.0b9 (64-bit) on a Windows 10 Pro Version 2004 on 64 bit with 32 GB RAM.

I use classic drag & drop under Windows. I click with the left mouse button on the entry in the library, keep the left mouse button pressed and drag the whole thing into the FFF. There I release the mouse button. 
https://imgur.com/a/MQfYmK6

Another test of mine shows another unusual "feature". If I mark several bookmarks in the library, they are added as one entry. 
https://imgur.com/a/5MquP62

If the problem is as suspected with Firefox, then I will wait until it is fixed. It doesn't make sense to spend a lot of time and effort on a bug in another program. But thanks, as you are willing to help here.

**Comment by JimmXinu** [comment]
I'm using Firefox 82.0.2 (64-bit), which reports it is the latest version, in Win10.  You appear to be using a developer/beta version.

I was dragging from the sidebar (opened by Ctrl-b), you appear to be using the separate window (presumably opened by Ctrl-shift-b).  I can only find a path to that window via keyboard shortcuts, either Ctrl-shift-b or alt-b, Show All Bookmarks.  (Which might suggest it is not a priority to Firefox.)

In both cases, when _dragging_ a bookmark with a valid story URL, FFF takes the story URL for me.  I only see a blue link-like text if the bookmark _doesn't_ contain a valid story URL.

The sidebar doesn't allow me to select multiple bookmarks.  In the 'Library' window, I can, but when dragged, only the first bookmark URL is carried over.  

Calibre dumps some very useful debugging data if you drag whatever over it.  Looking at it, Firefox doesn't correctly include all the bookmark URLs.  So I'm not seeing exactly what you do, but in both cases, it looks like Firefox isn't behaving quite correctly.

I confess that I read your first post too quickly and missed that you were talking about _copy-paste_ in the first two parts and _drag-n-drop_ only in the last.  If I copy-paste from bookmarks from either sidebar or 'Library' window, I do get a blue link-like text.  FFF doesn't do any special processing on *paste* anymore--that code was removed in 6925559f5f64ea8514cfc93b7962c720c3028996 to allow for more natural editing.

However, FFF _does_ apply special processing to clipboard contents when you _open_ "Download from URLs".  So copy first, then open "Download from URLs" works better.

Beyond that, I'm inclined to say that Firefox is doing weird stuff and be done.  Especially since we seem to be getting somewhat different results in different versions.

**Comment by JimmXinu** [comment]
Quoting from #584:
> Site changed. Already fixed in test versions and previously reported in #576. And #578. And #579. Going to leave this one open, see if it helps.

Apparently it doesn't.
