### ISSUE TITLE
Smilies don't show up from the Xenforo adapter?

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#596]
For quite some time now, I've noticed that smilies (usually in PHO "forum threads" in Worm stories) often don't appear at all or a blue "missing image" box shows up over them. I assume this is a known issue, but I didn't find anything in the wiki or closed issues, so maybe it isn't?

Is this a technical limitation where it would need JavaScript parsing or a library doesn't handle URLEncoding? Or does it just need updated? I did once try to find out where the smilies are stored and/or convert the encoded string, and didn't have any luck (there's only one that's actually a real URL anymore, I think), so I'm wondering if it might be esoteric.

pagecache(GET) MISS: https://forums.spacebattles.com/threads/camera-shy-worm-alt-power.685357/reader/page-1?threadmark_category=19
FFF: DEBUG: 2020-11-14 20:53:40,602: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1010): Encoding:utf8
FFF: DEBUG: 2020-11-14 20:53:41,255: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(672): Getting chapter text for: https://forums.spacebattles.com/posts/54727342/ index: 42
FFF: DEBUG: 2020-11-14 20:53:41,256: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(683): Using reader mode
FFF: DEBUG: 2020-11-14 20:53:41,256: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(703): post found in cache
FFF: DEBUG: 2020-11-14 20:53:41,289: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
FFF: INFO: 2020-11-14 20:53:51,544: calibre_plugins.fanficfare_plugin.fanficfare.story(1271): Failed to load or convert image, 
parent:https://forums.spacebattles.com/
skipping:https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
Exception: HTTP Error 404: Not Found
FFF: DEBUG: 2020-11-14 20:53:51,546: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
FFF: INFO: 2020-11-14 20:54:01,897: calibre_plugins.fanficfare_plugin.fanficfare.story(1271): Failed to load or convert image, 
parent:https://forums.spacebattles.com/
skipping:https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
Exception: HTTP Error 404: Not Found
FFF: DEBUG: 2020-11-14 20:54:01,900: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
FFF: INFO: 2020-11-14 20:54:12,162: calibre_plugins.fanficfare_plugin.fanficfare.story(1271): Failed to load or convert image, 
parent:https://forums.spacebattles.com/
skipping:https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
Exception: HTTP Error 404: Not Found
FFF: DEBUG: 2020-11-14 20:54:12,164: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
FFF: INFO: 2020-11-14 20:54:22,443: calibre_plugins.fanficfare_plugin.fanficfare.story(1271): Failed to load or convert image, 
parent:https://forums.spacebattles.com/
skipping:https://forums.spacebattles.com/data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
Exception: HTTP Error 404: Not Found

**Comment by JimmXinu** [comment]
From `defaults.ini`:
```
## SV & SB (and possibly QQ and AH) like to use sprite smilies --
## smiley images that are all in one image file for performance and
## are shown by CSS background with offsets.  Epub viewers don't like
## that.
##
## The sprite smiley img tags generally do have alt attributes that get
## the point across: ":)" ":D" ":(" ":lol" etc.  And not all smilies
## on these sites use sprite images, so some can be used as is.
##
## When replace_failed_smilies_with_alt_text:true, any images that
## failed to download or are src=clear.png *and* have a class containing
## mceSmilie and an alt attribute will be replaced with:
## <span class="(classes)">(alt text)</span>
##
## The smiley classes are preserved in case the user wants to do
## something special with them.
#replace_failed_smilies_with_alt_text:false
```
The in-line `data:image/gif` is single-pixel, likely transparent, while the real smiley comes from a sprite image in CSS.  I investigated including them before and couldn't make it work reliably, as I recall.  (I might, however, revisit it enough to stop trying to download them.)

It doesn't surprise me that you don't find anything if you're only looking on GitHub.  The vast majority of discussion about FFF happens in the [FanFicFare](https://www.mobileread.com/forums/showthread.php?t=259221) plugin thread.  Please go either there or the [FanFicFare maillist](https://groups.google.com/group/fanfic-downloader) for discussion and reserve opening issues for bug reports.

**Comment by JimmXinu** [comment]
I've been looking at this again and it has several layers to it.  I'm not saying it's impossible, but there are many issues to be considered.

1. Handling in-line `data:image/gif`
    1. I added code to just include them properly unchanged(12383b6342c987d97f48ee0886ad4de007b36e85).
    1. But that could be quite large and doesn't get image processing, so: code to convert them to files(0fa697b4185adce6979a625da59e9b66c355f1a6)
1. Cover: Now 1x1 transparent gif can become a cover--that's not good. Set a default `cover_min_size` value (0080310062740fc787f0411fd9ad22b852c36215)
1. JPG format
    Sprite smilies depend on transparent images with the real image in the background.
    1. FFF by default converts all images to JPG because 
        1. 10 years ago when I wrote that part, some ereaders didn't handle PNG correctly and 
        1. Calibre at the time didn't have image libraries to output PNG.
    1. JPG doesn't support transparency, and some ereaders didn't support transparency in other formats well, so FFF also defaults to `remove_transparency:true`.
1. Smilies Images / CSS Background images
    1. FFF supports 5 XenForo sites and while there is overlap, _none_ of them use exactly the smilies and CSS.
    1. Adjusting size of sprite smilies doesn't work--they rely on being an exact pixel size to work.  So can't scale for ereaders.
    1. Not all smilies are sprites.  Some are individual images, some are even unicode characters (or _images of_ unicode characters).  Which naturally are also different sizes.
    1. FFF as presently coded does not look at CSS for images to include.  Sprite smilies are defined in CSS.
1. `nook_img_fix`: 10 years ago, my primary ereader was Nook, and at the time, Nook handled `<img>` tags very poorly unless they had a `<p>` or `<div>` tag around them.  Thus, FFF has `nook_img_fix:true` which puts a `<div>` around any `<img>` that doesn't have one.  Which is hard on smilies that appear mid-text.  No idea if that's still needed or not.

I'm opening this issue again, since obviously I'm at least considering it.

**Comment by rdragonrydr** [comment]
Well, that's horrifying. I'm truly sorry for opening that can of worms, but would of course love it if that ends up working!

On the earlier topic, I will indeed go poke you over on the forum (sigh, need to make another login... :D) if something else like this comes up. 

And again it was something that I should have noticed if I read carefully through the settings file. _Facepalm_. Sorry about that...

I really appreciate your work on this. It's a huge convenience being able to archive a story without spending a full day copying into Libreoffice. It's saved my bacon quite a few times when an author has closed down their account.

**Comment by JimmXinu** [comment]
Some more notes on this thorny issue.

## Considered Solutions

### Include sprite smilies as used by the sites.
#### Pros:
1. Most 'faithful' to the source.
1. Sprites save some space by design--at least in theory--it depends how many appear.
#### Cons:
1. Having deal with all the issues above
1. Not all readers support them.  FBReader on Android, for example.
1. Images can't scale with text size--that I've found anyway, haven't looked very hard.

### Separate sprites into individual images, include as separate `<img>` tags without background image
#### Pros:
1. Least 'complex' solution, just `<img>` tags.
1. Should be most compatible and consistent across readers and devices.
1. Not having deal with _all_ the issues above
1. Should be able to scale with text size?  Haven't tested.
#### Cons:
1. Need to make 60-70? individual images from sprites.
1. Need to map sprite-smilie classes to images, and they're not necessarily the same on all sites.
1. Where would those image files come from on download?  Packaged with FFF?  On a server somewhere?

### Replace sprite smilies (and maybe all smilies?) with equivalent Unicode characters.
#### Pros:
1. Best space savings--no images files at all.
1. Not having deal with _any_ of the issues above.
#### Cons:
1. Not all readers support all, or sometimes any, Unicode characters.  Kindle Voyage and FBReader don't appear to support from brief testing.  **Kindle non-support basically makes this a non-starter.**
1. Not all smilies have exact Unicode character matches. 
1. Unicode characters often appear different between different devices.

### Replace sprite smilies with `alt` attribute text.  
**This is already implemented as `replace_failed_smilies_with_alt_text` optional setting.**
#### Pros:
1. Simple, and perhaps most importantly, _already done_.
1. Nearly best space savings--no images files at all, slightly more bytes
1. Not having deal with _any_ of the issues above.
#### Cons:
1. Graphical smilies become old-school emoticons such as `:)` `;)` `:D` `:p` etc, etc. Some become abbreviations such as `:lol:` `:confused:`  `:cool:` etc etc.  Or whatever else the site put in `alt`.

## Conclusion
This is crazy and it's not worth it.

As per my earlier comment, I added support for including in-line images correctly.  However, I've changed my mind on making them convert to image files by default.  Instead `convert_inline_images` will default to `false` in the next test version.  Otherwise, those 1x1 transparent gifs become opaque jpgs.

I am also strongly considering changing the default for `replace_failed_smilies_with_alt_text` to true for `[base_xenforoforum]`.

**Comment by rdragonrydr** [comment]
...I guess I can still comment on these?

My personal preference, for if you (or anyone else) adds this feature, would be to convert each image as seen on the page (from the CSS) to an image tag. It would need the CSS parsing to be added, at least to extract the offsets and the source sprite sheets, but that way the real images could just be dropped in place and would perfectly reflect the real ones (since, of course, they are the same). The transparent .gif could then just be dropped.

Maybe an exception for the "smilies" class or whatever when the parser hits an image with that class? That way, most images would process normally, but if someone added a smilie (the only way that class would end up on the rendered page), the special parser(s) would kick in.

I figure that not supporting it is fine (to some degree; I'm still going to end up with either broken images or awkward alt-text in weird spots) but _anything_ is better than converting everything to unicode. I find nothing more appalling than unicode smilies (not just on XF, mind) and was personally involved in the quest to bring back the Xenforo original ones. :D
--------
Alternately... (for the packaging case) is there a way to add a hook to the parser to detect those CSS tags that denote a smilie? Then you could just have it look for an associated image name in a folder (rather than do the whole parse-and-slice dance), and ask users to go find and link those images themselves (given some minimum detail on where that folder is, how to name the images, and where to find them themselves). Eventually I imagine someone would send a pull request and you could add a folder to the source/plugin that contains the commonly-used ones anyway. My personal preference is mostly for the main Xenforo original 20 or so, which are common to QQ, SB, and SV at minimum. The others aren't too common in stories that I've seen (maybe because they are really creepy).
