### ISSUE TITLE
Does txt download support markdown?

### ISSUE THREAD

**Issue by arbaazlaskar** [JimmXinu/FanFicFare#623]
This is not exactly an issue but more like a question. I needed to use txt file format of a fanfic for my project and wanted to know if fanficfare can download directly to both plain text and markdown txt files. Since as of now, i am downloading as epub and converting it to both plain text and markdown txt using calibre-cli. It would be more efficient if it was possible through fanficfare itself. Is this already possible?

**Comment by JimmXinu** [comment]
Hmmm.  As I recall, that part of FFF is basically older than my involvement with the project, ~10 years ago.

It looks like it uses the `html2text` package and just calls the `html2text()` method.  And it looks like `html2text` *does* do at least basic markdown.  So the answer is a cautious yes?  Try it and see if you like it.  (Fair warning: Unless something is actually broken, I'm not likely to be interested in changing it.  Code contributions usually welcome.)

FYI, the `html2text` packaged in the Calibre plugin version is 3 years old.  I don't expect to be able to update that due to older Calibre versions running Py2 still.

Plus, keep in mind that downloading to epub always has the advantage of being able to download updates without needing every chapter again.

**Comment by JimmXinu** [comment]
I'm going to assume this is adequately answered.

**Comment by arbaazlaskar** [comment]
What will be the command for the markdown txt download? Since using `fanficfare -f txt` will download it as plain text.
Is there a pre-existing command?
@JimmXinu

**Comment by JimmXinu** [comment]
The existing text output _is_ basic markdown.  Italics, bold, headers, etc.

**Comment by arbaazlaskar** [comment]
Yeah i just checked again. It _is_ very basic. I will mostly probably go with the epub+calibre convert to txt route. Thanks for all the help.
