### ISSUE TITLE
Webnovel Error

### ISSUE THREAD

**Issue by JasCU100** [JimmXinu/FanFicFare#632]
Hi! I'm having an error when updating novels from Webnovel. The comment says 'NoneType' object has no attribute 'find.' All links I have got this error. Hope it would be resolved. Thank you!

**Comment by HazelSh** [comment]
If you aren't already, try the most recent test version -- might already be fixed if it's the same as #629

**Comment by JimmXinu** [comment]
And #630.  I just checked--it's still fixed.  Please review recent issues before posting.  I will leave this one open for the higher visibility.

There are test versions with fixes up in the usual places.  Plugin [here](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2) and CLI in 
` pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare `

If you are still seeing this after trying the test versions, please also post a story URL that displays the problem.  Just because it happens for all the links you try doesn't mean it does for me.

**Comment by JasCU100** [comment]
Thank you!
