### ISSUE TITLE
TenhawkPresents failing

### ISSUE THREAD

**Issue by sanderson2000** [JimmXinu/FanFicFare#650]
I am unable to successfully download from http://fanfiction.tenhawkpresents.ink. I realize that this is a mostly dead site and do not class this as a priority issue. However, if a workaround is available I would appreciate knowing. Additionally, I am available via email if more information is needed or a tester is required for this issue.

Example URL: http://fanfiction.tenhawkpresents.ink/index.php

Sincerely,
Steven Anderson

**Comment by JimmXinu** [comment]
Some while back tenhawk moved.  There's both fanfiction.tenhawkpresents.ink and fanfic.tenhawkpresents.ink available.

fanfiction.tenhawkpresents.ink hasn't had any updates since 2018.  I assume that it was a a test site or an abandoned transfer.

fanfic.tenhawkpresents.ink was updated more recently (Jul 2020) and has more stories, so I assume it is the 'real' site and it is the one FFF supports.

However, from what I recall, the story numbers don't match between the two sites, or the previous site, so fanfic.tenhawkpresents.ink was implemented as a new site that doesn't share story URLs with what came before.

See:
http://fanfic.tenhawkpresents.ink/index.php
