### ISSUE TITLE
Bug on the newest Test Version

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#656]
I was getting the cloudflare error so I downloaded the 3.99.27 test version on CLI on my Windows 10, Python 3.7.
The url I was using is `https://www.fanfiction.net/s/11405694/[8-]`
The story was downloaded successfully but I got an error

> FFF: WARNING: 2021-02-11 19:20:57,158: adapter_fanfictionnet.py(153): Caught exception in check_next_chapter URL: https://www.fanfiction.net/s/11405694/11/Confrontation-II-the-Reckoning Exception cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available....".

The story is 10 chapters long and I have set `check_next_chapter:true` on personal.ini 
From what I understand, because of the above it checked for chapter 11 (which doesn't exist) and got the above error.

I used Chrome to go to `https://www.fanfiction.net/s/11405694/11/Confrontation-II-the-Reckoning` which would be the 'next' chapter and it didn't work. And neither did `https://www.fanfiction.net/s/11405694/11`

I don't think this is fixable because if the page does not exist then the cache wouldn't exist either. 
And because sometimes ffnet takes too long to add the latest chapter, the `check_next_chapter:true` is necessary for me
But it might be better to change the message printed in this case to make it obvious what the message is. So that the user can tell that the download was done correctly, but FFF couldn't check for the next chapter

**Comment by JimmXinu** [comment]
You are slightly incorrect.  If you go to a page off the end, the page from ffnet says it doesn't exist, but it does give an actual HTTP error.

So that 'error' page is cached. and should 'work' with the browser cache feature.

`check_next_chapter` is off by default and, personally, I have kept turned it off because ffnet's metadata hasn't been updating in a timely fashion lately so it doesn't actually help.
