### ISSUE TITLE
Download chapters individually [literotica] [hentai-foundry]

### ISSUE THREAD

**Issue by kesoy42840** [JimmXinu/FanFicFare#658]
Is it possible to download chapters individually from `literotica.com` and `hentai-foundry.com`?

Currently, all chapters of a fiction are downloaded into a single file (omnibus).
| read | title | author | series |
| --- | --- | --- | --- |
| ? | Some Series | thebestauthor | this is not populated |

I currently have a boolean calibre column marking whether a library entry has been read.
I would like to be able to download fictions such that each chapter is its own entry in a series, making it easier to pick up where I've left off.

| read | title | author | series |
| --- | --- | --- | --- |
| Y | foo | thebestauthor | Some Series [1] |
| n | bar | thebestauthor | Some Series [2] |

Please note that the second (desired) behavior is what happens on `archiveofourown.org`

**Comment by JimmXinu** [comment]
I don't see this issue in GitHub, so I'll try to reply by email.

You can download chapter ranges or individual chapters by putting [1-3] 
or [-3] or [3-] or [3] after the story URL when you first download it.

You could also use the EpubSplit plugin to quickly split chapters into 
separate books.

I am not interested in changing FFF to download individual chapters of a 
story to separate books.

**Comment by JimmXinu** [comment]
Oh hey, this issue did show up eventually.  For whatever reason, it wasn't visible to me in GitHub initially *and* I never got a notification email about your response.  Sorry I didn't notice it for so long.

Aside from fitting your particular reading habits, I really don't see any benefit to this for anyone else.

And I think you underestimate how much of a structural change it would be to download chapters as books--_especially_ in the face of updates.  Instead of checking one epub and adding new chapters, you'd have to add each chapter as a new book.  And it really breaks FFF's book-chapter paradigm.  

(What you are referring to in AO3 is a series of books, each containing chapters.  It's the author's call when to organize into chapters in a book or books in a series.)

If you really want to have individual chapters as separate books, I would suggest downloading and updating each story to one epub (keeping it for the next update) as FFF does naturally, then splitting and reading those separate chapter-books.  The EpubSplit plugin even has a button for splitting each selected chapter into a separate book.  Use different Virtual Libraries (or real Libraries) to partition the whole-books and chapter-books if you like.
