### ISSUE TITLE
Not issue but observation DL of fics is longer in new version 4.0

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#660]
DLing 3 stories off of SV and SB. the time it takes to DL Stories seems to have significantly Increased with the new version the 3 i'm working on now are 60% with it going for a half an hour.

edit: time to dl fics from these links:
https://forums.sufficientvelocity.com/threads/fate-sunny-order-fgo.43852/
https://forums.spacebattles.com/threads/my-huntsman-academia-rwby-mha-cross-quest.549311/
https://forums.spacebattles.com/threads/miraculous-escalation-worm-miraculous-ladybug.776197/

55mins 19 secs

**Comment by JimmXinu** [comment]
There are two changes that apply:

1. In past, XenForo(XF) sites including SB & SV, applied an 'extra sleep' time to chapter network requests, but not metadata network requests.  The 'extra sleep' function was removed during the FFF network layer rebuild because it added complexity and was only used by a few sites.  Instead, the default `slow_down_sleep_time` was raised by the same amount, which also affects metadata network requests.  Stories with tons of threadmarks may well see noticeable slow downs--especially on updates where most of the traffic will be threadmark lookups.

2. In past, FanFicFare Calibre Plugin launched 1 background process per download (limited to a pool of processes sized by Calibre BG process limit setting, usually == number of CPUs).  Version 4 FFF launches one BG process per _site_ instead to prevent parallel downloads on the same site.  This was primarily for ffnet, but serializes traffic for other sites as well.

You can use `personal.ini` settings to reduce `slow_down_sleep_time` for specific sites or `[base_xenforoforum]` in general if you like.  I'd be curious to see if you run into any troubles at lower settings (XF default is 6.0 seconds).  

I would _not_ suggest going lower than perhaps 2.0.  SB/SV approached me directly some time ago and asked for the delays, which I hardcoded as the 'extra sleep' function.  I'm trusting users to not abuse the ability to set their own sleep time.

**Comment by kyoam** [comment]
As much as I appreciate the suggestion for slow down sleep time I think I'll leave the settings as is. this is more a be minduful of how big the stories you are updating are (like only doing an update a month for the larger ones like huntsman academia) not over loading fff (3 to 4 fics at a time as opposed to one request of all fics updated that day [which could have been up to 30 on a heavy update schedule]) and planning time around the increased time the streamlining per site requested can add on more than fidiling around with the settings and possibly wrecking how fff works for me. but others like me who may have 15 to 20 fics between sb sv and qq updating a day might notice the slowdown and could have put it as an issue.

with this one written up and closed you can at least point to this and say "read it" before the user in question starts claiming fff is having slowdown issues.

Generally if the resulting html or epub of a fic is under 5mb it will go relatively quickly (maybe 5 mins at most per fic) above 5mb for the file (either through sheer text or additional images) and you might have it take longer than before ver 4.0.

its not a problem in my case but for other users it might be enough to mention it...
