### ISSUE TITLE
www.bdsmlibrary.com - Calibre crashes on missing author

### ISSUE THREAD

**Issue by albyofdoom** [JimmXinu/FanFicFare#696]
There are some stories on the site that are missing the author metadata. When attempting to download these, calibre fully exits with no warning or feedback when attempting to download metadata.

Examples: 
https://www.bdsmlibrary.com/stories/story.php?storyid=5028
https://www.bdsmlibrary.com/stories/story.php?storyid=5029

**Comment by JimmXinu** [comment]
Oh my.  It actually flat out calls `sys.exit()` in the adapter.  And that's been in the code for 5 years.  That's not good...

Instead of `adapter_bdsmlibrarycom.py` running it's own re-try loop _20 times_ (which doesn't work anyway because `use_basic_cache:true` is on by default), I'm going to change it to set author to Anonymous when none is found.

**Comment by JimmXinu** [comment]
Test versions posted in the usual places.
