### ISSUE TITLE
[bug]Fanficfare fails to download a specific sufficientvelocity story

### ISSUE THREAD

**Issue by jeancinq** [JimmXinu/FanFicFare#709]
With the calibre plugin version of Fanficfare, version 4.3.5 on Calibre version 5.21
Fanficfare repetedly fails to download a particular Sufficient Velocity story.
Specificaly it's this particular story : 
https://forums.sufficientvelocity.com/threads/the-lords-of-ruin-battletech-killzone.52819/
This happens whether it's the only downloaded story or if a batch is downloaded at the same time.
Other stories download fine when this one isn't in the batch, but this story makes the whole download process fails, including other stories downloaded with it.
Here is Calibre debug output for this problem: 
[calibre_debug_20062021.txt](https://github.com/JimmXinu/FanFicFare/files/6683136/calibre_debug_20062021.txt)

Thanks for any help with this.

**Comment by JimmXinu** [comment]
The problem was image https://cfw.sarna.net/wiki/images/c/c5/Tiverton_3151.svg?timestamp=20210317171843 from post https://forums.sufficientvelocity.com/posts/11937938/

Calibre's image processing library chokes badly on SVG images--killing the process rather than raising an exception properly.

We already had code to not try and convert img urls ending with `.svg`, but this image had `.svg?...`, which we will now look for.
