### ISSUE TITLE
[FR] Add CLI option to use an external program for downloading the HTTP pages

### ISSUE THREAD

**Issue by NightMachinary** [JimmXinu/FanFicFare#710]
Considering the issue with [Cloudflare](https://github.com/JimmXinu/FanFicFare/issues/703) has not abated, and even if it does go away, it will most likely recur, can you add a simple option `—external-downloader` so that we can just use our own solutions?

This option immediately solves a lot of problems (e.g., cookies, proxies, Cloudflare, ...), and doesn’t create a maintenance burden for you. 

I know this option would not work with fanficfare’s login features, but it doesn’t need to. We can assume the external downloader handles those on its own. (E.g., I personally will just reuse my Chrome’s cookies for logging in, but people can do whatever they want.)

**Comment by JimmXinu** [comment]
What is your example of an external downloader that works?

**Comment by NightMachinary** [comment]
@JimmXinu Both puppeteer and selenium seem to somewhat work, and I think, with selenium, one can just solve the captchas manually in the worst case, which is easier than opening a hundred chapters for the browser cache. And if anyone should actually pay for one of the premium services, they can also integrate that easily into fanficfare.

**Comment by JimmXinu** [comment]
Have you tried nsapa's fanfictionnet_ff_proxy? https://github.com/nsapa/fanfictionnet_ff_proxy

I really don't want to spend more of my time supporting solutions that "somewhat work".

**Comment by nsapa** [comment]
fanfictionnet_ff_proxy is Chrome + a runtime patch to kill navigator.webdriver + Selenium.
It currently works on fanfiction.net and it look like I've found the bug that truncated some page :)

**Comment by tom221-e** [comment]
hello why don't you use this:
https://github.com/FicHub/fichub-cli
this may be the solution

**Comment by JimmXinu** [comment]
https://github.com/FicHub/fichub-cli is a CLI frontend to the site https://fichub.net/ which is its own download and caching service.

I tried a couple fics, neither of which had all chapters available.  One just started recently and had been updated this morning (latest update missing), and one is several years old and updated after a long silence a couple weeks ago (new chapters missing, suggesting cache time is quite lengthy--possibly because fic was marked Completed but continued updating).

On the upside, it does look like fichub included most of the metadata in an Introduction page.

While this might be a viable option, the staleness of the cache is concerning.  I have little interest in explaining (over and over) why that is and why I can't fix it.

**Comment by iridescent-beacon** [comment]
> I have little interest in explaining (over and over) why that is and why I can't fix it.

I completely agree. I don't think it makes sense for fichub to be a backend for FanFicFare where users expect wildly different semantics. I get enough questions about how fichub works as it is without tossing in confused users of another tool :)  If anything, it may make sense to go the other direction and have fichub fallback to FanFicFare.

That being said I'm not sure either of those is what @tom221-e was suggesting, so much as they were suggesting just switching tools in the mean time. If they want to clarify and have suggestions on how the tools _could_ work together though I'm all ears, but don't have a lot of bandwidth for new features currently.

**Comment by JimmXinu** [comment]
For the time being I consider nsapa's [fanfictionnet_ff_proxy](https://github.com/nsapa/fanfictionnet_ff_proxy) to be the answer for this question.
