### ISSUE TITLE
Fimfiction downloads broken

### ISSUE THREAD

**Issue by diggit** [JimmXinu/FanFicFare#715]
Hi,
I've successfully used FFF with FimFiction in past.
Now it fails when I try to download FimFiction story, eg.: https://www.fimfiction.net/story/363399

Calibre 5.23.0
FFF 4.3.0
Archlinux (up to date, rolling release distro)
Python 3.9.6

This is copied Log output from Calibre:
```
Status
Title
Author
Comment
URL
Error
Unknown
Unknown
__init__() got an unexpected keyword argument 'other'
https://www.fimfiction.net/story/363399/
```

When trying CLI version:
```
fanficfare https://www.fimfiction.net/story/363399                                                                                                                                                                        
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.3.0', 'console_scripts', 'fanficfare')())
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 353, in do_download
    configuration = get_configuration(url,
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 635, in get_configuration
    options.cookiejar = configuration.get_cookiejar()
  File "/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 1037, in get_cookiejar
    return self.get_fetcher().get_cookiejar(filename)
  File "/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 994, in get_fetcher
    self.fetcher = fetchcls(self.getConfig,
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 400, in __init__
    self.retries = self.make_retries()
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 409, in make_retries
    return Retry(total=4,
TypeError: __init__() got an unexpected keyword argument 'other'
```
Tested with stable release and also with 4.3.14 (dbba0d5c). Both giving same result.

**Comment by JimmXinu** [comment]
FFF needs `urllib3` >= 1.26.2 specifically for `Retry(other=)`.

Are you installing FFF through `pip`?  Because it should be requiring a sufficiently new version of `urllib3`.

**Comment by diggit** [comment]
I have it installed via package manager, despite that, I have _python-urllib3 1.26.6_

**Comment by JimmXinu** [comment]
`urllib3` 1.26.6 does contain the `Retry(other)` setting and does work with FFF.

I believe the problem lies somewhere with your packages; you'll have to contact the package maintainer. 

 I don't have the time or knowledge base to support all the different package managers.  I only support problems in FFF directly or with the `pip` installed version I maintain.

I believe @eli-schwartz maintains the Archlinux FFF package?

**Comment by eli-schwartz** [comment]
It works for me.

Can you post the output of:
```
python3 -c 'import urllib3; print(f"{urllib3.__file__=}, {urllib3.__version__=}")'
```

**Comment by diggit** [comment]
You hit a nail on the head...
`urllib3.__file__='/home/diggit/.local/lib/python3.9/site-packages/urllib3/__init__.py', urllib3.__version__='1.25.11'`
after purging pip installed packages
`urllib3.__file__='/usr/lib/python3.9/site-packages/urllib3/__init__.py', urllib3.__version__='1.26.6'`

Now, everything works fine.
Thanks! :)

**Comment by eli-schwartz** [comment]
Right, this can happen if you pip install fanficfare, then afterwards you pip install something that requires a lower version. The good version of urllib3 gets uninstalled, even though other modules need it, in order to let the latest installed module use a lower version.

Or pip install urllib3 a long time ago to /home, then pip install fanficfare as root so it gets installed, alongside the correct version of urllib3, to /usr. But when running fanficfare as a user, you end up with the /home version on your PYTHONPATH by default, even though it's old and out of date.

pip isn't a true package manager, merely an installer -- it doesn't do full environment consistency checks, much less consistency checks spanning multiple python environments, some of which may or may not be active at the time.

Anyway, happy to help. :)
