### ISSUE TITLE
website requests

### ISSUE THREAD

**Issue by CodeyAce95** [JimmXinu/FanFicFare#722]
could we get more wuxia novel website support

**Comment by JimmXinu** [comment]
Unlikely.  I have no interest and there hasn't been a lot of interest from other developers.  

Plus, I consider wuxia novel sites outside of FanFicFare's mission--my understanding is they usually aren't fanfiction.  

I also worry more about the possible legal ramifications.  Fanfiction authors don't have as much legal or moral ground for complaint vs original content creators.  See #440.

Closing this issue since it doesn't actually specify any sites.
