### ISSUE TITLE
Just a Query

### ISSUE THREAD

**Issue by JoshMovell** [JimmXinu/FanFicFare#725]
Hello,
I am new to programming and wanted to ask you a question.
How does your plugin take data from sites like spacebattles or QuestionableQuesting.
Does it share Users data like ip address or device used.
Cause from what I read on Xenforo platform. They keep record for every guest user through cookies.
Also does this Calibre plugin work like browser request for any page on these forums.
Please consider this request from a new beginner.

**Comment by JimmXinu** [comment]
Ultimately, FFF uses the `requests` library to perform HTTP requests; see https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/fetcher.py#L456

IP address--at least the external IP address used--is _always_ exposed to the web server.  It's an intrinsic part of TCP/IP and the only way the server can send packets back to you.  However, VPNs and masquerading firewalls are common, which is why I say 'external IP address'.

FFF is only designed to get 'stories', which for xenforo sites we define as either a thread with threadmarks or a post containing links to other posts.  The threadmarks or links are used as a chapter list.  FFF deliberately cannot download all posts for a thread as that would be too easily abused, IMO.

I'm closing this because it is not an issue with FFF.  Quoting from the project home page:
> There's also a [FanFicFare maillist](https://groups.google.com/group/fanfic-downloader) for discussion and announcements and a [discussion thread](https://www.mobileread.com/forums/showthread.php?t=259221) for the Calibre plugin.
