### ISSUE TITLE
Change default filename in CLI

### ISSUE THREAD

**Issue by HappyFaceSpider** [JimmXinu/FanFicFare#727]
I'm a little noob where it comes to CLI, so I thought I'd try asking: is there a way to change the default filename of the output file, when downloading multiple fics at the same time? I would like to change it to, for example, {fandom}-{author}-{title} or smth similar.

**Comment by JimmXinu** [comment]
That is exactly what the `output_filename`(`defaults.ini` [link](https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/defaults.ini#L150)) setting is for.  You can change it in your `personal.ini`([FAQ link](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#where-is-this-personalini-i-keep-reading-about)) by default, site or even individual story.

Issues are for problems with FFF.  I'm closing this because it is not an issue with FFF.  Quoting from the project home page:
> There's also a [FanFicFare maillist](https://groups.google.com/group/fanfic-downloader) for discussion and announcements and a [discussion thread](https://www.mobileread.com/forums/showthread.php?t=259221) for the Calibre plugin.
