### ISSUE TITLE
Tags not being added for WebNovel.com & Wuxiaworld.com downloads with Calibre Plugin

### ISSUE THREAD

**Issue by 4getter** [JimmXinu/FanFicFare#730]
So, for every WebNovel.com & Wuxiaworld.com  book I download only the tags `FanFiction, In-Progress` & `Fanfiction` are being added respectively(Even though the books are not FanFictions). Tags like `Kingdombuilding`, `Reincarnation` etc are not being added to the books.

I tried `fanficfare` pip version with `fanficfare -j -m` and I found the tags like `KingdomBuilding` being shown in the `Site tags` in the json output in Webnovel.com books. I am not sure if the pip version writes the tags to the books or if it has the same problem as the Calibre version, since I don't know how to check the tags of epub books.

My guess is `category`/`cattags` tags are being written, but not the `sitetags`/`poptags`.

**Comment by JimmXinu** [comment]
webnovel.com and wuxiaworld.com are two different sites that are parsed by different code.  That said, I think your issue is user configuration, not code.

The webnovel.com adapter (the FFF code that parses it) collects site specific metadata items `translator`, `editor`, and `sitetags`, which should by default be appearing at the end of the title page (but may not be if you have set `extra_titlepage_entries` yourself in personal.ini).  

The wuxiaworld.com adapter collects site specific metadata item `tags` but doesn't put it anywhere by default.

All of those are not included in Calibre's tags by default.  The `include_subject_tags` is used in personal.ini to control what metadata items appear in Calibre's tags field.  See [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#how-do-i-control-what-is-sent-to-the-tags-fields-in-calibre) and search the [MR forum thread](https://www.mobileread.com/forums/showthread.php?t=259221) for `include_subject_tags` and `add_to_include_subject_tags`.

FanFicFare by default assumes all downloads are FanFiction.  Some sites are configured in defaults.ini to _not_ be marked FanFiction, but webnovel.com and wuxiaworld.com aren't currently.  I will change that by default if you can testify that all or most of the stories on each site are not FanFiction.

If you still think there's a problem with the collected metadata, please provide example story URLs and the tags/info that you think should also be collected.

**Comment by 4getter** [comment]
Yes, I can testify that most of the novels on both the sites are not fan-fiction. There is some fan-fiction, but it's amount is very small.
The content is mainly Chinese translated novels and original English novels by community Western authors with only a little fan-fiction.
Both sites are like this.

**Comment by JimmXinu** [comment]
Assumed resolved.
