### ISSUE TITLE
RoyalRoad CLI `--imap` special handling fails; SSL cert expired due to Let's Encrypt expiration

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#746]
I did upgrade to version 4.6.3, but I still get this error:

```
FFF: ERROR: 2021-10-15 05:06:18,695: geturls.py(262): Failed to read email content: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)
```

Any idea how to fix?

**Comment by JimmXinu** [comment]
I'm not having any problems.  

Your error is an expired cert:

> `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)`

Since it doesn't appear that the site's cert is expired, you may have an expired validating certificate in your cert store.  I would try updating your installed [`certfi`](https://pypi.org/project/certifi/) package, and/or your computer's/python's cert store.

See [this FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#im-having-ssltls-certificate-errors--help) for a few more details.

**Comment by JimmXinu** [comment]
SSH and HTTP over SSL, aka https are unrelated.  

'HTTP cache' and 'cert store/cache' are also unrelated, albeit similarly named.

I confess that I didn't notice your error was for getting URLs from email.  In my defense, you didn't mention it, either; and 99/100 the answer to SSL issues is 'update your cert store'.  

I suspect that is still the answer.  

Especially since the domain `email-click.royalroad.com` cert was re-inssued Oct 1 and is signed by "Let's Encrypt" which somewhat famously had it's cert expire the day before that.  And `certifi` was updated Oct 8 with new certs.  

(I only know about `email-click.royalroad.com` being used in RR emails because of a different issue from the plugin forum.)

I don't recognize your windows Python install.  I would suspect that perhaps it doesn't have the latest certs or `certifi` available; or that the latest `certifi` installed somewhere it doesn't use.  The random chars in the path name suggest some environment isolation is going on.

I assume from the way you reported this that you are using FFF CLI, not Calibre.  You should be able to check your installed `certifi` with:

`python -c "import certifi; print(certifi.__version__)"`

It should report `2021.10.08` if it's up to date.

**Comment by MrTyton** [comment]
Ah, yes, sorry for the confusion, I should have specified. My bad.

So, you were partially correct? Apparently there's 2 python environments, and it's very awk about which one that it's using. For clarity's sake, I am now using python 3.9 explicitly for everything, and in that env have updated certifi to latest and fanficfare to latest versions as stated above.

However, there's still an error:



```
C:\> python3.9 -c "import certifi; print(certifi.__version__); from fanficfare import geturls; import socket; print(geturls.get_urls_from_imap($CENSORED_ARGUMENTS));"
2021.10.08
FFF: WARNING: 2021-10-16 01:16:18,883: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/Rk7FatYY, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:19,112: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/I3LBQkVb, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:19,441: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/GkUopL5z, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:19,678: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/FM9bPeJf, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:19,965: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/SZPU3VQo, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:20,204: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/dGxXzVDA, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:20,442: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/hM9g504B, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:20,669: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/UKnKCHWu, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:20,898: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/ddAHcmdI, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
FFF: WARNING: 2021-10-16 01:16:21,139: geturls.py(184): Skipping royalroad email URL https://email-click.royalroad.com/a9chxm/KSxXMA2y, got HTTP error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
set()
```

So certifi seems to be up to date, but it's still getting an ssl error - albeit, a _slightly_ different one than before.

**Comment by JimmXinu** [comment]
Okay, looking at this again in the morning, I advised you incorrectly because I'd forgotten an implementation detail.  My apologies.

The 'get from page/imap' code has a special case in it for royalroad.com because they use click through tracking links in their notification emails.  FFF look for `if ('click' in href or 'fiction/chapter' in href) and 'royalroad' in href:` and if found, fetches the link, looks at where it redirected to, and uses that redirect link instead.

What I forgot or failed to realize last night is that piece of code was not changed to use `requests` when the actual story download code was.  So it uses whatever cert store `urllib` does, not `certifi`.  

So instead of updating `certifi`, you need to update whatever cert store the built-in `urllib` package is using.  Something that used to work for many Calibre plugin users on Windows was visiting the site in MS Explorer (or Edge now I suppose?) It's `https://email-click.royalroad.com` causing the issue.

Beyond that, I would just be googling solutions and I assume you can do that as well as I can.

I will look into changing that code to also use `requests` and that should at least consolidate any future problems.

**Comment by MrTyton** [comment]
No need to apologize, I appreciate the help. Everything that you've said makes sense here.

I tried visiting it in Edge, and I also tried using OpenSSL to import the certificates into the windows directory, but nothing ended up working. I'll wait until you update that part to requests then.

Thank you again for the assistance with all of this.

**Comment by MrTyton** [comment]
Seems to work for me, I'm getting the URLs now. Thanks for the help!

Closing for now.
