### ISSUE TITLE
the adaptor https://novelonlinefull.com redirects to https://bestlightnovel.com/ when getting stories. could this adaptor be changed?

### ISSUE THREAD

**Issue by mhussaincov93** [JimmXinu/FanFicFare#774]
when fanficfare starts getting stories using the domain novelonlinefull.com it starts getting chapters from the domain 
https://bestlightnovel.com/
and not novelonlinefull.com
here is an exammple of such a switch
if you start getting this story,
https://novelonlinefull.com/novel/invincible
after the first request the domain changes.
to something like
https://bestlightnovel.com/novel_888132160/chapter_1
am I going mad or something?
I would be greatful if you could peek in to this,
sorry for spelling errors, I am using a screen reader.
Majid Hussain

**Comment by Edocsil** [comment]
If you go to that website on your browser and click on any of those chapters, you see they are hosted on that different site.  It seems like the owner is trying to redirect the traffic towards a new website.

**Comment by JimmXinu** [comment]
I agree that novelonlinefull.com could be migrating to a new name.  Back in October 2018 (#346) the existing site lightnovelgate.com changed to novelonlinefull.com, which was similar to bestlightnovel.com.  It could also be they intend to support both and it's a mistake in the site templates.

Aside from the chapter links, I don't find anything that indicates which name would be more correct.  

And the chapters being on a different domain doesn't actually hurt anything that I can see.

@mhussaincov93 - Have you seen any announcements that the site domain name is changing?  Or know how long it's been like this?

The story URLs (https://novelonlinefull.com/novel/invincible vs https://bestlightnovel.com/novel_888102349) don't match, so it may not be a simple domain name swap to change the adapter in FFF.

**Comment by mhussaincov93** [comment]
hi,
no just noticed this when searching for another site to use with fanficfare because
wuxiaworld.co at time of writeing is not online.
thank you for looking in to this for me :)
Majid

**Comment by JimmXinu** [comment]
I've looked at this again; it appears the site has stories with chapters hosted on novelonlinefull.com _and_ bestlightnovel.com appearing on the front page.

It looks to me more like the on-going merger of two sites rather than a migration from one name to another.  And the story level URLs aren't necessarily the same between sites.  So changing the adapter to bestlightnovel.com would likely invalidate people existing books with novelonlinefull.com story URLs.

As long as the novelonlinefull.com adapter continues to work, I'm not going to worry about it.  You can open a new issue if it becomes a problem in future.
