### ISSUE TITLE
Setting default download directory using variables

### ISSUE THREAD

**Issue by gralsean16** [JimmXinu/FanFicFare#794]
I'm trying to set up FFF on Android via Termux. Whenever I tried to set `output_filename` to something like `~/storage/downloads/${title}-${siteabbrev}_${storyId}${formatext}`, instead of directing to the home directory, it instead creates a folder named ~ to the current directory. How can I set it up so that it directs to the home directory?

**Comment by stranger-danger-zamu** [comment]
Using the full explicit path (`/home/<username>/storage/downloads/${title}-${siteabbrev}_${storyId}${formatext}`) would be one way. Another is to use the `-o` flag and set the output_filename with the `$HOME` env var (ie. `fanficfare <url> -o $HOME'/storage/downloads/${title}-${siteabbrev}_${storyId}${formatext}'`). 

I usually just run the command in the directory where I want it to download, but a default download directory configuration option would be nice.

**Comment by Edocsil** [comment]
`/data/data/com.termux/files/home/storage/downloads/`

That's the full path in case you don't know how to find it.

`output_filename: /data/data/com.termux/files/home/storage/downloads/epubs/fanficfare/${title} - ${author}${formatext}`

That's how I have it set up in my `personal.ini`. Since it's something that you only configure once (well, maybe a couple more for each website) I don't think you need to use variables for anything.

**Comment by gralsean16** [comment]
Managed to set it up with `termux-url-opener` (basically using android's share function to download). Thanks :)
