### ISSUE TITLE
Conversion of transparent text from Xenforo sites

### ISSUE THREAD

**Issue by alethiophile** [JimmXinu/FanFicFare#812]
At some point in the past, FanFicFare would render transparent "invisitext" from Xenforo sites with strikethrough text in the resulting ebook. This seemed like a good compromise to mark out that text.

Now this is no longer happening, and instead the text is rendered as normal text without any marker. (I assume this is due to a difference in how those sites rendered invisitext.) It would be good to update this and make it return to the old behavior. One story that I use as a test case for this is https://forums.spacebattles.com/threads/xander-quest-thread-twenty-five-happy-sixth-i-mean-ninth-birthday.720100/.

**Comment by JimmXinu** [comment]
I don't remember FFF ever having exactly that.  

There is an option for base_xenforoforum sites, if `reveal_invisible_text:true` in personal.ini, FFF will find all `span` tags with `style="color:transparent"` and remove the `style` attribute.

Infortunately, invisitext is implemented different ways by different authors--`reveal_invisible_text` does nothing if the author manually set the color white (or black) to match their background.

If invisitext is implemented as a class, then custom CSS can be applied to change the appearance pretty easily, but may depend on the site and author.

In the example you give, it's done as `span style="color:transparent"`,  just as `reveal_invisible_text` is looking for.  You can change how that's handled with some clever CSS settings like so:

```
[https://forums.spacebattles.com/threads/xander-quest-thread-twenty-five-happy-sixth-i-mean-ninth-birthday.720100/]

# style attrs stripped by default
add_to_keep_html_attrs:,style

# usually off by default, but sounds like you have it on
reveal_invisible_text:false

# add to CSS; '!important' causes it to override the style attr.
add_to_output_css:
 span[style*="color:transparent"] { color:black !important; text-decoration: line-through; }
```

I would probably pick something other than line-through, like a gray color or something for that story--it already uses `<s>` tag strike-throughs in the text.

**Comment by alethiophile** [comment]
I don't have `reveal_invisible_text` on, but since the transparency is introduced in a `style` attribute, it gets stripped out automatically regardless. Whereas in the source those elements have `class="fixed-color" style="color: transparent"`, in the epub they only have `class="fixed-color"`.

It's true that sometimes authors set the text color to the same as the background manually, but this is unreliable even on the site -- users viewing under different site themes have different background colors. Thus, I don't think that this case really needs to be handled. Being able to customize the output in this case is nice, but it would be good to have some default that isn't stripping the formatting completely.

**Comment by JimmXinu** [comment]
FFF defaults to stripping formatting so stories all look the same.  I consider that one of FFF's primary features.

You can add `add_to_keep_html_attrs:,style` under `[defaults]` if you want to keep them across the board.

`reveal_invisible_text` was added as a [comprise feature](https://groups.google.com/g/fanfic-downloader/c/OsZ9dowyv60/m/p5tg9OO7FwAJ) for a user wanting both style attributes and to reveal invisible text.  Since you wanted to *change* the appearance instead, I found a CSS solution.  

Unfortunately, Calibre's convert completely rewrites the CSS and discards the `important!`.  So the CSS solution doesn't work through Calibre convert, which many people use for with Kindle.

I propose to change `reveal_invisible_text` to add class `invisible_text` to all span tags that it finds with `style="color:transparent"` as well as removing the style attribute.  This is done before `keep_html_attrs` is applied, so that wouldn't matter either way.

It would still require some additional CSS, for example:
```
add_to_output_css:
 .invisible_text { color:gray; }
```
I will add something like that to `defaults.ini`, but probably commented out.

Will that satisfy your needs?

**Comment by alethiophile** [comment]
That will work fine. It basically matches my current solution, which is to use Calibre's tools to rewrite the `fixed-color` class to a more appropriate name, then manually add some appropriate CSS.

I think that stripping styles is broadly the correct decision, especially since this automatically preserves common "semantically meaningful" tags like `em`/`strong`/etc. Unfortunately, you occasionally come across a case where authors have invented their own semantically meaningful inline tags and implemented them as styles. Per-site or per-story customization is probably the only sensible way to handle this case.

**Comment by JimmXinu** [comment]
Test versions posted in the usual places.
