### ISSUE TITLE
Stalls out downloading from SufficientVelocity

### ISSUE THREAD

**Issue by Anti-weakpasswords** [JimmXinu/FanFicFare#820]
Calibre 5.40 (64-bit)
FanFicFare v4.11.0
Example URL:
https://forums.sufficientvelocity.com/threads/all-wo-rk-and-no-play-an-abyssals-trials-in-the-job-market-kc.54131/

Note that many other books have downloaded from sufficientvelocity just fine.
Spacebattles may have the same issue, I haven't tested thoroughly, I just cut over to SufficientVelocity.

A library with a couple thousand books in it.

Download from URLs
Enter URL or list of URLs - in this example, a single one that is a brand new book to the library

Gets the metadata ok
Starts the job
Download 1 Fanfiction Book(s) works for awhile, then stalls out near the end at 96% after a few minutes.
10 hours 18 minutes later, it's still at 96%

Job details:
Download 1 FanFiction Book(s)
FFF: INFO: 2022-04-05 03:55:45,127: calibre_plugins.fanficfare_plugin.jobs(49): CPUs:3
FFF: INFO: 2022-04-05 03:55:45,127: calibre_plugins.fanficfare_plugin.jobs(52): FanFicFare v4.11.0
FFF: INFO: 2022-04-05 03:55:45,128: calibre_plugins.fanficfare_plugin.jobs(68): Launch background process for site forums.sufficientvelocity.com:
https://forums.sufficientvelocity.com/threads/all-wo-rk-and-no-play-an-abyssals-trials-in-the-job-market-kc.54131/

**Comment by JimmXinu** [comment]
That story downloaded in 2m 39s for me.

Unless you have `slow_down_sleep_time` set high, or the site is actively throttling you, I'm not sure why it would hang for that long instead of timing out and failing.  If you've been downloading a lot from the site, it's entirely possible that you may be on a list for throttling.

Things you can try:
- Restart Calibre in debug mode and try again to see if there's anything useful reported.
- Download only part of the story at a time.  There's 120 threadmarks, so use URL:
  `https://forums.sufficientvelocity.com/threads/all-wo-rk-and-no-play-an-abyssals-trials-in-the-job-market-kc.54131/[-60]`
  ...to get the first half, then update it a while later to get the rest.
- Wait a few days, you'll probably be off any throttle lists by then.

I'm going to close the issue because I don't think there's anything in FFF to be fixed related to this.  You can still add comments.

**Comment by Anti-weakpasswords** [comment]
Thank you very much for this program and for your quick response! The ability to update stories with new chapters in bulk is exactly what I've wanted for more than a decade!
[-60] worked, as did [-90], and then when I tried [-119] it stalled out again near the very end, running from the Calibre plugin.
Would [115-120] download only the last 5 chapters?  I couldn't find the syntax in the wiki, probably because of user error on my side.

**Comment by JimmXinu** [comment]
Yes, you can do ranges.  Note that if you do [115-120] and update the same ebook, you will _only_ get chapters 115-120--any prior existing chapters will be discarded.  You can use the 'Add New' mode to make a new book instead.
