### ISSUE TITLE
Plugin omits some lines when downloading from webnovel

### ISSUE THREAD

**Issue by seba11998** [JimmXinu/FanFicFare#841]
Some lines are being omitted by the plugin

Example: https://www.webnovel.com/book/new-god-in-marvel_21731452906433805/one-hundred-years_59330697923456658
Source:
```
After what seemed even longer than the first one. 
<Congratulation you've won the ability Devourer"
And for the last spin, the draw took even longer before finally 
```
Output from plugin:
```
<p>After what seemed even longer than the first one.</p>
<p>And for the last spin, the draw took even longer before finally</p>
```
This happens in several chapters of different novels.

**Comment by JimmXinu** [comment]
Can you confirm that it always/only happens when the line starts with `<` (the less than symbol)?

The FFF adapter is unusual because it has to pick the story text out from a data structure embedded in the HTML containing each paragraph/line of text separately.  Currently it looks for a leading `<` and treats the paragraph/line as HTML if it finds one.  This is because during testing I found a story where each paragraph already had `<p>` tags around it.

A few more examples, especially if any of them are not lines staring with `<` would be helpful to try and fix this without breaking anything else.

**Comment by JimmXinu** [comment]
[Test versions](https://github.com/JimmXinu/FanFicFare#test-versions) with a fix posted.
