### ISSUE TITLE
Where are the instructions on how to use this?

### ISSUE THREAD

**Issue by instaloadererror** [JimmXinu/FanFicFare#901]
I saw that there are two different versions of this: Calibre and Python. I can't find any instructions on how to use either. I don't use Calibre so I'm not sure if that version will support downloading html files which is what I want. I managed to install it using cmd.exe and typing "py -m pip install FanFicFare" but I now have no idea at all what the commands are to actually download anything. Am I just stupid? I genuinely don't see instructions anywhere. I'm mostly just trying to find a tool that will download side story and aprocypha threadmarks from forums.spacebattles.com.

**Comment by JimmXinu** [comment]
I don't have any step-by-step documents.  

As a general rule, the CLI is meant for tech savvy users who want to have extremely fine control over their library of downloads.

I recommend using Calibre and the Calibre plugin for most users and to download to EPUB format and use Calibre's excellent Conversion feature to change it to whatever format you actually use.  This is because FFF can update EPUBs with new chapters without re-downloading everything.

`fanficfare -h` gives the CLI options.  

At it's most basic, to download to HTML files:
`fanficfare -f html <storyUrl>`

You can limit downloads of SB/SV threads to only side story and aprocypha threadmarks on a per story basis with `personal.ini` settings:
```
[https://forums.sufficientvelocity.com/threads/thread-title.99999/]

## xenforoforum has categories of threadmarks.  This setting allows
## you to leave out categories you don't want.  Skipping categories
## will also speed downloads as categories other than 'Threadmarks'
## don't use Reader Mode.
## The last known list of categories is:
## Threadmarks,Sidestory,Apocrypha,Media,Informational,Staff Post
skip_threadmarks_categories:Threadmarks,Media,Informational,Staff Post
```
Or replace the story URL section header with `[forums.spacebattles.com]` for all SB stories or even with `[base_xenforoforum]` for all SB/SV/QQ/etc stories.

I'm closing this because it isn't really an issue as such.

**Comment by instaloadererror** [comment]
Thank you. 

When I try that I get an error, though.

'fanficfare' is a package and cannot be directly executed

Do you know why this is?

**Comment by JimmXinu** [comment]
If you installed it with `pip` [as instructed](https://github.com/JimmXinu/FanFicFare#getting-fanficfare), there should be an executable named `fanficfare` installed.  You might get that if you are in the dir `pip` installs packages in?  

I really couldn't say for sure--it's going to depend on your setup.

**Comment by instaloadererror** [comment]
I did use the instructed install. I was told before I had to start with "py -m" but that's the only difference. I had already done it before when I first tried using it so it told me everything was already satisfied.

C:\Users\student>py -m pip install FanFicFare

Requirement already satisfied: FanFicFare in c:\users\student\appdata\local\programs\python\python310\lib\site-packages (4.18.0)

**Comment by JimmXinu** [comment]
Yes, it does install on correctly on Windows.

I don't know where your `py -m` instruction came from--it suggests your python (or pip) is installed in a way I don't know.  

Another possibility is that you have a directory named `fanficfare` in your current working directory that's conflicting.
