### ISSUE TITLE
Proxy Problem: None of the 1 URLs/stories given can be/ need to be downloaded.

### ISSUE THREAD

**Issue by circrna** [JimmXinu/FanFicFare#916]
![image](https://user-images.githubusercontent.com/124867983/217747103-12b1aa28-acaf-40c6-afc1-510b514f44f1.png)
i always get this when i download something from ao3 and wattpad
if i can know how to fix it i would be very appreciate, THANK YOU

**Comment by circrna** [comment]
by the way, I use VPN to visit all pages，i guess is there any problem related with that

**Comment by JimmXinu** [comment]
I'm not seeing any issues with wattpad or AO3 downloads.  You will also see that if you don't need to update because there aren't any new chapters.

If it is something to do with the VPN I won't be able to help you with anything.

Did you look at the log to see what it said?  There's also more info if you run Calibre in debug mode (under Calibre Preferences drop down) and look at the debug log.

**Comment by CyberPengu1n** [comment]
Same issue. 

Here is the log: 
Unknown
Unknown
HTTPSConnectionPool(host='www.fanfiction.net', port=443): Max retries exceeded with url: /s/459617/1/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
https://www.fanfiction.net/s/459617/1/

Not sure if this could help, but please let me know how to fix this

**Comment by JimmXinu** [comment]
I really don't know much about using proxies.  I do know that fanfiction.net doesn't work directly for most users.  See [FAQ](https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet--why-am-i-getting-cloudflare-errors-downloading-from-fanfictionnet).

There are a couple settings in FFF to explicitly set proxy, but as I recall, they didn't help the user they were originally added for:
```
[defaults]
## using your numbers instead of this example
https_proxy:http://192.168.42.129:8080
http_proxy:http://192.168.42.129:8080
```
