### ISSUE TITLE
[Enhancement] A solution for Photobucket watermarks

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#940]
Something that's come up before was Photobucket's watermarks being downloaded:

https://www.mobileread.com/forums/showpost.php?p=4099090&postcount=5596
https://www.mobileread.com/forums/showpost.php?p=4312189&postcount=8304

Some possible solutions:

- Leave as is. When searching the MobileRead forums and github for 'photobucket' and 'watermark' I'm the only one who reported the problem. Unless there's more posts I haven't seen on the google group that hints that it's not a very widespread problem.
- Setting the HTTP referrer header to the same as the image, perhaps with a customizable pattern.
- As the cache-control on the images are `max-age=31536000, public`, in _theory_ pulling them from the cache (perhaps with a customizable pattern) might work. I didn't have any luck, but AO3 has a `no-cache` so that probably messed it up.

Thanks in advance.

**Comment by JimmXinu** [comment]
Using the page the `<img>` tag is on as the referrer is the best way to get the same results as browser.  That's what referrer is for.

The watermarks appear in the story on AO3 when viewed in the browser.  So FFF is no worse that AO3 itself.  

This looks like a case of trying to solve particular authors' mistakes in FFF.  Or more charitably, an image host site that has changed.

The most I am willing to do right now for this rare corner case is add a single new setting that will let you force what the referrer is for image look ups, like: `force_img_referer:http://i716.photobucket.com/`  You would set it for a specific story URL.  

Browser cache for bucket images doesn't work due to esoteric details of domain caching.  Not getting into it.

**Comment by chocolatechipcats** [comment]
> Or more charitably, an image host site that has changed.

This is what happened - first they [replaced all images with a "you need to upgrade your account 😠"](https://www.ghacks.net/2017/06/30/photobucket-now-charges-399-for-third-party-hosted-images/) but then rolled back a bit and just stuck an ugly watermark on it.

**Comment by JimmXinu** [comment]
Looking at #940 and #941, I plan to change `force_img_referer` to `force_img_self_referer` instead.  That way the user doesn't need to figure out the referrer URL and it will still work with images from different hosting sites.

```
## If set true, FFF will use the img tag's own src URL as the HTTP
## Referer instead of the page URL.  This is useful for some image
## hosting sites that watermark or return HTML instead of image data
## without it.
#force_img_self_referer:false
```
(Note that Refe**r**er is correct when talking about HTTP--it's a [typo in the standard](https://en.wikipedia.org/wiki/HTTP_referer) we're all stuck with.)

**Comment by chocolatechipcats** [comment]
Additional thought: would a force_image_self_referer_pattern make sense? This way the user could enable it in [defaults] but only for, e.g., `.*photobucket\.com` (regex is a bit sloppy).

**Comment by JimmXinu** [comment]
I was hoping to avoid making the user find the host name(s), but with a pattern it doesn't have to be set for each story, which is probably better.

```
## If set, and the img tag's URL matches the regular expression, FFF
## will use the img tag's own src URL as the HTTP Referer instead of
## the page URL.  This is useful for some image hosting sites that
## watermark or return HTML instead of image data without it.
#force_img_self_referer_regexp:gelbooru.com|photobucket.com
```
