### ISSUE TITLE
Scribblehub can't use Browser Cache -- use flaresolverr instead

### ISSUE THREAD

**Issue by TheAkashicTraveller** [JimmXinu/FanFicFare#964]
When trying to download from scribblehub I get this `Error | Unknown | Unknown | 'NoneType' object has no attribute 'get' | https://www.scribblehub.com/series/70708/witch-of-chains/`
when I have the page cached, when it's not cached I get the normal `HTTP Error in FFF 'Page not found or expired in Browser Cache (see FFF setting browser_cache_age_limit)'(428)` so no idea what's happening. MZCacheView can find and open the file fine.

**Comment by JimmXinu** [comment]
Scribblehub doesn't work with FFF's Browser Cache feature because the API request to get story info needs to be an HTTP POST and browsers don't cache those.  It's more than just the one page.

Using [FlareSolverr proxy](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures#flaresolverr) is the only way I currently know to use FFF to download from Scribblehub.  I was able to download that story using FlareSolverr.

**Comment by TheAkashicTraveller** [comment]
> Scribblehub doesn't work with FFF's Browser Cache feature because the API request to get story info needs to be an HTTP POST and browsers don't cache those. It's more than just the one page.
> 
> Using [FlareSolverr proxy](https://github.com/JimmXinu/FanFicFare/wiki/ProxyFeatures#flaresolverr) is the only way I currently know to use FFF to download from Scribblehub. I was able to download that story using FlareSolverr.

That works cheers.

**Comment by mhussaincov93** [comment]
hi,

I just changed the user agent which worked.

Majid
