### ISSUE TITLE
StoriesOnline not downloading/updating again

### ISSUE THREAD

**Issue by Dwraith0877** [JimmXinu/FanFicFare#99]
Calibre Plugin up to date
http://storiesonline.net/s/75073 and many others, though a few did work at first
output format mobi
overwrite always
result: Error: 'NoneType' object has no attribute 'find'
was working when I copied the adapters folder from the 2.2.2 version into the most recent, but it had those annoying links under the chapter headings, which added many extra lines to the book, resulting in many extra pages... 2.2.3 has removed those links, but now has issues with SOL again...

**Comment by cryzed** [comment]
The issue seems to be that the adapter still uses Beautiful Soup 3, which seems to have trouble parsing the HTML (the first few chapters turn up empty for me, after fixing the lines responsible for locating the article-tag).

When I tried to use Beautiful Soup 4 instead, it seemed to work until an [internal Beautiful Soup error](https://gist.github.com/cryzed/5c9298ea864f957ccae6) was raised during parsing one of the later chapters, which doesn't look very promising. Stuck between a rock and a hard place it seems...

**Comment by JimmXinu** [comment]
There are two places in the code that look for the same 'story' element. I'd only updated one of them in my change. So that's my bad. @cryzed, I've pushed those changes to master.

Plugin test version posted for latest storiesonline.net changes. http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

Also test version of web service: http://2-2-4.fanficfare.appspot.com/

storiesonline.net has such nasty HTML, it doesn't surprise me that bs4 has problems parsing it.  Did you use self.make_soup() or call bs4 directly to make the soup? make_soup explicitly uses html5lib and re-soups because that works better for improperly nested tags.

**Comment by cryzed** [comment]
I called the bs4.BeautifulSoup constructor directly instead of using the method, my knowledge about writing adapters (and thus such methods) is a bit limited, as can be seen from the other adapters I wrote. The new version seems to work, although these lines appear quite often:

> FFF:ERROR:base_adapter.py(544):Error parsing HTML, probably poor input HTML. 'NoneType' object has no attribute 'next'

**Comment by JimmXinu** [comment]
As I said: nasty HTML. ;)

It looks like they may still be changing the HTML, too.  Either that, or different stories just have different issues that I didn't see in my testing--I don't read that site, so it's entirely possible.  (And davidfor wrote the adapter originally (as I recall) using some different techniques than I usually use.)

I've pushed another merge to master for storiesonline.net that switches it to use bs4 (via make_soup()) and removes some more footer elements.  Test versions as linked to before updated.

**Comment by cryzed** [comment]
The test version seems to work on my end now for this story: No empty chapters and no unwanted elements in the HTML as far as I can tell; I'm pretty confident this issue can be closed with the next release.

**Comment by JimmXinu** [comment]
FYI, there's another test version posted with yet more fix for changes to the site.  It appears to be moving target lately.

**Comment by JimmXinu** [comment]
Fixed in d51bb8373f46734204834b92060ecc818ac123b5.
