### ISSUE TITLE
Error downloading some fanfics from fanfics.me

### ISSUE THREAD

**Issue by YusAli17** [JimmXinu/FanFicFare#999]
Most are fine, but some urls gives errors like:
https://fanfics.me/fic133819 give "list index out of range"
https://fanfics.me/fic97228   give "Error downloading Chapter: https://fanfics.me/read.php?id=97228&chapter=2#start_read!  Missing required element!"
Calibre plugin

**Comment by JimmXinu** [comment]
https://fanfics.me/fic133819 is caused by a third different version of 'Translator' (`Переводчик`, `Переводчи`, and now `Переводчики`), so that's an easy fix.

https://fanfics.me/fic97228 is a fic that mismatches chapter 'number' and location in chapter list.

I've posted a test version that addresses these problems.  Please check that the correct chapter texts are downloaded for both these and other stories.  Thanks.

**Comment by YusAli17** [comment]
Hi, I tested it with both of these stories, they downloaded fine.
After that I tested with some others, there are still errors with the stories.

> list index out of range | https://fanfics.me/fic49471
> list index out of range | https://fanfics.me/fic121130
> list index out of range | https://fanfics.me/fic123822
> list index out of range | https://fanfics.me/fic102014
> list index out of range | https://fanfics.me/fic60589
> list index out of range | https://fanfics.me/fic1057

I don't know if this will help, but in all of them, 2 authors are indicated in the `Авторы:` field

**Comment by JimmXinu** [comment]
:shrug: I don't read that site--I'm not going to see any errors that aren't reported.  I'll look at these, too.

**Comment by JimmXinu** [comment]
Those stories work for me now.

**Comment by YusAli17** [comment]
It worked for me too, thanks.
